<h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Users'); ?> </h4>

<form>
	<div class="table-responsive">
		<table class="table table-striped table-hover table-bordered">
			<thead>
				<tr>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Name'); ?></th>
					<th class="text-center"><?php $this->show('Login'); ?></th>
					<th class="text-center"><?php $this->show('Email'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>
			
			<?php if (!empty($users)): ?>
			<tbody>
				<?php foreach ($users as $user): ?>
				<tr>
					<td class="text-center text-muted"><?php echo $user->getId(); ?></td>
					<td class="text-center"><?php echo $user->getName(); ?></td>
					<td class="text-center"><?php echo $user->getLogin(); ?></td>
					<td class="text-center"><?php echo $user->getEmail(); ?></td>
					<td class="text-center">
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this user'); ?>" data-button="edit" href="<?php echo $this->url('Cms:Admin:Users@editAction', $user->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this user'); ?>" data-button="delete" data-id="<?php echo $user->getId(); ?>" data-category="main" href="#"><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
			<?php endif; ?>
			
		</table>
		
		<?php if (empty($users)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No users'); ?></h2>
		</div>
		<?php endif; ?>

		<div class="pull-left">
			<a class="btn btn-primary btn-sm" href="<?php echo $this->url('Cms:Admin:Users@addAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add new user'); ?></a>
		</div>
		
	</div>
</form>
