<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Users'); ?> <small>(<?php echo count($users); ?>)</small></h4>

<p>
    <a class="btn btn-primary btn-sm" href="<?php echo $this->url('Cms:Admin:Users@addAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add new user'); ?></a>
</p>

<form>
	<div class="table-responsive">
        <?= Grid::render($users, array(
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'name'
                ),

                array(
                    'column' => 'login'
                ),

                array(
                    'column' => 'email'
                )
            ),

            'actions' => array(
                'edit' => function($user){
                    return Icon::edit(
                        $this->url('Cms:Admin:Users@editAction', $user->getId()),
                        $this->translate('Edit this user')
                    );
                },

                'remove' => function($user){
                    return Icon::remove(
                        $this->url('Cms:Admin:Users@deleteAction', $user->getId()),
                        $this->translate('Remove this user')
                    );
                }
            )

        ), $this->translator); ?>

		<?php if (empty($users)): ?>
		<div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No users'); ?></h2>
		</div>
		<?php endif; ?>
	</div>
</form>
