<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <div class="btn-group mr-2">
        <a class="btn btn-primary btn-sm" href="<?= $this->url('Cms:Admin:Users@addAction'); ?>"><i class="fas fa-user-plus"></i> <?php $this->show('Add new user'); ?></a>
    </div>

    <?php if (count($users) > 1): ?>
    <div class="btn-group mr-2">
        <a data-button="delete" data-message="<?php $this->show('All listed users will be removed and no longer able to enter the system except you. Continue?'); ?>" class="btn btn-primary btn-sm" href="<?= $this->url('Cms:Admin:Users@wipeAction'); ?>"><i class="fas fa-user-shield"></i> <?php $this->show('Remove all, but current'); ?></a>
    </div>
    <?php endif; ?>
</div>

<div class="card">
    <h4 class="mb-4"><i class="fas fa-users-cog"></i> <?php $this->show('Users'); ?> <small class="text-muted">(<?= count($users); ?>)</small></h4>

    <form>
        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($users, [
                'tableClass' => 'table table-hover table-bordered table-striped',
                'columns' => [
                    [
                        'column' => 'id',
                        'label' => '#',
                        'attributes' => [
                            'class' => 'text-center text-muted'
                        ]
                    ],

                    [
                        'column' => 'name'
                    ],

                    [
                        'column' => 'login'
                    ],

                    [
                        'column' => 'email'
                    ]
                ],

                'actions' => [
                    'edit' => function($user){
                        return Icon::edit(
                            $this->url('Cms:Admin:Users@editAction', $user->getId()),
                            $this->translate('Edit this user')
                        );
                    },

                    'remove' => function($user) use ($currentUserId) {
                        // Prevent removing oneself
                        if ($currentUserId == $user->getId()) {
                            return null;
                        }

                        return Icon::remove(
                            $this->url('Cms:Admin:Users@deleteAction', $user->getId()),
                            $this->translate('Remove this user')
                        );
                    }
                ]
            ])); ?>
        </div>
    </form>

</div>