<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>
<div class="btn-toolbar mb-3 d-flex justify-content-between">
    <div class="btn-group">
        <a class="btn btn-primary btn-sm" href="<?= $this->url('Cms:Admin:Users@addAction'); ?>">
            <i class="bi bi-person-plus"></i> <?= $this->translate('Add new user'); ?>
        </a>
    </div>

    <?php if (count($users) > 1): ?>
    <div class="btn-group">
        <a data-button="delete" data-message="<?= $this->translate('All listed users will be removed and no longer able to enter the system except you. Continue?'); ?>" class="btn btn-outline-danger btn-sm" href="<?= $this->url('Cms:Admin:Users@wipeAction'); ?>">
            <i class="bi bi-shield-lock"></i> <?= $this->translate('Remove all, but current'); ?>
        </a>
    </div>
    <?php endif; ?>
</div>

<div class="card">
    <div class="card-header">
        <h4 class="card-title mb-0">
            <i class="bi bi-people"></i> <?= $this->translate('Users'); ?> 
            <small class="text-muted">(<?= count($users); ?>)</small>
        </h4>
    </div>

    <div class="table-responsive">
        <?= $this->widget(new GridViewWidget($users, [
            'tableClass' => 'table table-hover table-striped mb-0',
            'columns' => [
                [
                    'column' => 'id',
                    'label' => '#',
                    'attributes' => [
                        'class' => 'text-center text-muted'
                    ]
                ],
                [
                    'column' => 'name'
                ],
                [
                    'column' => 'login'
                ],
                [
                    'column' => 'email'
                ]
            ],
            'actions' => [
                function($user){
                    return Icon::edit(
                        $this->url('Cms:Admin:Users@editAction', $user->getId()),
                        $this->translate('Edit this user')
                    );
                },

                function($user) use ($currentUserId) {
                    // Prevent removing oneself
                    if ($currentUserId == $user->getId()) {
                        return null;
                    }

                    return Icon::remove(
                        $this->url('Cms:Admin:Users@deleteAction', $user->getId()),
                        $this->translate('Remove this user')
                    );
                }
            ]
        ])); ?>
    </div>
</div>