<?php

use Krystal\Form\Element;

?>

<form data-group="user">
	<div class="well clearfix">
		
        <?php echo Element::hidden('user[id]', $user->getId()); ?>
        <?php echo Element::hidden('user[password_hash]', $user->getPasswordHash()); ?>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Login'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('user[login]', $user->getLogin(), array('class' => 'form-control', 'placeholder' => $this->translate('Enter desired login'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Password'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<?php echo Element::password('user[password]', null, array('class' => 'form-control', 'placeholder' => $this->translate('Enter new password'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Password confirmation'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::password('user[password_confirm]', null, array('class' => 'form-control', 'placeholder' => $this->translate('Enter new password again'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Email'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('user[email]', $user->getEmail(), array('class' => 'form-control', 'placeholder' => $this->translate('Email to be used for notifications and password recovery'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('user[name]', $user->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('First Name of the user to be added'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		<?php if ($role->isDeveloper()): ?>
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Role'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::select('user[role]', $roles, $user->getRole(), array('class' => 'form-control')); ?>
			</div>
		</div>
		<?php else: ?>
		
        <?php echo Element::hidden('user[role]', 'user'); ?>
        
		<?php endif; ?>
	</div>
	
	<?php if (!$user->getId()): ?>
	<button data-button="add" data-back-url="<?php echo $this->url('Cms:Admin:Users@editAction', null); ?>" data-url="<?php echo $this->url('Cms:Admin:Users@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	
	<?php else: ?>
	<button data-button="save" data-url="<?php echo $this->url('Cms:Admin:Users@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	
	<?php endif; ?>
	
	<?php if ($role->isDeveloper()): ?>
	<button data-button="cancel" data-url="<?php echo $this->url('Cms:Admin:Users@gridAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
	
	<?php else: ?>
	<button data-button="dashboard" data-url="<?php echo $this->url('Cms:Admin:Dashboard@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
	
	<?php endif; ?>
	
</form>
