
<?php if (isset($paginator) && $paginator->hasPages()): ?>
<nav class="center-block text-center">
  <ul class="pagination pagination-lg">
	<?php if ($paginator->hasPreviousPage()): ?>
	<?php endif; ?>
	<li>
	  <a href="#" aria-label="Previous">
		<span aria-hidden="true">&laquo;</span>
	  </a>
	</li>
	
	<?php foreach ($paginator->getPageNumbers() as $pageNumber): ?>
	<li <?php $this->getHelper()->addClassOnDemand($paginator->isCurrentPage($pageNumber), 'active')?>><a href="<?php echo $paginator->getUrl($pageNumber); ?>"><?php echo $pageNumber; ?></a></li>
	<?php endforeach; ?>
	
	<li>
	  <a href="#" aria-label="Next">
		<span aria-hidden="true">&raquo;</span>
	  </a>
	</li>
  </ul>
</nav>
<?php endif; ?>
