<?php

use Krystal\Form\Widget\CheckBoxWidget;
use Krystal\Form\HtmlHelper;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu pull-bottom">
		 <li><a href="<?php echo $this->url('Photogallery:Admin:Photo:Add@indexAction'); ?>"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Add a photo'); ?></a></li>
		 <li><a href="<?php echo $this->url('Photogallery:Admin:Album:Add@indexAction'); ?>"><i class="glyphicon glyphicon-folder-open"></i> <?php $this->show('Add album'); ?></a></li>
		 <li><a href="<?php echo $this->url('Photogallery:Admin:Config@indexAction'); ?>"><i class="glyphicon glyphicon-tasks"></i> <?php $this->show('Configuration'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 
		 <?php if (!empty($photos)): ?>
		 <li><a href="#" data-button="save-changes"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes');?></a></li>
		 <li><a href="#" data-button="remove-selected"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 
		 <?php else: ?>
		 
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes');?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<?php $this->loadBlock('items-per-page', array('caption' => 'Photogallery')); ?>

<form>
	<div class="table-responsive">
		<table class="table table-striped table-hover table-bordered table-condensed">
			<thead>
				<tr>
					<th class="text-center"><input type="checkbox" /></th>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Image'); ?></th>
					<th class="text-center"><?php $this->show('Name'); ?></th>
					<th class="text-center"><?php $this->show('Album'); ?></th>
					<th class="text-center"><?php $this->show('Published'); ?></th>
					<th class="text-center"><?php $this->show('Order'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>
			
			<?php if (!empty($photos)): ?>
			<tbody>
				
				<?php foreach ($photos as $photo): ?>
				<tr>
					<td class="text-center">
						<input type="checkbox" name="toDelete[<?php echo $photo->getId(); ?>]" />
					</td>
					<td class="text-center text-muted"><?php echo $photo->getId(); ?></td>
					<td>
						<img class="img-responsive center-block" src="<?php echo $photo->getImageBag()->getUrl('400x200'); ?>" data-zoom-image="<?php echo $photo->getImageBag()->getUrl('original'); ?>" />
					</td>
					<td class="text-center"><?php echo $photo->getName(); ?></td>
					<td class="text-center"><?php echo $photo->getAlbumName(); ?></td>
					<td class="text-center">
						<?php echo CheckBoxWidget::render(array('name' => sprintf('published[%s]', $photo->getId())), $photo->getPublished()); ?>
					</td>
					<td class="text-center col-md-1">
						<input type="number" class="form-control" min="0" name="order[<?php echo $photo->getId(); ?>]" value="<?php echo $photo->getOrder(); ?>" />
					</td>
					<td class="text-center col-md-1">
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit the photo'); ?>" data-button="edit" href="<?php echo $this->url('Photogallery:Admin:Photo:Edit@indexAction', $photo->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
						<a data-toggle="tooltip" data-button="delete" data-id="<?php echo $photo->getId(); ?>" data-category="photo" data-placement="left" data-original-title="<?php $this->show('Remove the photo'); ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				<?php endforeach; ?>
				
			</tbody>
			<?php endif; ?>
		</table>
		
		<?php if (empty($photos)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No photos'); ?></h2>
		</div>
		<?php endif; ?>
		
	</div>
</form>


<?php $this->loadBlock('paginator'); ?>


<div class="table-responsive clearfix">
	<h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Albums'); ?> (<?php echo count($albums); ?>)</h4>
	
	<table class="table table-striped table-hover table-bordered table-condensed">
		<thead>
			<tr>
				<th class="text-center"><?php $this->show('#'); ?></th>
				<th class="text-center"><?php $this->show('Name'); ?></th>
				<th class="text-center"><?php $this->show('Amount of photos'); ?></th>
				<th class="text-center"><?php $this->show('Actions'); ?></th>
			</tr>
		</thead>
		
		<?php if (!empty($albums)): ?>
		<tbody>
			
			<?php foreach ($albums as $id => $title): ?>
			<tr>
				<td class="text-center text-muted"><?php echo $id; ?></td>
				
				<td class="text-center">
					<a href="<?php echo $this->url('Photogallery:Admin:Browser@albumAction', $id); ?>">
						<?php HtmlHelper::wrapOnDemand(isset($albumId) && $albumId == $id, 'strong', $title); ?>
					</a>
				</td>
				
				<td class="text-center"><?php echo $taskManager->getCountByAlbumId($id); ?></td>
				<td class="text-center">
					<a data-button="view" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('View this album on site'); ?>" target="_blank" href="<?php echo $taskManager->fetchByAlbumId($id)->getUrl(); ?>"><i class="glyphicon glyphicon-search"></i></a>
					<a data-button="edit" href="<?php echo $this->url('Photogallery:Admin:Album:Edit@indexAction', $id); ?>" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit the album'); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
					<a data-button="delete" data-id="<?php echo $id; ?>" data-category="category" href="#" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove the album'); ?>"><i class="glyphicon glyphicon-remove"></i></a>
				</td>
			</tr>
			<?php endforeach; ?>
			
		</tbody>
		<?php endif; ?>
	</table>

	<?php if (empty($albums)): ?>
	<div class="center-block">
		<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No albums'); ?></h2>
	</div>
	<?php endif; ?>
	
</div>
