<?php

use Krystal\Form\Widget\CheckBoxWidget;
use Krystal\Form\Widget\DropdownWidget;

?>

<?php if (count($albums) != 0): ?>

<form>

	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#image" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Image'); ?></a></li>
		<li role="presentation"><a href="#options" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Options'); ?></a></li>
	</ul>
	
	
	<div class="tab-content">
		
		<div role="tabpanel" class="tab-pane fade in active" id="image" role="tabpanel">
			<div class="well clearfix">
				
				<input type="hidden" name="photo[id]" value="<?php echo $photo->getId(); ?>" />
				<input type="hidden" name="photo[photo]" value="<?php echo $photo->getPhoto(); ?>" />
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
							<input type="text" name="photo[name]" class="form-control" value="<?php echo $photo->getName(); ?>" placeholder="<?php $this->show('Name of the photo to be added'); ?>" />
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Album'); ?></label>
					<div class="col-lg-10">
						<?php echo DropdownWidget::render(array('name' => 'photo[album_id]', 'class' => 'form-control'), $albums, $photo->getAlbumId(), false); ?>
					</div>
				</div>
				
				<div class="form-group clearfix">
					
					<br />
					
					<label class="col-lg-2 control-label"><?php $this->show('Photo file'); ?></label>
					<div class="col-lg-10">
						
						<?php if (!$photo->getPhoto()): ?>
						<img data-image="preview" />
						
						<?php else: ?>
						<img class="img-responsive" src="<?php echo $photo->getImageBag()->getUrl('400x200'); ?>" data-zoom-image="<?php echo $photo->getImageBag()->getUrl('original'); ?>" />
						<?php endif; ?>
						
						<br />
						<br />
						
						<input type="file" name="file" accept="image/x-png, image/gif, image/jpeg" />
					</div>
					
					<br />
				</div>
				
			</div>
		</div>
		
		
		<div role="tabpanel" class="tab-pane fade" id="options" role="tabpanel">
			<div class="well">
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
					<div class="col-lg-10">
						<?php echo CheckBoxWidget::render(array('name' => 'photo[published]', 'class' => 'form-control'), $photo->getPublished()); ?>
					</div>
				</div>
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
							<input type="number" name="photo[order]" class="form-control" value="<?php echo $photo->getOrder(); ?>" placeholder="<?php $this->show('Order of this photo in selected album'); ?>" />
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
							<textarea name="photo[description]" class="form-control" placeholder="<?php $this->show('Description. Can be used as a hint when mouse overs'); ?>"><?php echo $photo->getDescription(); ?></textarea>
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
			</div>
		</div>
		
	</div>
	
	<?php if (!$photo->getId()): ?>

	<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-upload" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Upload new'); ?></button>

	<?php else: ?>

	<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-upload" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Upload new'); ?></button>

	<?php endif; ?>

	<button data-button="cancel" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>

</form>

<?php else: ?>

<div class="well">
	<blockquote>
		<p class="text-muted"><?php $this->show('You can not upload photos before you create a photo album!'); ?></p>
		<small><a href="<?php echo $this->url('Photogallery:Admin:Album:Add@indexAction'); ?>"><?php $this->show('Click here to create a new one'); ?></a></small>
	</blockquote>
</div>

<?php endif; ?>
