<form>
	<div class="well clearfix">
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Per page count'); ?></label>
			<div class="col-lg-10">
				<div class="input-group date">
					<input type="number" min="1" name="config[per_page_count]" class="form-control" value="<?php echo $config->getPerPageCount(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
				<span class="help-block"><?php $this->show('How many posts you want to be displayed per page in each category?'); ?></span>
			</div>
		</div>
	</div>

	<button class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button class="btn btn-default"><i class="glyphicon glyphicon-open"></i> <?php $this->show('Cancel'); ?></button>

</form>
