<?php if (!empty($categories)): ?>

<form>
	<div class="well clearfix">
		
		<input type="hidden" name="id" value="<?php echo $post->getId(); ?>" />
		<input type="hidden" name="web_page_id" value="<?php echo $post->getWebPageId(); ?>" />
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="title" class="form-control" placeholder="<?php $this->show("Post's title"); ?>" value="<?php echo $post->getTitle(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Category'); ?></label>
			<div class="col-lg-10">
				
				<select name="category_id" class="form-control">
					
					<?php foreach ($categories as $category): ?>
					<option value="<?php echo $category->getId(); ?>" <?php $this->getHelper()->selectOnDemand($post->getCategoryId() == $category->getId()); ?>><?php echo $category->getTitle(); ?></option>
					<?php endforeach; ?>
					
				</select>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Introduction'); ?></label>
			<div class="col-lg-10">
				<textarea name="introduction" class="form-control"><?php echo $post->getIntroduction(); ?></textarea>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Full text'); ?></label>
			<div class="col-lg-10">
				<textarea name="full" class="form-control"><?php echo $post->getFull(); ?></textarea>
			</div>
		</div>
		
		
		
		<div class="options">
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php echo $this->translate('Date'); ?></label>
				<div class="col-lg-10">
					<div class="input-group date">
						<input type="text" name="date" class="form-control" placeholder="<?php $this->show('Date of the post'); ?>" value="<?php echo $post->getDate(); ?>" />
						<span class="input-group-addon"><i class="glyphicon glyphicon-calendar" data-toggle="tooltip" title="<?php $this->show('Change the date'); ?>"></i></span>
					</div>
				</div>
			</div>
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Enable comments'); ?></label>
				<div class="col-lg-10">
					<input type="hidden" name="comments" value="0" />
					<input type="checkbox" name="comments" value="1" class="form-control" <?php $this->getHelper()->checkOnDemand($post->getComments()); ?>/>
				</div>
			</div>
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php echo $this->translate('Published'); ?></label>
				<div class="col-lg-10">
					<input type="hidden" name="published" value="0" />
					<input type="checkbox" name="published" value="1" class="form-control" <?php $this->getHelper()->checkOnDemand($post->getPublished()); ?>/>
				</div>
			</div>
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php echo $this->translate('Enable SEO'); ?></label>
				<div class="col-lg-10">
					<input type="hidden" name="seo" value="0" />
					<input type="checkbox" name="seo" value="1" class="form-control" <?php $this->getHelper()->checkOnDemand($post->getSeo()); ?> />
				</div>
			</div>
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
				<div class="col-lg-10">
					<div class="input-group">
						<input type="text" name="slug" class="form-control" placeholder="<?php $this->show('URL slug for this post. By default is taken from a title'); ?>" value="<?php echo $post->getSlug(); ?>" />
						<span class="input-group-addon">
							<a href="#" data-button="slug"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh'); ?>"></i></a>
						</span>
					</div>
				</div>
			</div>
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
				<div class="col-lg-10">
					<div class="input-group">
						<input type="text" name="keywords" class="form-control" placeholder="<?php $this->show('Keywords used for search engines'); ?>" value="<?php echo $post->getKeywords(); ?>" />
						<span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
					</div>
				</div>
			</div>
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
				<div class="col-lg-10">
					<textarea name="metaDescription" class="form-control" placeholder="<?php $this->show('Meta description for search engines'); ?>"><?php echo $post->getMetaDescription(); ?></textarea>
				</div>
			</div>
			
		</div>
	</div>
	
	
	<?php if (isset($editing)): ?>
	<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Save & Create new'); ?></button>
	
	<?php else: ?>
	<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-open"></span> <?php $this->show('Add & Create new'); ?></button>
	
	<?php endif; ?>
	
	<button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
	<button data-button="cancel" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
	
</form>

<?php else: ?>

<div class="well">
 <div class="center-block">
  <h2 class="text-muted text-center"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Before you add a post, you need to create at least one category'); ?></h2>
 </div>
</div>

<?php endif; ?>
