<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> 
		<span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('News:Admin:Post:Add@indexAction'); ?>"><i class="glyphicon glyphicon-plus"></i> <?php $this->show('Add new post'); ?></a></li>
		 <li><a href="<?php echo $this->url('News:Admin:Category:Add@indexAction'); ?>"><i class="glyphicon glyphicon-plus"></i> <?php $this->show('Add new category'); ?></a></li>
		 <li><a href="<?php echo $this->url('News:Admin:Config@indexAction'); ?>"><i class="glyphicon glyphicon-th-large"></i> <?php $this->show('Configuration'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 
		 <?php if(!empty($posts)): ?>
		 <li><a href="#" data-button="save-changes"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-button="remove-selected"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<?php $this->loadBlock('items-per-page', array('caption' => 'News')); ?>

<form>
	<div class="table-responsive">
		<table class="table table-hover table-bordered table-striped table-condensed">
			<thead>
				<tr>
					<th class="text-center"><input type="checkbox" /></th>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Title'); ?></th>
					<th class="text-center"><?php $this->show('Date'); ?></th>
					<th class="text-center"><?php $this->show('Category'); ?></th>
					<th class="text-center"><?php $this->show('Published'); ?></th>
					<th class="text-center"><?php $this->show('SEO'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>
			
			<?php if (!empty($posts)): ?>
			<tbody>
				
				<?php foreach ($posts as $post): ?>
				<tr>
					<td class="text-center">
						<input type="checkbox" name="toDelete[<?php echo $post->getId(); ?>]" />
					</td>
					<td class="text-center text-muted"><?php echo $post->getId(); ?></td>
					<td class="text-center"><?php echo $post->getTitle(); ?></td>
					<td class="text-center"><?php echo $post->getTimeBag()->getPanelFormat(); ?></td>
					<td class="text-center"><?php echo $post->getCategoryName(); ?></td>
					<td class="text-center">
						<input type="hidden" name="published[<?php echo $post->getId(); ?>]" value="0" />
						<input type="checkbox" name="published[<?php echo $post->getId(); ?>]" value="1" <?php $this->getHelper()->checkOnDemand($post->getPublished()); ?>/>
					</td>
					<td class="text-center">
						<input type="hidden" name="seo[<?php echo $post->getId(); ?>]" value="0" />
						<input type="checkbox" name="seo[<?php echo $post->getId(); ?>]" value="1" <?php $this->getHelper()->checkOnDemand($post->getSeo()); ?>/>
					</td>
					<td class="text-center">
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('View this post'); ?>" data-button="view" target="_blank" href="<?php echo $post->getUrl(); ?>"><i class="glyphicon glyphicon-search"></i></a>
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this post'); ?>" data-button="edit" href="<?php echo $this->url('News:Admin:Post:Edit@indexAction', $post->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this post'); ?>" data-button="delete" href="#" data-id="<?php echo $post->getId(); ?>" data-category="post"><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				
				<?php endforeach; ?>
				
			</tbody>
			<?php endif; ?>
		</table>
		
		<?php if (empty($posts)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No news'); ?></h2>
		</div>
		<?php endif; ?>
		
	</div>
</form>

<?php $this->loadBlock('paginator'); ?>

<div class="table-responsive clearfix">
	<h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Categories'); ?> (<?php echo count($categories); ?>)</h4>
	
	<div class="table-responsive">
		<table class="table table-hover table-bordered table-striped table-condensed">
			<thead>
				<tr>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Title'); ?></th>
					<th class="text-center"><?php $this->show('Amount of news'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>
			
			<?php if (!empty($categories)): ?>
			<tbody>
				
				<?php foreach ($categories as $category): ?>
				<tr>
					<td class="text-center text-muted"><?php echo $category->getId(); ?></td>
					<td class="text-center">
						<a href="<?php echo $this->url('News:Admin:Browser@categoryAction', $category->getId()); ?>">
						<?php if (isset($categoryId) && $categoryId == $category->getId()): ?>
						<strong><?php echo $category->getTitle(); ?></strong>
						
						<?php else: ?>
						<?php echo $category->getTitle(); ?>
						
						<?php endif; ?>
						</a>
					</td>
					
					<td class="text-center"><?php echo $taskManager->getPostCountByCategoryId($category->getId()); ?></td>
					<td class="text-center">
						<a data-button="view" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('View this category on site'); ?>" target="_blank" href="<?php echo $category->getUrl();?>"><i class="glyphicon glyphicon-search"></i></a>
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this category'); ?>" data-button="edit" href="<?php echo $this->url('News:Admin:Category:Edit@indexAction', $category->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this category'); ?>" data-button="delete" data-id="<?php echo $category->getId(); ?>" data-category="category" href="#"><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				
				<?php endforeach; ?>
				
			</tbody>
			<?php endif; ?>
			
		</table>
		
		<?php if (empty($categories)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
		</div>
		<?php endif; ?>
		
	</div>
</div>