<?php

use Krystal\Form\HtmlHelper;
use Krystal\Form\Widget\CheckBoxWidget;
 
?>

<form>
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#page" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Category'); ?></a></li>
		<li role="presentation"><a href="#menu" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-list"></i> <?php $this->show('Item in menu'); ?></a></li>
	</ul>
	
	<div class="tab-content">
		<div class="tab-pane fade in active" id="page" role="tabpanel">
			<div class="well clearfix">
				
				<input type="hidden" name="category[id]" value="<?php echo $category->getId(); ?>" />
				<input type="hidden" name="category[web_page_id]" value="<?php echo $category->getWebPageId(); ?>" />
				<input type="hidden" name="web_page_id" value="<?php echo $category->getWebPageId(); ?>" />
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
							<input type="text" name="category[title]" class="form-control" value="<?php echo $category->getTitle(); ?>" data-input="title" placeholder="<?php $this->show('Category title'); ?>" />
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
					<div class="col-lg-10">
						<textarea name="category[description]"><?php echo $category->getDescription(); ?></textarea>
					</div>
				</div>
				
				<div class="options">
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
						<div class="col-lg-10">
							<?php echo CheckBoxWidget::render(array('name' => 'category[seo]', 'class' => 'form-control'), $category->getSeo()); ?>
						</div>
					</div>
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
						<div class="col-lg-10">
							<div class="input-group">
								<input type="text" name="category[slug]" class="form-control" value="<?php echo $category->getSlug(); ?>" data-input="slug" placeholder="<?php $this->show('URL slug for this post. By default is taken from a title'); ?>" />
								<span class="input-group-addon">
									<a href="#" data-button="slug"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i></a>
								</span>
							</div>
						</div>
					</div>
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
						<div class="col-lg-10">
							<div class="input-group">
								<input type="text" name="category[keywords]" class="form-control" value="<?php echo $category->getKeywords(); ?>" placeholder="<?php $this->show('Keywords used for search engines'); ?>" />
								<span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
							</div>
						</div>
					</div>
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
						<div class="col-lg-10">				
							<textarea name="category[meta_description]" class="form-control" placeholder="<?php $this->show('Meta description for search engines'); ?>"><?php echo $category->getMetaDescription(); ?></textarea>
						</div>
					</div>
					
				</div>
			</div>
			
			<?php if ($category->getId()):?>
			<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
			
			<?php else: ?>
			<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
			
			<?php endif; ?>
			
			<button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
			<button data-button="cancel" class="btn btn-default"><i class="glyphicon glyphicon-open"></i> <?php $this->show('Cancel'); ?></button>
			
		</div>
		
		<div class="tab-pane fade" id="menu" role="tabpanel">
			<?php $this->loadBlock('menu-widget'); ?>
		</div>
	</div>
</form>
