<?php

use Krystal\Form\Widget\CheckBoxWidget;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('MailForm:Admin:Add@indexAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new form'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>

		 <?php if (!empty($forms)): ?>
		 
		 <li><a href="#" data-button="save-changes"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-button="remove-selected"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 
		 <?php else: ?>
		 
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<h4 class="inline"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Mail forms'); ?></h4>

<form>
	<div class="table-responsive">
		<table class="table table-hover table-bordered table-striped">
			<thead>
				<tr>
					<th class="text-center">
						<?php if (!empty($forms)): ?>
						<input type="checkbox" />
						<?php endif; ?>
					</th>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Title'); ?></th>
					<th class="text-center"><?php $this->show('SEO'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>
			
			<?php if (!empty($forms)): ?>
			<tbody>
				
				<?php foreach ($forms as $form): ?>
				<tr>
					<td class="text-center">
						<input type="checkbox" name="toDelete[<?php echo $form->getId(); ?>]" />
					</td>
					<td class="text-center text-muted"><?php echo $form->getId(); ?></td>
					<td class="text-center"><?php echo $form->getTitle(); ?></td>
					<td class="text-center">
						<?php echo CheckBoxWidget::render(array('name' => sprintf('seo[%s]', $form->getId())), $form->getSeo()); ?>
					</td>
					<td class="text-center">
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('View this page on site'); ?>" data-button="view" target="_blank" href="<?php echo $form->getUrl(); ?>"><i class="glyphicon glyphicon-search"></i></a>
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this page'); ?>" data-button="edit" href="<?php echo $this->url('MailForm:Admin:Edit@indexAction', $form->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this page'); ?>" data-button="delete" data-category="main" data-id="<?php echo $form->getId(); ?>" href="#" ><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				
				<?php endforeach; ?>
			</tbody>
			<?php endif; ?>
		</table>
		
		<?php if (empty($forms)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No forms'); ?></h2>
		</div>
		<?php endif; ?>
		
	</div>
</form>

<?php $this->loadBlock('paginator'); ?>
