<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	
	<meta name="keywords" content="<?php echo $page->getKeywords(); ?>" />
	<meta name="description" content="<?php echo $page->getMetaDescription(); ?>" />
	<meta name="author" content="D.D.Yang" />
	
	<title><?php echo $page->getTitle(); ?></title>
	
	<?php foreach ($this->getPluginBag()->getStylesheets() as $stl): ?>
    <link href="<?php echo $stl; ?>" rel="stylesheet" />
	<?php endforeach; ?>
	
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body>
    <div class="navbar-wrapper">
      <div class="container">
		<nav class="navbar navbar-default navbar-fixed-top">
		  <div class="container">
			<div class="navbar-header">
			  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  </button>
			  <a class="navbar-brand" href="/">Bono CMS</a>
			</div>
			<div id="navbar" class="collapse navbar-collapse">
			  <?php echo $menu->renderByClass('brand-top', $page->getWebPageId()); ?>
			  
			  <form action="<?php echo $search->getUrl(); ?>" class="navbar-form navbar-right">
				<div class="form-group">
				  <input type="text" name="<?php echo $search->getElementName(); ?>" class="form-control" placeholder="<?php $this->show('Looking for something?'); ?>" />
				</div>
				<button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i> <?php $this->show('Search'); ?></button>
			  </form>
			</div>
		  </div>
		</nav>
      </div>
    </div>
	
	<!--Slider-->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
	  <ol class="carousel-indicators">
       <?php foreach($slider->getAll('brand') as $index => $slide): ?>
       <li data-target="#myCarousel" data-slide-to="<?php echo $index; ?>"  <?php $this->getHelper()->addClassOnDemand($index == 0, 'active'); ?>></li>
       <?php endforeach; ?>
	  </ol>
      
	  <div class="carousel-inner" role="listbox">
		<?php foreach ($slider->getAll('brand') as $index => $slide): ?>
		<div class="item <?php $this->getHelper()->addOnDemand($index == 0, 'active'); ?>">
		  <img src="<?php echo $slide->getImageBag()->getUrl('800x500'); ?>" alt="<?php echo $slide->getName(); ?>" />
		  <div class="carousel-caption">
			<h1><?php echo $slide->getName(); ?></h1>
			<p><?php echo $slide->getDescription(); ?></p>
		  </div>
		</div>
		<?php endforeach; ?>
      </div>
	  
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
	</div>
	<!--/Slider-->
	
	
    <div class="container marketing">
	  
	  <?php echo $fragment; ?>
	  
      <footer>
        <p>&copy; 2015 D.D. Yang, Inc. &middot; <a href="#">License</a> &middot; <a href="#">About</a></p>
      </footer>
    </div>
	
	<?php foreach ($this->getPluginBag()->getScripts() as $script): ?>
	<script src="<?php echo $script; ?>"></script>
	<?php endforeach; ?>
	
  </body>
</html>
