<div class="page-header">
	<h2>Modules</h2>
	<article>
		Nam condimentum, nunc in tristique auctor, tellus dolor aliquet lectus, eget bibendum metus enim eget urna. 
		In sagittis est id tellus fringilla malesuada. 
		Proin sit amet porttitor ipsum. Proin luctus sed libero eget mattis. 
		Mauris et arcu euismod, feugiat arcu vitae, varius orci. Donec vitae est lobortis, tincidunt leo quis, gravida neque. 
		Fusce ut erat ac turpis sollicitudin pellentesque. Vivamus commodo eleifend urna. Aliquam sit amet venenatis justo, in molestie libero. Fusce pellentesque eget nunc sed pulvinar. 
	</article>
</div>

<div class="row">
	
	<div class="col-sm-6 col-md-4">
		<div class="thumbnail">
		  <img src="<?php echo $this->asset('img/m-ph.jpg'); ?>" alt="...">
		  <div class="caption">
			<h2>Photogallery</h2>
			<p>This module allows you to manage photo albums on your site. Albums can be nested</p>
			<div class="center-block">
				<h3 class="text-center"><a class="btn btn-lg btn-primary" href="#"><i class="glyphicon glyphicon-share-alt"></i> Download</a></h3>
			</div>
		  </div>
		</div>
	</div>
</div>
