<!DOCTYPE html>
<html>
 <head>
   <meta charset="utf-8" />
   <meta http-equiv="X-UA-Compatible" content="IE=edge" />
   <meta name="viewport" content="width=device-width, initial-scale=1" />
   <meta name="description" content="<?php echo $page->getMetaDescription(); ?>" />
   <meta name="keywords" content="<?php echo $page->getKeywords(); ?>" />
   
   <title><?php echo $page->getTitle(); ?></title>
	
   <?php foreach ($this->getPluginBag()->getStylesheets() as $style): ?>
   <link href="<?php echo $style; ?>" rel="stylesheet" />
   <?php endforeach; ?>
	
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
     <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
     <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

  <body>
    <div class="blog-masthead">
		<nav class="navbar navbar-default navbar-fixed-top">
		  <div class="container-fluid">
			<div class="navbar-header">
			  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  </button>
			  <a class="navbar-brand" href="/"><?php echo $block->render('name'); ?></a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			  <?php echo $menu->renderByClass('top', $page->getWebPageId()); ?>
			  <form class="navbar-form navbar-right" role="search" action="<?php echo $search->getUrl(); ?>">
				<div class="form-group">
				  <input type="text" name="<?php echo $search->getElementName(); ?>" class="form-control" placeholder="<?php $this->show('Looking for something?'); ?>" />
				</div>
				<button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i> <?php $this->show('Search'); ?></button>
			  </form>
			</div>
		  </div>
		</nav>
    </div>

    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title"><?php echo $block->render('header'); ?></h1>
        <p class="lead blog-description"><i class="glyphicon glyphicon-th-large"></i> <?php echo $block->render('slogan'); ?></p>
      </div>
	  
	  <?php if ($this->getBreadcrumbBag()->has()): ?>
	  <ul class="breadcrumb">
		<?php foreach ($this->getBreadcrumbBag()->getBreadcrumbs() as $breadcrumb): ?>
		<?php if ($breadcrumb->isActive()): ?>
		<li class="active"><?php echo $breadcrumb->getName(); ?></li>
		<?php else: ?>
		<li><a href="<?php echo $breadcrumb->getLink(); ?>"><?php echo $breadcrumb->getName(); ?></a></li>
		<?php endif; ?>
		<?php endforeach; ?>
	  </ul>
	  <?php endif; ?>
	  
      <div class="row">
	   <div class="col-sm-8 blog-main">
	   <?php echo $fragment; ?>
	   </div>

		<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
		  
		  <div class="sidebar-module sidebar-module-inset">
			<h4><?php $this->show('About this blog'); ?></h4>
			<?php echo $aboutBox; ?>
		  </div>
		  
		  <div class="sidebar-module">
			<h4><?php $this->show('Categories'); ?></h4>
			
			<ol class="list-unstyled">
			  <?php foreach($blog->getAllCategoriesWithCount() as $category): ?>
			  <li><a href="<?php echo $category->getUrl(); ?>"><?php echo $category->getTitle(); ?></a></li>
			  <?php endforeach; ?>
			</ol>
		  </div>
		  
		  <div class="sidebar-module">
			<h4><?php echo $menu->getCategoryNameByClass('partners'); ?></h4>
			<ol class="list-unstyled">
			  <li><a href="#">GitHub</a></li>
			  <li><a href="#">Twitter</a></li>
			  <li><a href="#">Facebook</a></li>
			</ol>
		  </div>
		</div><!-- /.blog-sidebar -->	   
	  </div>

    <footer class="blog-footer">
      <p>Powered by <a href="#">Bono CMS</a> Copyright (c) 2014 </p>
    </footer>
	
	</div>
	<?php foreach ($this->getPluginBag()->getScripts() as $script): ?>
	<script src="<?php echo $script; ?>"></script>
	<?php endforeach; ?>
	
  </body>
</html>

	   