<article><?php echo $page->getDescription(); ?></article>

<form class="form-horizontal" method="POST">
  <fieldset>
	<legend><?php echo $page->getTitle(); ?></legend>
	
	<div class="form-group">
	  <label for="inputName" class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
	  <div class="col-lg-10">
		<input type="text" class="form-control" name="name" id="inputName" placeholder="<?php $this->show('Your name'); ?>" />
	  </div>
	</div>
	
	<div class="form-group">
	  <label for="inputEmail" class="col-lg-2 control-label"><?php $this->show('Email'); ?></label>
	  <div class="col-lg-10">
		<input type="text" class="form-control" name="email" id="inputEmail" placeholder="<?php $this->show('Type your email if you want us to reply'); ?>" />
	  </div>
	</div>
	
	<div class="form-group">
	  <label for="textArea" class="col-lg-2 control-label"><?php $this->show('Message'); ?></label>
	  <div class="col-lg-10">
		<textarea class="form-control" rows="3" id="textArea" name="message" placeholder="<?php $this->show('Type your message'); ?>"></textarea>
	  </div>
	</div>
	
	<div class="form-group">
		<label for="inputCaptcha" class="col-lg-3 control-label"></label>
		<div class="col-lg-9">
			<a href="#" title="Click to refresh" data-captcha="button-refresh"><img data-captcha="image" src="<?php echo $this->url('Site:Main@captchaAction', null); ?>" /></a>
		</div>
	</div>
	
	<div class="form-group">
		<label for="inputCaptcha" class="col-lg-2 control-label"></label>
		<div class="col-lg-10">
			<input type="text" class="form-control" name="captcha" placeholder="<?php $this->show('Enter what you see on image'); ?>" />
		</div>
	</div>
	
	<div class="form-group">
	  <div class="col-lg-10 col-lg-offset-2">
		<button type="reset" class="btn btn-default"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Cancel'); ?></button>
		<button type="submit" class="btn btn-primary" data-button="submit"><i class="glyphicon glyphicon-envelope"></i> <?php $this->show('Submit'); ?></button>
	  </div>
	</div>
	
  </fieldset>
</form>
