
  <div class="blog-post">
	<h2 class="blog-post-title">Your first post</h2>
	<p class="blog-post-meta">January 1, 2014</p>
	<p>This blog post shows a few different types of content that's supported and styled with Bootstrap. Basic typography, images, and code are all supported.</p>
  </div><!-- /.blog-post -->
  
  <hr />
  
  <div class="blog-post">
	<h2 class="blog-post-title">Sample blog post</h2>
	<p class="blog-post-meta">January 1, 2014</p>
	<p>This blog post shows a few different types of content that's supported and styled with Bootstrap. Basic typography, images, and code are all supported.</p>
	<p>Cras mattis consectetur purus sit amet fermentum. Sed posuere consectetur est at lobortis.</p>
  </div><!-- /.blog-post -->

  <?php $this->loadBlock('pagination'); ?>

  
