<?php defined('KRYSTAL') or die; ?>
<!DOCTYPE html>
<html lang="<?php echo $locale; ?>">
<head>
 <noscript>
  <meta http-equiv="refresh" content="0; url=http://browsehappy.com" />
 </noscript>
 <meta http-equiv="X-UA-Compatible" content="IE=edge" />
 <meta charset="UTF-8" />
 <meta name="csrf-token" content="<?php echo $csrfToken; ?>" />
 <title><?php echo $page->getTitle(); ?></title>
 
 <?php if ($page->getSeo()): ?>
 <meta name="description" content="<?php echo htmlentities($page->getMetaDescription()); ?>" />
 <meta name="keywords" content="<?php echo htmlentities($page->getKeywords()); ?>" />
 <?php else: ?>
 
 <meta name="robots" content="noindex, nofollow, noarchive" />
 <meta name="description" content="" />
 <meta name="keywords" content="" />
 <?php endif; ?>
 
 <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
 
 <link rel="alternate" href="<?php echo $currentUrl; ?>" hreflang="<?php echo $locale; ?>" />
 
 <?php foreach ($this->getPluginBag()->getStylesheets() as $stylesheet): ?>
 <link rel="stylesheet" href="<?php echo $stylesheet; ?>" media="all" />
 <?php endforeach; ?>
 
 <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
 <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
 <![endif]-->
 
 <base href="<?php echo $this->asset(null); ?>" />
</head>
<body>