<?php

use Krystal\Paginate\Paginator;
use Krystal\Security\Filter;

defined('KRYSTAL') or die;

$url = $page->getDefault() ? $baseUrl : $page->getUrl();

?>
<!DOCTYPE html>
<html lang="<?= $locale; ?>">
<head>
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
 <meta charset="UTF-8">
 <meta name="csrf-token" content="<?= $csrfToken; ?>">
 <title><?= $page->getTitle(); ?></title>
 
 <?php if ($page->isDefault() || $page->getSeo()): ?>
 <meta name="description" content="<?= Filter::escape($page->getMetaDescription()); ?>">
 <meta name="keywords" content="<?= Filter::escape($page->getKeywords()); ?>">

 <!-- OG tags -->
 <meta property="og:title" content="<?= $page->getTitle(); ?>">
 <meta property="og:url" content="<?= $url; ?>">
 <meta property="og:description" content="<?= Filter::escape($page->getMetaDescription()); ?>">
 <meta property="og:type" content="website">
 <meta property="og:locale" content="<?= $locale; ?>">

 <meta name="twitter:card" content="summary">
 <meta name="twitter:title" content="<?= $page->getTitle(); ?>">
 <meta name="twitter:description" content="<?= Filter::escape($page->getMetaDescription()); ?>">
 <meta name="twitter:url" content="<?= $url; ?>">
 
 <?php else: ?>
 <meta name="robots" content="noindex, nofollow, noarchive">
 <?php endif; ?>
 
 <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
 
 <?php if (count($languages) > 1): ?>
 <?php foreach ($languages as $language): ?>
 <link rel="alternate" href="<?= $baseUrl . $language->getSwitchUrl(); ?>" hreflang="<?= $language->getCode(); ?>">
 <?php endforeach; ?>
 <link rel="alternate" href="<?= $baseUrl; ?>/" hreflang="x-default">
 <?php endif; ?>

 <?php foreach ($this->getPluginBag()->getStylesheets() as $stylesheet): ?>
 <link rel="stylesheet" href="<?= $stylesheet; ?>" media="all">
 <?php endforeach; ?>
 
 <?php if (isset($paginator) && ($paginator instanceof Paginator)): ?>
 <?php if ($paginator->hasPreviousPage()): ?>
 <link rel="prev" href="<?= $baseUrl, $paginator->getPreviousPageUrl(); ?>">
 <?php endif; ?>
 <?php if ($paginator->hasNextPage()): ?>
 <link rel="next" href="<?= $baseUrl, $paginator->getNextPageUrl(); ?>">
 <?php endif; ?>
 <?php endif; ?>
 
 <link rel="canonical" href="<?= $currentUrl; ?>">

 <base href="<?= $this->asset(null); ?>" />
</head>
<body>