<?php defined('KRYSTAL') or die; ?>

<div class="modal fade" id="ajax-modal" tabindex="-1" aria-labelledby="ajaxModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <div class="modal-content border-0 shadow">
            <div class="modal-header border-0 pb-0">
                <h6 class="modal-title fw-bold text-muted text-uppercase small" id="ajaxModalLabel">
                    <?php $this->show('Please wait'); ?>
                </h6>

                <button type="button" class="btn-close small" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body py-4 d-flex justify-content-center align-items-center">
                <div class="spinner-border text-primary" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
            </div>
        </div>
    </div>
</div>