<?php defined('KRYSTAL') or die; ?>
<div class="modal fade" id="ajax-modal" tabindex="-1" role="dialog" aria-labelledby="mdLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="mdLabel"><?php $this->show('Please wait'); ?></h4>
      </div>
      <div class="modal-body">
        <img class="center-block" src="<?php echo $this->asset('/img/ajax.gif'); ?>" />
      </div>
    </div>
  </div>
</div>