<?php defined('KRYSTAL') or die; ?>

<?php if ($this->getBreadcrumbBag()->has()): ?>
<ul class="breadcrumb">
 <?php foreach ($this->getBreadcrumbBag()->getBreadcrumbs() as $breadcrumb): ?>
 <?php if ($breadcrumb->isActive()): ?>
 <li class="active"><?php echo $breadcrumb->getName(); ?></li>
 <?php else: ?>
 <li><a href="<?php echo $breadcrumb->getLink(); ?>"><?php echo $breadcrumb->getName(); ?></a></li>
 <?php endif; ?>
 <?php endforeach; ?>
</ul>

<?php endif; ?>