<?php

use Krystal\Form\Element;
use Krystal\Stdlib\ArrayUtils;

// Handle defaults
$length['field'] = isset($length['field']) ? $length['field'] : 10;
$length['label'] = isset($length['label']) ? $length['label'] : 2;

// CAPTCHA is enabled by default
if (!isset($captcha)) {
    $captcha = true;    
} else {
    $captcha = (bool) $captcha;
}

?>

<form class="form-horizontal" action="<?php echo $action; ?>">
  <fieldset>
    <?php if (isset($title)): ?>
    <legend><?php echo $title; ?></legend>
    <?php endif; ?>

    <?php foreach ($fields as $field): ?>
    <?php
        $field['attrs'] = isset($field['attrs']) ? $field['attrs'] : array();
        $field['attrs']['name'] = isset($field['attrs']['name']) ? $field['attrs']['name'] : null;
        $field['attrs']['value'] = isset($field['attrs']['value']) ? $field['attrs']['value'] : null;
        $field['attrs']['type'] = isset($field['attrs']['type']) ? $field['attrs']['type'] : null;

        $id = sprintf('input-%s', $field['attrs']['name']);
    ?>

    <div class="form-group">
        <label for="<?php echo $id; ?>" class="<?php printf('col-lg-%s control-label', $length['label']); ?>"><?php $this->show($field['label']); ?></label>
        <div class="<?php printf('col-lg-%s', $length['field']); ?>">
            <?php echo Element::dynamic($field['attrs']['type'], $field['attrs']['name'], $field['attrs']['value'], ArrayUtils::mergeWithout($field['attrs'], array('class' => 'form-control', 'id' => $id, 'placeholder' => $this->translate($field['attrs']['placeholder'])), array('name', 'value', 'type'))); ?>
        </div>
    </div>

    <?php endforeach; ?>

    <?php if ($captcha === true): ?>
    <div class="form-group">
     <label for="inputCaptcha" class="col-lg-3 control-label"></label>
     <div class="col-lg-9">
       <a href="#" title="<?php $this->show('Click to refresh'); ?>" data-captcha="button-refresh">
        <img data-captcha="image" src="<?php echo $this->url('Site:Main@captchaAction', null); ?>" />
       </a>
      </div>
    </div>

    <div class="form-group">
      <label for="inputCaptcha" class="col-lg-2 control-label"></label>
      <div class="col-lg-10">
        <input type="text" class="form-control" name="captcha" placeholder="<?php $this->show('Enter what you see on image'); ?>" />
      </div>
    </div>
    <?php endif; ?>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="reset" class="btn btn-default"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Cancel'); ?></button>
        <button type="submit" class="btn btn-primary" data-button="submit"><i class="glyphicon glyphicon-envelope"></i> <?php $this->show('Submit'); ?></button>
      </div>
    </div>
  </fieldset>
</form>
