<?php defined('KRYSTAL') or die; ?>
<?php if (isset($paginator) && $paginator->hasPages()): ?>
<nav class="center-block text-center">
  <ul class="pagination pagination-lg">
	<?php if ($paginator->hasPreviousPage()): ?>
	<li>
	  <a href="<?php echo $paginator->getPreviousPageUrl(); ?>" aria-label="Previous">
		<span aria-hidden="true">&laquo;</span>
	  </a>
	</li>
	<?php endif; ?>

	<?php foreach ($paginator->getPageNumbers() as $page): ?>
	<?php if (is_numeric($page)): ?>
	<?php if ($paginator->isCurrentPage($page)): ?>
	
	<li class="active"><a href="<?php echo $paginator->getUrl($page); ?>"><?php echo $page; ?></a></li>
	<?php else: ?>
	
	<li><a href="<?php echo $paginator->getUrl($page); ?>"><?php echo $page; ?></a></li>
	<?php endif; ?>
	
	<?php else: ?>
	<li><a href="#"><?php echo $page; ?></a></li>
	<?php endif; ?>
	<?php endforeach; ?>
	
	<?php if ($paginator->hasNextPage()): ?>
	<li>
	  <a href="<?php echo $paginator->getNextPageUrl(); ?>" aria-label="Next">
		<span aria-hidden="true">&raquo;</span>
	  </a>
	</li>
	<?php endif; ?>
	
  </ul>
</nav>

<?php endif; ?>
