<?php

use Krystal\Form\Widget\CheckBoxWidget;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> 
		<span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Faq:Admin:Add@indexAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new FAQ'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>

		 <?php if (!empty($faqs)): ?>
		 
		 <li><a href="#" data-button="save-changes"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-button="remove-selected"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<?php $this->loadBlock('items-per-page', array('caption' => 'FAQ')); ?>

<form>
	<div class="table-responsive">
		<table class="table table-hover table-bordered table-striped table-condensed">
			<thead>
				<tr>
					<th class="text-center">
						<?php if (!empty($faqs)): ?>
						<input type="checkbox" />
						<?php endif; ?>
					</th>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Question'); ?></th>
					<th class="text-center"><?php $this->show('Published'); ?></th>
					<th class="text-center"><?php $this->show('Order'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>
			
			<?php if (!empty($faqs)): ?>
			<tbody>
				
				<?php foreach ($faqs as $faq): ?>
				<tr>
					<td class="text-center">
						<input type="checkbox" name="toDelete[<?php echo $faq->getId(); ?>]" />
					</td>
					<td class="text-center text-muted"><?php echo $faq->getId(); ?></td>
					<td class="text-center"><?php echo $faq->getQuestion(); ?></td>
					<td class="text-center">
						<?php echo CheckBoxWidget::render(array('name' => sprintf('published[%s]', $faq->getId())), $faq->getPublished()); ?>
					</td>
					<td class="text-center col-md-1">
						<input type="number" class="form-control" min="0" name="order[<?php echo $faq->getId(); ?>]" value="<?php echo $faq->getOrder(); ?>" />
					</td>
					<td class="text-center">
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this pair'); ?>" data-button="edit" href="<?php echo $this->url('Faq:Admin:Edit@indexAction', $faq->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this pair'); ?>" data-button="delete" data-id="<?php echo $faq->getId(); ?>" data-category="main" href="#" ><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				<?php endforeach; ?>
				
			</tbody>
			<?php endif; ?>
			
		</table>
		
		<?php if (empty($faqs)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No faqs'); ?></h2>
		</div>
		<?php endif; ?>
		
	</div>
</form>

<?php $this->loadBlock('paginator'); ?>
