<?php

use Krystal\Form\Widget\CheckBoxWidget;

?>

<form>
	<div class="well clearfix">
		
		<input type="hidden" name="id" value="<?php echo $faq->getId(); ?>" />
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Question'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="question" class="form-control" value="<?php echo $faq->getQuestion(); ?>" placeholder="<?php $this->show('Question title'); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Answer'); ?></label>
			<div class="col-lg-10">
				<textarea name="answer" rows="7"><?php echo $faq->getAnswer(); ?></textarea>
			</div>
		</div>
		
		
		<div class="options">
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
				<div class="col-lg-10">
					<?php echo CheckBoxWidget::render(array('name' => 'published', 'class' => 'form-control'), $faq->getPublished()); ?>
				</div>
			</div>
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
				<div class="col-lg-10">				
					<div class="input-group">
						<input type="number" name="order" class="form-control" value="<?php echo $faq->getOrder(); ?>" placeholder="<?php $this->show('Order of this question'); ?>" />
						<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
					</div>
				</div>
			</div>
			
		</div>
	</div>
	
	<?php if ($faq->getId()): ?>
	
	<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
	
	<?php else: ?>
	
	<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
	
	<?php endif; ?>
	<button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
	<button data-button="cancel" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
	
</form>
