<!DOCTYPE html>
<html>
<head>
 <meta charset="utf-8" />
 <title><?= $this->translate($title); ?></title>
 
 <?php foreach ($this->getPluginBag()->getStylesheets() as $stylesheet): ?>
 <link rel="stylesheet" media="screen" href="<?= $stylesheet; ?>"  />
 <?php endforeach; ?>
 
</head>

<body>

<main><?= $fragment; ?></main>

<?php $this->loadPartial('ajax'); ?>

<?php foreach ($this->getPluginBag()->getScripts() as $script): ?>
<script src="<?= $script; ?>"></script>
<?php endforeach; ?>

</body>
</html>