<div class="container">
    <h2 class="page-header"><i class="bi bi-check-circle"></i> <?= $this->translate('Congrats!'); ?></h2>

    <div class="alert alert-success alert-dismissible fade show">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <strong><?= $this->translate('You have successfully installed Bono CMS!'); ?></strong>
    </div>

    <blockquote>
        <p><?= $this->translate('When first time entering administration panel, use these credentials to authorize yourself'); ?>: </p>
        <p><?= $this->translate('Login'); ?>: <em>admin</em></p>
        <p><?= $this->translate('Password'); ?>: <em>admin</em></p>
        <p><?= $this->translate("And don't forget to change these! Otherwise any kid would easily hack your site!"); ?></p>
    </blockquote>

    <h2 class="text-muted"><i class="bi bi-signpost"></i> <?= $this->translate('Now you can'); ?></h2>
    <h3><i class="bi bi-house"></i> <a href="/"><?= $this->translate('Visit your new site'); ?></a></h3>
    <h3><i class="bi bi-person"></i> <a href="/admin" target="_blank"><?= $this->translate('Open administration panel'); ?></a></h3>
    
    <h1 class="text-muted float-end"><i class="bi bi-music-note"></i> <?= $this->translate('Stay Tuned!'); ?></h1>
</div>