<?php defined('KRYSTAL') or die; ?>

<div class="container">
    <h2 class="page-header"><i class="glyphicon glyphicon-ok"></i> <?php $this->show('Congrats!'); ?></h2>

    <div class="alert alert-dismissible alert-success">
        <strong><?php $this->show('You have successfully installed Bono CMS!'); ?></strong>
    </div>

    <blockquote>
        <p><?php $this->show('When first time entering administration panel, use these credentials to authorize yourself'); ?>: </p>
        <p><?php $this->show('Login'); ?>: <em>admin</em></p>
        <p><?php $this->show('Password'); ?>: <em>admin</em></p>
        <p><?php $this->show("And don't forget to change these! Otherwise any kid would easily hack your site!"); ?></p>
    </blockquote>

    <h2 class="text-muted"><i class="glyphicon glyphicon-road"></i> <?php $this->show('Now you can'); ?></h2>
    <h3><i class="glyphicon glyphicon-home"></i> <a href="/"><?php $this->show('Visit your new site'); ?></a></h3>
    <h3><i class="glyphicon glyphicon-user"></i> <a href="/admin" target="_blank"><?php $this->show('Open administration panel'); ?></a></h3>
    
    <h1 class="text-muted pull-right"><i class="glyphicon glyphicon-music"></i> <?php $this->show('Stay Tuned!'); ?></h1>
</div>
