
		
		<div class="well">
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php echo $this->translate('Storage engine'); ?><b>*</b></label>
				<div class="col-lg-10">
					<select name="engine" size="1" class="form-control">
						
						<?php foreach($engines as $engine): ?>
						<option><?php echo $engine; ?></option>
						<?php endforeach; ?>
						
					</select>
				</div>
			</div>
			
			
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php echo $this->translate('Host'); ?><b>*</b></label>
				<div class="col-lg-10">
					<input type="text" name="host" class="form-control" value="127.0.0.1" placeholder="<?php echo $this->translate('Host'); ?>" />
				</div>
			</div>
			
			
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php echo $this->translate('Username'); ?><b>*</b></label>
				<div class="col-lg-10">
					<input type="text" name="username" class="form-control" value="root" placeholder="<?php echo $this->translate('Username'); ?>" />
				</div>
			</div>
			
			
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php echo $this->translate('Password'); ?><b>*</b></label>
				<div class="col-lg-10">
					<input type="text" name="username" class="form-control" value="root" placeholder="<?php echo $this->translate('Target password'); ?>" />
				</div>
			</div>
			
			
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php echo $this->translate('Database'); ?><b>*</b></label>
				<div class="col-lg-10">
					<input type="text" name="database" class="form-control" value="root" placeholder="<?php echo $this->translate('Database where system will be installed in'); ?>" />
				</div>
			</div>
			
			<button><?php echo $this->translate('Next'); ?></button>
			
		</div>
		
		