<?php

use Krystal\Form\Widget\CheckBoxWidget;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Reviews:Admin:Add@indexAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new review'); ?></a></li>
		 <li><a href="<?php echo $this->url('Reviews:Admin:Config@indexAction'); ?>"><i class="glyphicon glyphicon-tasks"></i> <?php $this->show('Configuration'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 
		 <?php if (!empty($reviews)): ?>
		 <li><a href="#" data-button="save-changes"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes');?></a></li>
		 <li><a href="#" data-button="remove-selected" data-button="remove-selected"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes');?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php endif; ?>
		 
	  </ul>
	</div>
</div>

<?php $this->loadBlock('items-per-page', array('caption' => 'Reviews')); ?>

<form>
	<div class="table-responsive">
		<table class="table table-hover table-bordered table-striped table-condensed">
			<thead>
				<tr>
					<th class="text-center">
						<?php if (!empty($reviews)): ?>
						<input type="checkbox" />
						<?php endif; ?>
					</th>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Name'); ?></th>
					<th class="text-center"><?php $this->show('Email'); ?></th>
					<th class="text-center"><?php $this->show('Date'); ?></th>
					<th class="text-center"><?php $this->show('IP-Address'); ?></th>
					<th class="text-center"><?php $this->show('Published'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>
			
			<?php if (!empty($reviews)): ?>
			<tbody>
				<?php foreach ($reviews as $review): ?>
				<tr>
					<td class="text-center">
						<input type="checkbox" name="toDelete[<?php echo $review->getId(); ?>]" />
					</td>
					<td class="text-center text-muted"><?php echo $review->getId(); ?></td>
					<td class="text-center"><?php echo $review->getName(); ?></td>
					<td class="text-center"><?php echo $review->getEmail(); ?></td>
					<td class="text-center"><?php echo date($dateFormat, $review->getTimestamp()); ?></td>
					<td class="text-center">
						<a href="#"><?php echo $review->getIp(); ?></a>
					</td>
					<td class="text-center">
						<?php echo CheckBoxWidget::render(array('name' => sprintf('published[%s]', $review->getId())), $review->getPublished()); ?>
					</td>
					<td class="text-center">
						<a data-button="edit" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this review'); ?>" href="<?php echo $this->url('Reviews:Admin:Edit@indexAction', $review->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
						<a data-button="delete" href="#" data-category="main" data-id="<?php echo $review->getId(); ?>" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this review'); ?>"><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				
				<?php endforeach; ?>
			</tbody>
			<?php endif; ?>
			
		</table>

		<?php if (empty($reviews)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No reviews'); ?></h2>
		</div>
		<?php endif; ?>
		
	</div>
	
</form>

<?php $this->loadBlock('paginator'); ?>
