<?php

use Krystal\Form\Widget\CheckBoxWidget;

?>

<form>
	<div class="well clearfix">
		
		<input type="hidden" name="review[id]" value="<?php echo $review->getId(); ?>" />
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="review[name]" class="form-control" placeholder="<?php $this->show('Name of the person who left this message'); ?>" value="<?php echo $review->getName(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Email'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" class="form-control" name="review[email]" placeholder="<?php $this->show('Email of the person who left this message'); ?>" value="<?php echo $review->getEmail(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Date'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="review[date]" class="form-control" placeholder="<?php $this->show('Date of the publication'); ?>" value="<?php echo date($dateFormat, $review->getTimestamp()); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
				</div>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Content'); ?></label>
			<div class="col-lg-10">
				<textarea name="review[review]"><?php echo $review->getReview(); ?></textarea>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
			<div class="col-lg-10">
				<?php echo CheckBoxWidget::render(array('name' => 'review[published]', 'class' => 'form-control'), $review->getPublished()); ?>
			</div>
		</div>
		
	</div>
	
	<?php if ($review->getId()):?>
	
	<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
	
	<?php else: ?>
	
	<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php echo $this->translate('Add'); ?></button>
	<button data-button="add-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php echo $this->translate('Add & Create new'); ?></button>
	
	<?php endif; ?>
	
	<button data-button="cancel" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
	
</form>
