<?php

use Krystal\Form\Widget\CheckBoxWidget;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<span class="glyphicon glyphicon-list"></span> <?php $this->show('Menu'); ?> 
		<span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('QA:Admin:Add@indexAction'); ?>"><i class="glyphicon glyphicon-plus"></i> <?php $this->show('Add a pair'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 
		 <?php if (!empty($pair)):?>
		 
		 <li><a href="#" data-button="save-changes"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-button="remove-selected"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<?php $this->loadBlock('items-per-page', array('caption' => 'Questions and Answers')); ?>

<form>
	<div class="table-responsive">
		<table class="table table-hover table-bordered table-striped table-condensed">
			<thead>
				<tr>
					<th class="text-center">
						<input type="checkbox" />
					</th>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Question'); ?></th>
					<th class="text-center"><?php $this->show('Questioner'); ?></th>
					<th class="text-center"><?php $this->show('Answerer'); ?></th>
					<th class="text-center"><?php $this->show('Published'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>
			
			<?php if (!empty($pair)): ?>
			<tbody>
				<?php foreach ($pair as $qa): ?>
				<tr>
					<td class="text-center">
						<input type="checkbox" name="toDelete[<?php echo $qa->getId(); ?>]" />
					</td>
					<td class="text-center text-muted"><?php echo $qa->getId(); ?></td>
					<td class="text-center"><?php echo $qa->getQuestion(); ?></td>
					<td class="text-center"><?php echo $qa->getQuestioner(); ?></td>
					<td class="text-center"><?php echo $qa->getAnswerer(); ?></td>
					<td class="text-center">
						<?php echo CheckBoxWidget::render(array('name' => sprintf('published[%s]', $qa->getId())), $qa->getPublished()); ?>
					</td>
					<td class="text-center">
						<a data-button="edit" href="<?php echo $this->url('QA:Admin:Edit@indexAction', $qa->getId()); ?>" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this pair'); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
						<a data-button="delete" href="#" data-category="main" data-id="<?php echo $qa->getId(); ?>" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this pair'); ?>"><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				<?php endforeach; ?>
				
			</tbody>
			<?php endif; ?>
			
		</table>
		
		<?php if (empty($pair)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No pairs'); ?></h2>
		</div>
		<?php endif; ?>
		
	</div>
</form>

<?php $this->loadBlock('paginator'); ?>
