<?php

use Krystal\Form\Widget\CheckBoxWidget;

?>

<form>
	<div class="well clearfix">
		
		<input type="hidden" name="qa[id]" value="<?php echo $qa->getId() ;?>" />
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Question'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="qa[question]" class="form-control" placeholder="<?php $this->show('Type the question'); ?>" value="<?php echo $qa->getQuestion(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Questioner'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="qa[questioner]" class="form-control" placeholder="<?php $this->show('Person who asked this question'); ?>" value="<?php echo $qa->getQuestioner(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Answerer'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="qa[answerer]" class="form-control" placeholder="<?php $this->show('Person who answered this question'); ?>" value="<?php echo $qa->getAnswerer(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Answer'); ?></label>
			<div class="col-lg-10">
				<textarea name="qa[answer]"><?php echo $qa->getAnswer(); ?></textarea>
			</div>
		</div>
		
		
		<div class="options">
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Date asked'); ?></label>
				<div class="col-lg-10">
					<div class="input-group date">
						<input type="text" name="qa[date_asked]" class="form-control" placeholder="<?php $this->show('Date of the question'); ?>" value="<?php echo date($timeFormat, $qa->getTimestampAsked()); ?>" />
						<span class="input-group-addon"><i class="glyphicon glyphicon-calendar" data-toggle="tooltip" title="<?php $this->show('Change the date'); ?>"></i></span>
					</div>
				</div>
			</div>
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Date answered'); ?></label>
				<div class="col-lg-10">
					<div class="input-group date">
						<input type="text" name="qa[date_answered]" class="form-control" placeholder="<?php $this->show('Date of the answer'); ?>" value="<?php echo date($timeFormat, $qa->getTimestampAnswered()); ?>" />
						<span class="input-group-addon"><i class="glyphicon glyphicon-calendar" data-toggle="tooltip" title="<?php $this->show('Change the date'); ?>"></i></span>
					</div>
				</div>
			</div>
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
				<div class="col-lg-10">
					<?php echo CheckBoxWidget::render(array('name' => 'qa[published]', 'class' => 'form-control'), $qa->getPublished()); ?>
				</div>
			</div>
			
		</div>
	</div>
	
	<?php if (!$qa->getId()): ?>

	<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
	<?php else: ?>

	<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>

	<?php endif; ?>

	<button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
	<button data-button="cancel" type="button" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>

</form>
