<form>
	<div class="well clearfix">
		
		<input type="hidden" name="id" value="<?php echo $qa->getId() ;?>" />
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php echo $this->translate('Question'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="question" class="form-control" placeholder="<?php echo $this->translate('Type the question'); ?>" value="<?php echo $qa->getQuestion(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php echo $this->translate('Questioner'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="questioner" class="form-control" placeholder="<?php echo $this->translate('Person who asked this question'); ?>" value="<?php echo $qa->getQuestioner(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php echo $this->translate('Answerer'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="answerer" class="form-control" placeholder="<?php echo $this->translate('Person who answered this question'); ?>" value="<?php echo $qa->getAnswerer(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php echo $this->translate('Answer'); ?></label>
			<div class="col-lg-10">
				<textarea name="answer" rows="7" class="form-control"><?php echo $qa->getAnswer(); ?></textarea>
			</div>
		</div>
		
		
		
		<div class="options">
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php echo $this->translate('Date asked'); ?></label>
				<div class="col-lg-10">
					<div class="input-group date">
						<input type="text" name="date_asked" class="form-control" placeholder="<?php echo $this->translate('Date of the question'); ?>" value="<?php echo date($timeFormat, $qa->getTimestampAsked()); ?>" />
						<span class="input-group-addon"><i class="glyphicon glyphicon-calendar" data-toggle="tooltip" title="<?php echo $this->translate('Change the date'); ?>"></i></span>
					</div>
				</div>
			</div>
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php echo $this->translate('Date answered'); ?></label>
				<div class="col-lg-10">
					<div class="input-group date">
						<input type="text" name="date_answered" class="form-control" placeholder="<?php echo $this->translate('Date of the answer'); ?>" value="<?php echo date($timeFormat, $qa->getTimestampAnswered()); ?>" />
						<span class="input-group-addon"><i class="glyphicon glyphicon-calendar" data-toggle="tooltip" title="<?php echo $this->translate('Change the date'); ?>"></i></span>
					</div>
				</div>
			</div>
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php echo $this->translate('Published'); ?></label>
				<div class="col-lg-10">
					<input type="hidden" name="published" value="0" />
					<input type="checkbox" name="published" value="1" class="form-control" <?php $this->getHelper()->checkOnDemand($qa->getPublished()); ?> />
				</div>
			</div>
			
		</div>
	</div>
	
	<?php if (!isset($editing)): ?>

	<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
	<?php else: ?>

	<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>

	<?php endif; ?>

	<button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
	<button data-button="cancel" type="button" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>

</form>
