<?php

use Krystal\Form\Widget\BooleanWidget;
use Krystal\Form\Widget\CheckBoxWidget;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Shop:Admin:Product:Add@indexAction'); ?>"><i class="glyphicon glyphicon-shopping-cart"></i> <?php $this->show('Add product'); ?></a></li>
		 <li><a href="<?php echo $this->url('Shop:Admin:Category:Add@indexAction'); ?>"><i class="glyphicon glyphicon-folder-open"></i> <?php $this->show('Add category'); ?></a></li>
		 <li><a href="<?php echo $this->url('Shop:Admin:Config@indexAction'); ?>"><i class="glyphicon glyphicon-th-large"></i> <?php $this->show('Configuration'); ?></a></li>
		 <li><a href="<?php echo $this->url('Shop:Admin:Stat@indexAction'); ?>"><i class="glyphicon glyphicon-calendar"></i> <?php $this->show('Statistic'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 
		 <?php if (!empty($products)):?>
		 <li><a href="#" data-button="save-changes"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes');?></a></li>
		 <li><a href="#" data-button="remove-selected" data-button="remove-selected"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes');?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<div>
	
	<?php $this->loadBlock('items-per-page', array('caption' => 'Products')); ?>
	
	<form action="<?php echo $this->url('Shop:Admin:Browser@filterAction', null); ?>" novalidate>
		
		<div class="table-responsive">
			<table class="table table-hover table-bordered table-striped">
				<thead>
					<tr>
						<th class="text-center"><input type="checkbox" /></th>
						<th class="text-center"><?php $this->show('#'); ?></th>
						<th class="text-center"><?php $this->show('Cover'); ?></th>
						<th class="text-center"><?php $this->show('Title'); ?> </th>
						<th class="text-center"><?php $this->show('Date'); ?></th>
						<th class="text-center"><?php $this->show('Category'); ?></th>
						<th class="text-center"><?php $this->show('Price'); ?></th>
						<th class="text-center"><?php $this->show('Published'); ?></th>
						<th class="text-center"><?php $this->show('SEO'); ?></th>
						<th class="text-center"><?php $this->show('Actions'); ?></th>
					</tr>
					
					<tr>
						<th></th>
						<th>
							<input type="number" name="filter[id]" min="1" class="form-control col-md-1" value="<?php echo $filter->get('id'); ?>" />
						</th>
						<th></th>
						<th>
							<input type="text" name="filter[title]" class="form-control" value="<?php echo $filter->get('title'); ?>" />
						</th>
						<th>
							<input type="text" name="filter[date]" class="form-control" />
						</th>
						<th></th>
						<th>
							<input type="text" name="filter[price]" class="form-control" value="<?php echo $filter->get('price'); ?>" />
						</th>
						
						<th class="text-center">
							<?php echo BooleanWidget::render(array('name' => 'filter[published]', 'class' => 'form-control'), $filter->get('published'), $this->getTranslator()); ?>
						</th>
						
						<th class="text-center">
							<?php echo BooleanWidget::render(array('name' => 'filter[seo]', 'class' => 'form-control'), $filter->get('seo'), $this->getTranslator()); ?>
						</th>
						
						<th></th>
					</tr>
					
				</thead>

				<?php if (!empty($products)):?>
				<tbody>
					
					<?php foreach ($products as $product): ?>
					<tr>
						<td class="text-center">
							<input type="checkbox" name="toDelete[<?php echo $product->getId(); ?>]" />
						</td>
						<td class="col-lg-1 text-center text-muted"><?php echo $product->getId(); ?></td>
						<td data-selectable="true">
							<a data-lightbox="<?php printf('image-%s', $product->getId()); ?>" href="<?php echo $product->getImageBag()->getUrl('original'); ?>"><img class="img-responsive center-block" src="<?php echo $product->getImageBag()->getUrl('120x120'); ?>" /></a>
						</td>
						<td data-selectable="true" class="text-center"><?php echo $product->getTitle(); ?></td>
						<td class="text-center"><?php echo date('d-m-Y', $product->getTimestamp()); ?></td>
						<td class="text-center"><?php echo $product->getCategoryName(); ?></td>
						<td class="text-center col-lg-2">
							<input type="number" class="form-control center-block" min="0" name="price[<?php echo $product->getId(); ?>]" value="<?php echo $product->getPrice(); ?>" />
						</td>
						<td class="text-center">
							<?php echo CheckBoxWidget::render(array('name' => sprintf('published[%s]', $product->getId())), $product->getPublished()); ?>
						</td>
						<td class="text-center">
							<?php echo CheckBoxWidget::render(array('name' => sprintf('seo[%s]', $product->getId())), $product->getSeo()); ?>
						</td>
						<td class="text-center">
							<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('View this product on site'); ?>" data-button="view" href="<?php echo $product->getUrl(); ?>" target="_blank"><i class="glyphicon glyphicon-search"></i></a>
							<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this product'); ?>" data-button="edit" href="<?php echo $this->url('Shop:Admin:Product:Edit@indexAction', $product->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
							<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this product'); ?>" data-button="delete" data-category="product" data-id="<?php echo $product->getId(); ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
						</td>
					</tr>
					
					<?php endforeach; ?>
					
				</tbody>
				<?php endif; ?>
				
			</table>

			<div>
				<button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-filter"></i> <?php $this->show('Filter'); ?></button>
				<br />
			</div>
			
			<div class="center-block" id="l" style="display:none;">
				<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Loading'); ?></h2>
			</div>
			
			<?php if (empty($products)): ?>
			<div class="center-block">
				<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No products'); ?></h2>
			</div>
			<?php endif; ?>
			
		</div>
	</form>
	
	<?php $this->loadBlock('paginator'); ?>
</div>


<div class="clearfix">
	<h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Categories'); ?> (<?php echo count($categories); ?>)</h4>
	
	<table class="table table-hover table-bordered table-striped">
		<thead>
			<tr>
				<th class="text-center"><?php $this->show('#'); ?></th>
				<th class="text-center"><?php $this->show('Name'); ?></th>
				<th class="text-center"><?php $this->show('Amount of products'); ?></th>
				<th class="text-center"><?php $this->show('Actions'); ?></th>
			</tr>
		</thead>
		
		<?php if (!empty($categories)): ?>
		<tbody>
			<?php foreach ($categories as $id => $category): ?>
			
			<tr <?php $this->getHelper()->addClassOnDemand(isset($currentCategoryId) && $currentCategoryId == $id, 'info'); ?>>
				<td class="text-center text-muted"><?php echo $id; ?></td>
				<td>
					<a class="pull-left" href="<?php echo $this->url('Shop:Admin:Browser@categoryAction', $id); ?>">
						<?php $this->getHelper()->wrapOnDemand(isset($currentCategoryId) && $currentCategoryId == $id, 'strong', $category); ?>
					</a>
				</td>
				
				<td class="text-center col-md-1"><?php echo $taskManager->getProductCountByCategoryId($id); ?></td>
				<td class="text-center">
					<a target="_blank" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('View this category'); ?>" data-button="view" href="<?php echo $taskManager->fetchByCategoryId($id)->getUrl(); ?>"><i class="glyphicon glyphicon-search"></i></a>
					<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this category'); ?>" data-button="edit" href="<?php echo $this->url('Shop:Admin:Category:Edit@indexAction', $id); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
					<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this category'); ?>" data-button="delete" data-button="delete" data-category="category" data-id="<?php echo $id; ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
		<?php endif; ?>
		
	</table>
	
	<?php if (empty($categories)): ?>
	<div class="center-block">
		<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
	</div>
	<?php endif; ?>
	
</div>
