<?php

use Krystal\Form\Widget\CheckBoxWidget;
use Krystal\Form\Widget\DropdownWidget;
use Krystal\Form\HtmlHelper;

?>

<form>

	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#page" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Category'); ?></a></li>
		<li role="presentation"><a href="#menu" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-list"></i> <?php $this->show('Item in menu'); ?></a></li>
	</ul>
	
	
	<div class="tab-content">
		<div class="tab-pane fade in active" id="page" role="tabpanel">
			<div class="well clearfix">
				
				<!--Special hidden value for menu widget. That's a workaround-->
				<input type="hidden" name="web_page_id" value="<?php echo $category->getWebPageId(); ?>" />
				<input type="hidden" name="category[id]" value="<?php echo $category->getId(); ?>" />
				<input type="hidden" name="category[web_page_id]" value="<?php echo $category->getWebPageId(); ?>" />
				<input type="hidden" name="category[cover]" value="<?php echo $category->getCover(); ?>" />
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
							<input type="text" name="category[title]" class="form-control" placeholder="<?php $this->show('Category title'); ?>" data-input="title" value="<?php echo $category->getTitle(); ?>" />
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Parent category'); ?></label>
					<div class="col-lg-10">
						<?php echo DropdownWidget::render(array('name' => 'category[parent_id]', 'class' => 'form-control'), $categories, $category->getParentId(), '— '.$this->translate('None').' —'); ?>
					</div>
				</div>
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
					<div class="col-lg-10">
						<textarea name="category[description]" rows="7" class="form-control"><?php echo $category->getDescription(); ?></textarea>
					</div>
				</div>
				
				
				
				<div class="options">
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
						<div class="col-lg-10">
							<?php echo CheckBoxWidget::render(array('name' => 'category[seo]', 'class' => 'form-control'), $category->getSeo()); ?>
						</div>
					</div>
					
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
						<div class="col-lg-10">
							<div class="input-group">
								<input type="text" name="category[order]" class="form-control" placeholder="<?php $this->show('Category order'); ?>" value="<?php echo $category->getOrder(); ?>" />
								<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
							</div>
						</div>
					</div>
					
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
						<div class="col-lg-10">
							<div class="input-group">
								<input type="text" name="category[slug]" class="form-control" data-input="slug" placeholder="<?php $this->show('URL slug for this category. By default is taken from a title'); ?>" value="<?php echo $category->getSlug(); ?>" />
								<span class="input-group-addon">
									<a href="#" data-button="slug"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i></a>
								</span>
							</div>
						</div>
					</div>
					
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
						<div class="col-lg-10">
							<div class="input-group">
								<input type="text" name="category[keywords]" class="form-control" placeholder="<?php $this->show('Keywords used for search engines'); ?>" value="<?php echo $category->getKeywords(); ?>" />
								<span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
							</div>
						</div>
					</div>
					
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
						<div class="col-lg-10">
							<textarea name="category[meta_description]" class="form-control" placeholder="<?php $this->show('Meta description for search engines'); ?>"><?php echo $category->getMetaDescription(); ?></textarea>
						</div>
					</div>
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Сover'); ?></label>
						<div class="col-lg-10">

							<?php if ($category->hasCover()): ?>

							<img src="<?php echo $category->getImageBag()->getUrl('200x200'); ?>" />

							<br />
							<br />

							<div>
								<label for="removeCover"><?php $this->show('Remove this cover'); ?>&nbsp;</label>
								<input type="checkbox" id="removeCover" name="category[remove_cover]" data-toggle="tooltip" data-placement="left" title="<?php $this->show('Check it if you want to remove this cover'); ?>" />
							</div>
							
							<?php else: ?>
							
							<img data-image="preview" />
							
							<?php endif; ?>
							
							<br />
							<br />
							
							<input type="file" name="file" accept="image/x-png, image/gif, image/jpeg" />
						</div>
					</div>
					
				</div>
			</div>
			
			<?php if ($category->getId()): ?>
			<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
			<button data-button="save-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Save & Create new'); ?></button>
			
			<?php else: ?>
			<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
			<button data-button="add-create" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-open"></span> <?php $this->show('Add & Create new'); ?></button>
			
			<?php endif; ?>
			
			<button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
			<button data-button="cancel" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
			
		</div>
		
		
		<div class="tab-pane fade" id="menu" role="tabpanel">
			<?php $this->loadBlock('menu-widget'); ?>
		</div>
		
	</div>
</form>
