
<h2><i class="glyphicon glyphicon-user"></i> <?php $this->show('Orders'); ?> (<?php echo $paginator->getTotalAmount(); ?>)</h2>

<div class="table-responsive">
	<?php $this->loadBlock('items-per-page', array('caption' => 'Recent orders')); ?>
	
	<table class="table table-hover table-bordered table-striped">
		<thead>
			<tr>
				<th class="text-center"><?php $this->show('#'); ?></th>
				<th class="text-center"><?php $this->show('Date'); ?></th>
				<th class="text-center"><?php $this->show('Customer'); ?></th>
				<th class="text-center"><?php $this->show('Phone'); ?></th>
				<th class="text-center"><?php $this->show('Address'); ?></th>
				<th class="text-center"><?php $this->show('Comment'); ?></th>
				<th class="text-center"><?php $this->show('Delivery type'); ?></th>
				<th class="text-center"><?php $this->show('Qty'); ?></th>
				<th class="text-center"><?php $this->show('Total price'); ?></th>
				<th class="text-center"><?php $this->show('Approved'); ?></th>
				<th class="text-center"><?php $this->show('Actions'); ?></th>
			</tr>
		</thead>
		
		<?php if (!empty($orders)): ?>
		<tbody>
			
			<?php foreach($orders as $order): ?>
			<tr>
				<td class="text-center text-muted"><?php echo $order->getId(); ?></td>
				<td class="text-center"><?php echo $order->getDate(); ?></td>
				<td class="text-center"><?php echo $order->getName(); ?></td>
				<td class="text-center"><?php echo $order->getPhone(); ?></td>
				<td class="text-center"><?php echo $order->getAddress(); ?></td>
				<td class="text-center"><?php echo $order->getComment(); ?></td>
				<td class="text-center"><?php echo $order->getDelivery(); ?></td>
				<td class="text-center"><?php echo $order->getQty(); ?></td>
				<td class="text-center"><?php echo $order->getTotalPrice(); ?></td>
				<td class="text-center"><?php $this->show($order->getApproved() ? 'Yes' : 'No'); ?></td>
				<td class="text-center">
					<?php if (!$order->getApproved()):?>
					<a data-toggle="tooltip" data-placement="left" title="<?php $this->show('Approve this order'); ?>" data-button="approve" href="#" data-id="<?php echo $order->getId(); ?>"><i class="glyphicon glyphicon-ok"></i></a>
					<?php endif; ?>
					
					<a data-toggle="tooltip" data-placement="left" title="<?php $this->show('Remove this order'); ?>" data-button="delete" data-category="order" data-id="<?php echo $order->getId(); ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
					<a data-toggle="tooltip" data-placement="left" title="<?php $this->show('View purchased products'); ?>" data-button="details" href="<?php echo $this->url('Shop:Admin:Order@detailsAction', $order->getId()); ?>"><i class="glyphicon glyphicon-th-list"></i></a>
				</td>
			</tr>
			<?php endforeach; ?>
			
		</tbody>
		<?php endif; ?>
		
	</table>
	
	<?php $this->loadBlock('paginator'); ?>
	
	
	<?php if (empty($orders)): ?>
	<div class="center-block">
		<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No orders'); ?></h2>
	</div>
	<?php endif; ?>
	
</div>

<a href="<?php echo $this->url('Shop:Admin:Browser@indexAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-chevron-left"></i> <?php $this->show('Back'); ?></a>
