<?php

use Krystal\Form\Widget\BooleanWidget;
use Krystal\Form\HtmlHelper;

?>

<h2><i class="glyphicon glyphicon-user"></i> <?php $this->show('Orders'); ?> (<?php echo $paginator->getTotalAmount(); ?>)</h2>

<a href="<?php echo $this->url('Shop:Admin:Browser@indexAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-chevron-left"></i> <?php $this->show('Back'); ?></a>

<div class="table-responsive">
	<?php $this->loadBlock('items-per-page', array('caption' => 'Recent orders')); ?>
	
	<form action="<?php echo $this->url('Shop:Admin:Order@filterAction', null); ?>" novalidate>
		<table class="table table-hover table-bordered table-striped">
			<thead>
				<tr>
					<th class="text-center">
						<a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('id'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('id'); ?>"><i class="<?php echo $filter->isSortedByDesc('id') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> #</a>
					</th>
					<th class="text-center">
						<a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('date'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('date'); ?>"><i class="<?php echo $filter->isSortedByDesc('date') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Date'); ?></a>
					</th>
					<th class="text-center">
						<a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('name'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('name'); ?>"><i class="<?php echo $filter->isSortedByDesc('name') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Customer'); ?></a>
					</th>
					<th class="text-center">
						<a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('phone'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('phone'); ?>"><i class="<?php echo $filter->isSortedByDesc('name') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Phone'); ?></a>
					</th>
					<th class="text-center">
						<a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('address'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('address'); ?>"><i class="<?php echo $filter->isSortedByDesc('address') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Address'); ?></a>
					</th>
					<th class="text-center"><?php $this->show('Comment'); ?></th>
					<th class="text-center"><?php $this->show('Delivery type'); ?></th>
					<th class="text-center">
						<a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('qty'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('qty'); ?>"><i class="<?php echo $filter->isSortedByDesc('address') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Qty'); ?></a>
					</th>
					<th class="text-center">
						<a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('total_price'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('total_price'); ?>"><i class="<?php echo $filter->isSortedByDesc('total_price') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Total price'); ?></a>
					</th>
					<th class="text-center">
						<a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('approved'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('approved'); ?>"><i class="<?php echo $filter->isSortedByDesc('approved') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Approved'); ?></a>
					</th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
				
				<tr>
					<th class="col-md-1">
						<input type="number" min="1" class="form-control" name="filter[id]" value="<?php echo $filter->get('id'); ?>" />
					</th>
					<th>
						<input type="text" name="filter[date]" class="form-control" value="<?php echo $filter->get('date'); ?>" />
					</th>
					<th>
						<input type="text" class="form-control" name="filter[name]" value="<?php echo $filter->get('name'); ?>" />
					</th>
					<th>
						<input type="text" class="form-control" name="filter[phone]" value="<?php echo $filter->get('phone'); ?>" />
					</th>
					<th>
						<input type="text" class="form-control" name="filter[address]" value="<?php echo $filter->get('address'); ?>" />
					</th>
					<th></th>
					<th></th>
					<th class="col-md-1">
						<input type="number" min="1" class="form-control" name="filter[qty]" value="<?php echo $filter->get('qty'); ?>" />
					</th>
					<th>
						<input type="number" step="any" min="1" class="form-control" name="filter[total_price]" value="<?php echo $filter->get('total_price'); ?>" />
					</th>
					<th>
						<?php echo BooleanWidget::render(array('name' => 'filter[approved]', 'class' => 'form-control'), $filter->get('approved'), $this->getTranslator()); ?>
					</th>
					<th></th>
				</tr>
				
			</thead>
			
			<?php if (!empty($orders)): ?>
			<tbody>
				
				<?php foreach($orders as $order): ?>
				<tr <?php HtmlHelper::addClassOnDemand(!$order->getApproved(), 'warning'); ?>>
					<td class="text-center text-muted"><?php echo $order->getId(); ?></td>
					<td class="text-center"><?php echo $order->getDate(); ?></td>
					<td class="text-center"><?php echo $order->getName(); ?></td>
					<td class="text-center"><?php echo $order->getPhone(); ?></td>
					<td class="text-center"><?php echo $order->getAddress(); ?></td>
					<td class="text-center"><?php echo $order->getComment(); ?></td>
					<td class="text-center"><?php echo $order->getDelivery(); ?></td>
					<td class="text-center"><?php echo $order->getQty(); ?></td>
					<td class="text-center"><?php echo $order->getTotalPrice(), PHP_EOL, $config->getCurrency(); ?></td>
					<td class="text-center"><?php $this->show($order->getApproved() ? 'Yes' : 'No'); ?></td>
					<td class="text-center">
						<?php if (!$order->getApproved()):?>
						<a data-toggle="tooltip" data-placement="left" title="<?php $this->show('Approve this order'); ?>" data-button="approve" href="#" data-id="<?php echo $order->getId(); ?>"><i class="glyphicon glyphicon-ok"></i></a>
						<?php endif; ?>
						
						<a data-toggle="tooltip" data-placement="left" title="<?php $this->show('Remove this order'); ?>" data-button="delete" data-category="order" data-id="<?php echo $order->getId(); ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
						<a data-toggle="tooltip" data-placement="left" title="<?php $this->show('View purchased products'); ?>" data-button="details" data-order-id="<?php echo $order->getId(); ?>" href="#"><i class="glyphicon glyphicon-th-list"></i></a>
					</td>
				</tr>
				<?php endforeach; ?>
				
			</tbody>
			<?php endif; ?>
			
		</table>
		
		<div>
			<?php if ($filter->isApplied()): ?>
			<a href="<?php echo $this->url('Shop:Admin:Order@indexAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-trash"></i> <?php $this->show('Reset filter'); ?></a>
			<?php endif; ?>
			<button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-filter"></i> <?php $this->show('Filter'); ?></button>
			<br />
		</div>
		
	</form>
	
	<?php $this->loadBlock('paginator'); ?>
	
	
	<?php if (empty($orders)): ?>
	<div class="center-block">
		<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No orders'); ?></h2>
	</div>
	<?php endif; ?>
	
</div>

<div class="modal fade" id="details-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 <div class="modal-dialog">
  <div class="modal-content">
	<div class="modal-header">
	  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	  <h4 class="modal-title"><i class="glyphicon glyphicon-eye-open"></i> <?php $this->show('Order details'); ?></h4>
	</div>
	<div class="modal-body" id="details-body"></div>
	<div class="modal-footer">
		<button type="button" class="btn btn-primary" data-dismiss="modal"><i class="glyphicon glyphicon-ok"></i> OK</button>
	</div>
 </div><!-- /.modal-content -->
 </div><!-- /.modal-dialog -->  
</div>
