<?php

use Krystal\Form\Widget\CheckBoxWidget;
use Krystal\Form\Widget\DropdownWidget;
use Krystal\Form\HtmlHelper;

?>

<?php if (!empty($categories)): ?>

<form>
	
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#product" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-shopping-cart"></i> <?php $this->show('Product'); ?></a></li>
		<li role="presentation"><a href="#images" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Images'); ?></a></li>
	</ul>
	
	
	<div class="tab-content">

	  <!--Product tab-->
	<div role="tabpanel" class="tab-pane active" id="product">
		<div class="well clearfix">
			
			<input type="hidden" name="product[id]" value="<?php echo $product->getId(); ?>" />
			<input type="hidden" name="product[cover]" value="<?php echo $product->getCover(); ?>" />
			<input type="hidden" name="product[web_page_id]" value="<?php echo $product->getWebPageId(); ?>" />
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
				<div class="col-lg-10">
					<div class="input-group">
						<input type="text" name="product[title]" class="form-control" value="<?php echo $product->getTitle(); ?>" data-input="title" placeholder="<?php $this->show('Product title'); ?>" />
						<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
					</div>
				</div>
			</div>
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Price'); ?></label>
				<div class="col-lg-10">
					<div class="input-group">
						<input type="number" min="1" step="0.01" name="product[regular_price]" class="form-control" value="<?php echo $product->getPrice(); ?>" placeholder="<?php $this->show('Price of the product to be added'); ?>" />
						<span class="input-group-addon"><i class="glyphicon glyphicon-euro"></i></span>
					</div>
				</div>
			</div>
			
			
			<div class="form-group clearfix <?php echo !$config->getStokePriceEnabled() ? 'hidden' : ''; ?>">
				<label class="col-lg-2 control-label"><?php $this->show('Stoke price'); ?></label>
				<div class="col-lg-10">
					<div class="input-group">
						<input type="number" name="product[stoke_price]" class="form-control" value="<?php echo $product->getStokePrice(); ?>" placeholder="<?php $this->show('Stoke price'); ?>" />
						<span class="input-group-addon"><i class="glyphicon glyphicon-euro"></i></span>
					</div>
				</div>
			</div>
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Category'); ?></label>
				<div class="col-lg-10">
					<?php echo DropdownWidget::render(array('name' => 'product[category_id]', 'class' => 'form-control'), $categories, $product->getCategoryId(), false); ?>
				</div>
			</div>
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
				<div class="col-lg-10">
					<textarea name="product[description]" rows="7" class="form-control"><?php echo $product->getDescription(); ?></textarea>
				</div>
			</div>
			
			
			<div class="form-group clearfix <?php HtmlHelper::addOnDemand($config->getSpecialSupport(), 'hidden'); ?>">
				<label class="col-lg-2 control-label"><?php $this->show('Special offer'); ?></label>
				<div class="col-lg-10">
					<?php echo CheckBoxWidget::render(array('name' => 'product[special_offer]', 'class' => 'form-control'), $product->getSpecialOffer()); ?>
				</div>
			</div>
			
			<div class="options">
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
							<input type="number" name="product[order]" class="form-control" value="<?php echo $product->getOrder(); ?>" placeholder="<?php $this->show('Order of the product to be sorted'); ?>" />
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
					<div class="col-lg-10">
						<?php echo CheckBoxWidget::render(array('name' => 'product[published]', 'class' => 'form-control'), $product->getPublished()); ?>
					</div>
				</div>
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
					<div class="col-lg-10">
						<?php echo CheckBoxWidget::render(array('name' => 'product[seo]', 'class' => 'form-control'), $product->getSeo()); ?>
					</div>
				</div>
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
							<input type="text" name="product[slug]" class="form-control" value="<?php echo $product->getSlug(); ?>" data-input="slug" placeholder="<?php $this->show('URL slug for this product. By default is taken from a title'); ?>" />
							<span class="input-group-addon">
								<a href="#" data-button="slug"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i></a>
							</span>
						</div>
					</div>
				</div>
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
							<input type="text" name="product[keywords]" class="form-control" value="<?php echo $product->getKeywords(); ?>" placeholder="<?php $this->show('Keywords used for search engines'); ?>" />
							<span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
						</div>
					</div>
				</div>
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
					<div class="col-lg-10">
						<textarea name="product[meta_description]" class="form-control" placeholder="<?php $this->show('Meta description for search engines'); ?>"><?php echo $product->getMetaDescription(); ?></textarea>
					</div>
				</div>
				
			</div>
		</div>

		<?php if (!$product->getId()): ?>

		<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-saved"></i> <?php $this->show('Add'); ?></button>
		<button data-button="add-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>

		<?php else: ?>

		<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-saved"></i> <?php $this->show('Save'); ?></button>

		<?php endif; ?>

		<button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
		<button data-button="cancel" type="button" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>

	  </div>
	  <!--/Home tab-->
	  
	  
	  <!--Images tab-->
	  <div role="tabpanel" class="tab-pane" id="images">
		<div class="well">
			
			<div id="file-input-container">
				<input type="file" name="file[]" accept="image/x-png, image/gif, image/jpeg" />
			</div>
			
			<div class="btn-container">
				<a class="btn btn-default dropdown-toggle" data-button="upload" href="#"><i class="glyphicon glyphicon-camera"></i> <?php $this->show('Upload new image'); ?></a></a>
			</div>
			
			<div class="table-responsive">
				<table class="table table-hover table-striped table-bordered table-condensed">
					<thead>
						<tr>
							<th class="text-center"><?php $this->show('Image'); ?></th>
							<th class="text-center"><?php $this->show('Order'); ?></th>
							<th class="text-center"><?php $this->show('Published'); ?></th>
							<th class="text-center"><?php $this->show('Cover'); ?></th>
							<th class="text-center"><?php $this->show('Actions'); ?></th>
						</tr>
					</thead>
					
					<tbody data-container="image">
						
						<?php if (!empty($photos)): ?>
						<?php foreach ($photos as $photo): ?>
						
						<tr>
							<td>
								<img class="img-responsive center-block" data-image="" width="200" height="200" src="<?php echo $photo->getImageBag()->getUrl('200x200'); ?>" />
							</td>
							
							<td class="text-center col-md-1">
								<input type="number" class="form-control center-block" value="<?php echo $photo->getOrder(); ?>" name="photos[order][<?php echo $photo->getId(); ?>]" />
							</td>
							
							<td class="text-center">
								<?php echo CheckBoxWidget::render(array('name' => sprintf('photos[published][%s]', $photo->getId())), $photo->getPublished()); ?>
							</td>
							
							<td class="text-center">
								<input type="radio" name="photos[cover]" value="<?php echo $photo->getImage(); ?>" <?php HtmlHelper::checkOnDemand($product->getCover() == $photo->getImage()); ?>/>
							</td>
							
							<td class="text-center">
								<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Replace this image'); ?>" data-button="edit" data-image="<?php echo $photo->getImage(); ?>" href="#"><i class="glyphicon glyphicon-pencil"></i></a>
								
								<?php if ($product->getCover() != $photo->getImage()): ?>
								<input type="checkbox" name="photos[toDelete][<?php echo $photo->getId(); ?>]" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Check if you want to remove this image'); ?>" /> <?php $this->show('Remove'); ?>
								<?php endif; ?>
								
								<input type="file" accept="image/x-png, image/gif, image/jpeg" class="hidden" name="<?php printf('image_%s', $photo->getId()); ?>" />
							</td>
						</tr>
						
						<?php endforeach; ?>
						<?php endif; ?>
						
					</tbody>
				</table>
				
			</div>
			
		</div>
	  </div>
	  <!--Images tab-->
	 
	 
	</div>
</form>

<?php else: ?>

<div class="well">
	<div class="center-block">
		<h2 class="text-muted text-center"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Before you add a product, you need to create at least one category'); ?></h2>
	</div>
</div>

<?php endif; ?>
