<?php

$add = is_array($add) ? call_user_func_array([$this, 'url'], $add) : $this->url($add);

if (isset($edit)) {
    $edit = is_array($edit) ? call_user_func_array([$this, 'url'], $edit) : $this->url($edit, '');
} else {
    $edit = $cancel;
}

if (isset($cancel)) {
    $cancel = is_array($cancel) ? call_user_func_array([$this, 'url'], $cancel) : $this->url($cancel);
}

$wrapperClass = $wrapperClass ?? 'actions';

?>

<div class="<?= $wrapperClass ?>">
    <?php if ($new && isset($add)): ?>
    <button data-button="add" data-back-url="<?= $edit ?>" data-url="<?= $this->url($save) ?>" class="btn btn-primary"><?= $this->translate('Add') ?></button>
    <button data-button="add-create" data-url="<?= $this->url($save) ?>" class="btn btn-primary"><?= $this->translate('Add & Create new') ?></button>

    <?php else: ?>
    <button data-button="save" data-url="<?= $this->url($save) ?>" class="btn btn-primary"><?= $this->translate('Save') ?></button>
    
    <?php if (isset($add)): ?>
    <button data-button="save-create" data-back-url="<?= $add ?>" data-url="<?= $this->url($save) ?>" class="btn btn-primary"><?= $this->translate('Save & Create new') ?></button>
    <?php endif; ?>
    
    <?php endif; ?>

    <?php if (isset($options) && $options == true): ?>
    <button data-button="options" class="btn btn-primary"><?= $this->translate('More options') ?></button>
    <?php endif; ?>

    <?php if (isset($cancel)): ?>
    <button data-button="cancel" data-url="<?= $cancel ?>" class="btn btn-secondary"><?= $this->translate('Cancel') ?></button>
    <?php endif; ?>
</div>