<?php

$add = is_array($add) ? call_user_func_array(array($this, 'url'), $add) : $this->url($add);

if (isset($edit)) {
    $edit = is_array($edit) ? call_user_func_array(array($this, 'url'), $edit) : $this->url($edit);
} else {
    $edit = $cancel;
}

if (isset($cancel)) {
    $cancel = is_array($cancel) ? call_user_func_array(array($this, 'url'), $cancel) : $this->url($cancel);
}

$wrapperClass = isset($wrapperClass) ? $wrapperClass : 'actions';

?>

<div class="<?= $wrapperClass; ?>">
    <?php if ($new): ?>
    <button data-button="add" data-back-url="<?php echo $edit; ?>" data-url="<?php echo $this->url($save); ?>" class="btn btn-primary"><?php $this->show('Add'); ?></button>
    <button data-button="add-create" data-url="<?php echo $this->url($save); ?>" class="btn btn-primary"><?php $this->show('Add & Create new'); ?></button>

    <?php else: ?>
    <button data-button="save" data-url="<?php echo $this->url($save); ?>" class="btn btn-primary"><?php $this->show('Save'); ?></button>
    <button data-button="save-create" data-back-url="<?php echo $add; ?>" data-url="<?php echo $this->url($save); ?>" class="btn btn-primary"><?php $this->show('Save & Create new'); ?></button>
    <?php endif; ?>

    <?php if (isset($options) && $options == true): ?>
    <button data-button="options" class="btn btn-primary"><?php $this->show('More options'); ?></button>
    <?php endif; ?>

    <?php if (isset($cancel)): ?>
    <button data-button="cancel" data-url="<?php echo $cancel; ?>" class="btn btn-default"><?php $this->show('Cancel'); ?></button>
    <?php endif; ?>
</div>