<?php

$add = is_array($add) ? call_user_func_array(array($this, 'url'), $add) : $this->url($add);

if (isset($cancel)) {
    $cancel = is_array($cancel) ? call_user_func_array(array($this, 'url'), $cancel) : $this->url($cancel);
}

?>
<div class="actions">
    <?php if ($new): ?>
    <button data-button="add" data-back-url="<?php echo $this->url($edit, null); ?>" data-url="<?php echo $this->url($save); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
    <button data-button="add-create" data-url="<?php echo $this->url($save); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>

    <?php else: ?>
    <button data-button="save" data-url="<?php echo $this->url($save); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
    <button data-button="save-create" data-back-url="<?php echo $add; ?>" data-url="<?php echo $this->url($save); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
    <?php endif; ?>

    <?php if (isset($options) && $options == true): ?>
    <button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
    <?php endif; ?>

    <?php if (isset($cancel)): ?>
    <button data-button="cancel" data-url="<?php echo $cancel; ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
    <?php endif; ?>
</div>