<div class="modal fade" id="loader" tabindex="-1" aria-labelledby="loaderModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="loaderModalLabel"><?= $this->translate('Please wait') ?></h4>
        </div>

        <div class="modal-body">
            <div class="text-center">
                <img src="<?= $this->moduleAsset('images/ajax.gif', 'Cms') ?>" />
                <h2><?= $this->translate('Working') ?>...</h2>
            </div>
        </div>
        <div class="modal-footer"></div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

<div class="modal fade" id="errors-modal" tabindex="-1" aria-labelledby="errorsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="errorsModalLabel"><?= $this->translate('Warning') ?></h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body"></div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-bs-dismiss="modal"><?= $this->translate('OK') ?></button>
        </div>
     </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->  
</div>