<?php if (count($languages) > 1): ?>
<ul class="nav nav-tabs">
    <?php foreach ($languages as $index => $language): ?>
    <li class="nav-item">
        <a class="nav-link <?= $index == 0 ? 'active' : '' ?>" href="<?php printf('#language-%s', $language->getId()); ?>" role="tab" data-bs-toggle="tab">
            <i class="<?php printf('famfamfam-flag-%s', $language->getFlag()); ?>"></i> <?= $language->getName() ?>
        </a>
    </li>
    <?php endforeach; ?>
</ul>

<br />
<?php endif; ?>