<?php if (count($languages) > 1): ?>
<ul class="nav nav-tabs" role="tablist">
    <?php foreach ($languages as $index => $language): ?>
    <li role="presentation" class="<?php echo $index == 0 ? 'active' : null; ?>"><a href="<?php printf('#language-%s', $language->getId()); ?>" role="tab" data-toggle="tab"><i class="<?php printf('famfamfam-flag-%s', $language->getFlag()); ?>"></i> <?php echo $language->getName(); ?></a></li>
    <?php endforeach; ?>
</ul>

<br />
<?php endif; ?>
