<?php

/**
 * Shared menu button partial
 */

defined('KRYSTAL') or die;

?>

<?php if (isset($items)): ?>
<div class="dropdown">
  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
    <?php $this->show('Menu'); ?> <span class="caret"></span>
    <?php if (isset($notifications) && $notifications > 0): ?>
    (<?= $notifications; ?>)
    <?php endif; ?>
  </button>

  <div class="dropdown-menu">
     <?php foreach ($items as $key => $value): ?>
         <?php if ($value == null): ?>
         <?php continue; ?>
         <?php endif; ?>

         <?php if ($key === null): ?>
         <div class="dropdown-divider"></div>
         <?php endif; ?>

         <?php if (!is_numeric($key) & is_array($value)): ?>
         <a class="dropdown-item" href="<?php echo $this->url($key); ?>">
             <?php isset($value['caption']) ? $this->show($value['caption']) : ''; ?>

             <?php if (isset($value['notifications']) && $value['notifications'] > 0): ?>
             <small class="text-danger"> (<?= $value['notifications']; ?>)</small>
             <?php endif; ?>
         </a>
         
         <?php else: ?>
         <a class="dropdown-item" href="<?php echo $this->url($key); ?>"> <?php $this->show($value); ?></a>

         <?php endif; ?>
         
         <?php if (is_numeric($key) && is_array($value)): ?>
         <div class="dropdown-header"><?php $this->show($key); ?></div>
             <?php foreach ($value as $subKey => $subValue): ?>
             <a class="dropdown-item" href="<?php echo $this->url($subKey); ?>"> <?php $this->show($subValue); ?></a>
             <?php endforeach; ?>
         <?php endif; ?>
     <?php endforeach; ?>

     <?php if (isset($actions['data'])): ?>
     <div class="dropdown-header"><?php $this->show('Actions'); ?></div>
         <?php if (!empty($actions['data'])): ?>

             <?php if (isset($actions['save'])): ?>
             <a class="dropdown-item" href="#" data-button="save-changes" data-url="<?php echo $this->url($actions['save']); ?>"><i class="fas fa-save"></i> <?php $this->show('Save changes'); ?></a>
             <?php endif; ?>

             <?php if (isset($actions['delete'])): ?>
             <a class="dropdown-item" href="#" data-button="remove-selected" data-url="<?php echo $this->url($actions['delete'], null); ?>"><i class="fas fa-trash"></i> <?php $this->show('Remove selected'); ?></a>
             <?php endif; ?>

          <?php else: ?>

             <?php if (isset($actions['save'])): ?>
             <a class="dropdown-item disabled"><i class="fas fa-save"></i> <?php $this->show('Save changes'); ?></a>
             <?php endif; ?>

             <?php if (isset($actions['delete'])): ?>
             <a class="dropdown-item disabled"><i class="fas fa-trash"></i> <?php $this->show('Remove selected'); ?></a>
             <?php endif; ?>

         <?php endif; ?>
         
     <?php endif; ?>
  </div>
</div>
<?php endif; ?>