<?php

/**
 * Shared menu button partial
 */

?>

<?php if (isset($items)): ?>
<div class="dropdown">
  <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">
    <?= $this->translate('Menu') ?>
    <?php if (isset($notifications) && $notifications > 0): ?>
    (<?= $notifications ?>)
    <?php endif; ?>
  </button>

  <div class="dropdown-menu">
     <?php foreach ($items as $key => $value): ?>
         <?php if ($value === null): ?>
         <?php continue; ?>
         <?php endif; ?>

         <?php if ($key === null): ?>
         <div class="dropdown-divider"></div>
         <?php endif; ?>

         <?php if (!is_numeric($key) && is_array($value)): ?>
         <a class="dropdown-item" href="<?= $this->url($key) ?>">
             <?php if (isset($value['icon'])): ?>
             <i class="<?= $value['icon'] ?>"></i> &nbsp;
             <?php endif; ?>

             <?= isset($value['caption']) ? $this->translate($value['caption']) : '' ?>

             <?php if (isset($value['notifications']) && $value['notifications'] > 0): ?>
             <small class="text-danger"> (<?= $value['notifications'] ?>)</small>
             <?php endif; ?>
         </a>

         <?php else: ?>
         <a class="dropdown-item" href="<?= $this->url($key) ?>"> <?= $this->translate($value) ?></a>

         <?php endif; ?>

         <?php if (isset($value['title'], $value['items']) && is_array($value['items'])): ?>
         <div class="dropdown-header"><?= $this->translate($value['title']) ?></div>
             <?php foreach ($value['items'] as $subKey => $subValue): ?>
             <a class="dropdown-item" href="<?= $this->url($subKey) ?>"> <?= $this->translate($subValue) ?></a>
             <?php endforeach; ?>
         <?php endif; ?>
     <?php endforeach; ?>

     <?php if (isset($actions['data'])): ?>
     <div class="dropdown-header"><?= $this->translate('Actions') ?></div>
         <?php if (!empty($actions['data'])): ?>

             <?php if (isset($actions['save'])): ?>
             <a class="dropdown-item" href="#" data-button="save-changes" data-url="<?= $this->url($actions['save']) ?>"><i class="fas fa-save"></i> <?= $this->translate('Save changes') ?></a>
             <?php endif; ?>

             <?php if (isset($actions['delete'])): ?>
             <a class="dropdown-item" href="#" data-button="remove-selected" data-url="<?= $this->url($actions['delete'], null) ?>"><i class="fas fa-trash"></i> <?= $this->translate('Remove selected') ?> <span class="selected-counter"></span></a>
             <?php endif; ?>

          <?php else: ?>

             <?php if (isset($actions['save'])): ?>
             <a class="dropdown-item disabled"><i class="fas fa-save"></i> <?= $this->translate('Save changes') ?></a>
             <?php endif; ?>

             <?php if (isset($actions['delete'])): ?>
             <a class="dropdown-item disabled"><i class="fas fa-trash"></i> <?= $this->translate('Remove selected') ?></a>
             <?php endif; ?>

         <?php endif; ?>

     <?php endif; ?>
  </div>
</div>
<?php endif; ?>