<?php

/**
 * Shared table generator
 */

use Krystal\Widget\GridView\GridViewWidget;

$responsive = true; // By default assume responsive

?>

<?php if (isset($caption)): ?>
<?php $this->loadPartial('items-per-page', ['caption' => $caption]); ?>
<?php endif; ?>

<?php if (isset($batch)): ?>
<form>
<?php endif; ?>

    <?php if ($responsive): ?>
    <div class="table-responsive">
    <?php endif; ?>
        <?= $this->widget(new GridViewWidget($rows, [
            'batch' => isset($batch) && $batch === true,
            'pk' => 'id',
            'tableClass' => 'table table-hover table-bordered',
            'columns' => $columns,
            'actions' => $actions,
            'rowAttributes' => isset($rowAttributes) ? $rowAttributes : []
        ])); ?>

        <?php if (empty($rows)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="bi bi-x-circle"></i> <?= $this->translate('No data'); ?></h2>
        </div>
        <?php endif; ?>

    <?php if (isset($responsive)): ?>
    </div>
    <?php endif; ?>
    
<?php if (isset($batch)): ?>
</form>
<?php endif; ?>

<?php if (!(isset($pagination) && $pagination === false)): ?>
<?php $this->loadPartial('paginator'); ?>
<?php endif; ?>