<form>
	<div class="well clearfix">
		
		<input type="hidden" name="id" value="<?php echo $banner->getId(); ?>" />
		<input type="hidden" name="image" value="<?php echo $banner->getImage(); ?>" >
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
				<input type="text" name="name" class="form-control" placeholder="<?php $this->show('Banner name'); ?>" value="<?php echo $banner->getName(); ?>"/>
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('URL Link'); ?></label>
			<div class="col-lg-10">
				<input type="text" name="link" class="form-control" placeholder="<?php $this->show('URL link when clicked'); ?>" value="<?php echo $banner->getLink(); ?>" />
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('File'); ?></label>
			<div class="col-lg-10">
				
				<?php //TODO?: ?>
				
				<input type="file" name="file" />
			</div>
		</div>
	</div>
	
	<?php if (!isset($editing)): ?>
	<button data-button="add" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> <?php $this->show('Add'); ?></button>
	
	<?php else: ?>
	<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	
	<?php endif; ?>
	
	<button class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
</form>
