<?php

use Krystal\Form\Widget\CheckBoxWidget;

?>

<form>
	<div class="well clearfix">
		
		<input type="hidden" name="advice[id]" value="<?php echo $advice->getId(); ?>" />
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
			<div class="col-lg-10">
				<input type="text" name="advice[title]" class="form-control" placeholder="<?php $this->show('Advice title'); ?>" value="<?php echo $advice->getTitle(); ?>" />
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Content'); ?></label>
			<div class="col-lg-10">
				<textarea name="advice[content]"><?php echo $advice->getContent(); ?></textarea>
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
			<div class="col-lg-10">
				<?php echo CheckBoxWidget::render(array('name' => 'advice[published]', 'class' => 'form-control'), $advice->getPublished()); ?>
			</div>
		</div>
		
	</div>
	
	<?php if ($advice->getId()): ?>
	
	<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
	
	<?php else: ?>

	<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
	
	<?php endif; ?>
	
	<button data-button="cancel" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
	
</form>
