<form>
	<div class="well clearfix">
		
		<input type="hidden" name="id" value="<?php echo $category->getId(); ?>" />
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="name" value="<?php echo $category->getName(); ?>" class="form-control" placeholder="<?php $this->show('Category name'); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Class'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="class" value="<?php echo $category->getClass(); ?>" class="form-control" placeholder="<?php $this->show('Class to simplify rendering'); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Width'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="number" name="width" value="<?php echo $category->getWidth(); ?>" class="form-control" placeholder="<?php $this->show('Desired width for slide images'); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Height'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="number" name="height" value="<?php echo $category->getHeight(); ?>" class="form-control" placeholder="<?php $this->show('Desired height for slide images'); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
	</div>
	
	
	<?php if (!$category->getId()): ?>
	<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	
	<?php else: ?>
	<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	
	<?php endif; ?>
	<button data-button="cancel" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
	
</form>
