<?php

use Krystal\Form\Widget\CheckBoxWidget;
use Krystal\Form\Widget\DropdownWidget;

?>

<?php if (!empty($categories)): ?>



<form>

	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#image" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Image'); ?></a></li>
		<li role="presentation"><a href="#options" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Options'); ?></a></li>
	</ul>
	
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane fade in active" id="image" role="tabpanel">
			<div class="well clearfix">
				
				<input type="hidden" name="image[id]" value="<?php echo $image->getId(); ?>" />
				<input type="hidden" name="image[image]" value="<?php echo $image->getCover(); ?>" />
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
							<input type="text" name="image[name]" class="form-control" placeholder="<?php $this->show("Slider's name. When empty, then is taken from a filename"); ?>" value="<?php echo $image->getName(); ?>" />
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Category'); ?></label>
					<div class="col-lg-10">
						<?php echo DropdownWidget::render(array('name' => 'image[category_id]', 'class' => 'form-control'), $categories, $image->getCategoryId(), false); ?>
					</div>
				</div>
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Image'); ?></label>
					<div class="col-lg-10">
						
						<?php if ($image->getCover() != ''): ?>
						<img class="img-responsive" src="<?php echo $image->getImageBag()->getUrl('400x200'); ?>" />
						
						<?php else: ?>
						<img data-image="preview" />
						
						<?php endif; ?>
						
						<br />
						<br />
						
						<input type="file" name="file" accept="image/x-png, image/gif, image/jpeg" />
					</div>
				</div>
				
			</div>
		</div>

		
		<div class="tab-pane" id="options" role="tabpanel">
			
			<div class="well">
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
							<input type="number" name="image[order]" class="form-control" value="<?php echo $image->getOrder(); ?>" placeholder="<?php $this->show('Image sort order'); ?>" />
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
					<div class="col-lg-10">
						<textarea name="image[description]" class="form-control" placeholder="<?php $this->show('Image description'); ?>"><?php echo $image->getDescription(); ?></textarea>
					</div>
				</div>
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Link'); ?></label>
					<div class="col-lg-10">
						<input type="text" name="image[link]" class="form-control" placeholder="<?php $this->show('Link to be opened when clicking on the slider'); ?>" value="<?php echo $image->getLink(); ?>" />
					</div>
				</div>
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
					<div class="col-lg-10">
						<?php echo CheckBoxWidget::render(array(

							'name' => 'image[published]', 
							'class' => 'form-control'

						), $image->getPublished()); ?>
					</div>
				</div>
			</div>
		</div>
		
		
	</div>
	
	<?php if (!$image->getId()): ?>
	<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-upload" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Upload new'); ?></button>
	<?php else: ?>
	
	<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-upload" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Upload new'); ?></button>
	<?php endif; ?>
	
	<button data-button="cancel" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
	
</form>

<?php else: ?>

<div class="well">

	<div class="center-block">
		<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('In order to upload a slider, you need to create at least one category'); ?></h2>
	</div>

</div>

<?php endif; ?>