
<?php $this->show('Hello there!'); ?>

<?php $this->show('You have a new order from'); ?>: <?php echo $input['name']; ?>

<?php $this->show('Contact information'); ?>:

<?php $this->show('Phone'); ?>: <?php echo $input['phone']; ?>

<?php $this->show('Address'); ?>: <?php echo $input['address']; ?>

<?php if (!empty($input['comment'])): ?>
------------------------------------------

<?php $this->show('Comments'); ?>:

<?php echo $input['comment']; ?>
<?php endif; ?>

------------------------------------------

<?php $this->show('Delivery type'); ?>: <?php echo $input['delivery']; ?>

<?php foreach ($basketManager->getProducts() as $product): ?>

<?php $this->show('Product'); ?>: <?php echo $product->getTitle(); ?>

<?php $this->show('Quantity'); ?> : <?php echo $product->getQty(); ?>

<?php $this->show('Sub-total price'); ?>: <?php echo $product->getSubTotalPrice(); ?>

<?php endforeach; ?>

------------------------------------------

<?php $this->show('Total quantity of all products'); ?>: <?php echo $basketManager->getTotalQuantity(); ?>

<?php $this->show('Total price'); ?>: <?php echo $basketManager->getTotalPrice(); ?>
