
<p><?php $this->show('Hello there!'); ?></p>
<p><?php $this->show('You have a new order from'); ?>: <?php echo $input['name']; ?></p>
<p><?php $this->show('Contact information'); ?>:</p>
<p><?php $this->show('Phone'); ?>: <?php echo $input['phone']; ?></p>
<p><?php $this->show('Address'); ?>: <?php echo $input['address']; ?></p>
<p><?php $this->show('Delivery type'); ?>: <?php echo strip_tags($input['delivery']); ?></p>

<?php if (!empty($input['comment'])): ?>
<p><?php $this->show('Comments'); ?>:</p>
<?php echo $input['comment']; ?>
<?php endif; ?>

<br />

<p><?php $this->show('Ordered products'); ?>: </p>

<?php foreach ($basketManager->getProducts() as $product): ?>
<br />
<p><?php $this->show('Product'); ?>: <?php echo $product->getTitle(); ?></p>
<p><?php $this->show('Quantity'); ?> : <?php echo $product->getQty(); ?></p>
<p><?php $this->show('Sub-total price'); ?>: <?php echo $product->getSubTotalPrice(), ' ', $currency; ?></p>
<br />
<?php endforeach; ?>

<br />
<hr />

<p><?php $this->show('Total quantity of all products'); ?>: <?php echo $basketManager->getTotalQuantity(); ?></p>
<p><?php $this->show('Total price'); ?>: <?php echo $basketManager->getTotalPrice(), ' ', $currency; ?></p>
