<?php

use Krystal\Form\Element;

?>

<?php if (isset($paginator) && $paginator->hasPages()): ?>

<div class="per-page-container">
	<h4 class="inline"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show($caption); ?> 
	<?php if ($paginator->getSummary() != 0): ?>
	<small> (<?php $this->show('Displayed'); ?> <?php echo $paginator->getSummary(); ?> <?php $this->show('of'); ?> <?php echo $paginator->getTotalAmount(); ?>) </small>
	<?php endif; ?>
	</h4>
	
	<div class="pull-right">
		<span class="help-block inline"><?php $this->show('Items per page'); ?>: </span>
        <?php echo Element::select(null, $ppc->getPerPageCountValues(), $ppc->getPerPageCount(), array('data-button' => 'per-page-changer')); ?>
	</div>
	
	<div class="clearfix"></div>
	
</div>

<?php else: ?>

<br />

<?php endif; ?>
