<?php

use Krystal\Form\Element;

?>

<form class="card" autocomplete="off">
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="nav-item"><a class="nav-link active" href="#common" role="tab" data-bs-toggle="tab"><i class="fas fa-home fa-fw"></i> <?= $this->translate('Common'); ?></a></li>
		<li role="presentation" class="nav-item"><a class="nav-link" href="#maintenance" role="tab" data-bs-toggle="tab"><i class="fas fa-life-ring"></i> <?= $this->translate('Maintenance'); ?></a></li>
		<li role="presentation" class="nav-item"><a class="nav-link" href="#mail" role="tab" data-bs-toggle="tab"><i class="fas fa-envelope"></i> <?= $this->translate('Mail'); ?></a></li>
	</ul>

	<div class="tab-content pt-3">
		<div class="tab-pane fade show active" id="common" role="tabpanel">
            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Keep the track of latest activity'); ?></label>
                <div class="col-lg-10">
                    <div class="form-check">
                        <?= Element::checkbox('config[keep_track]', $config->getKeepTrack(), ['class' => 'form-check-input']); ?>
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Email for notifications'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?= Element::text('config[notification_email]', $config->getNotificationEmail(), ['class' => 'form-control']); ?>
                        <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                    </div>
                    <div class="form-text"><?= $this->translate('This email is used as an address for sending notifications'); ?></div>
                </div>
            </div>
		</div>
		
		<!--Maintenance tab-->
		<div class="tab-pane fade" id="maintenance" role="tabpanel">
            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Site is down for maintenance'); ?></label>
                <div class="col-lg-10">
                    <div class="form-check">
                        <?= Element::checkbox('config[site_enabled]', $config->getSiteEnabled(), ['class' => 'form-check-input']); ?>
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Message'); ?></label>
                <div class="col-lg-10">
                    <?= Element::textarea('config[site_down_reason]', $config->getSiteDownReason(), ['data-wysiwyg' => 'true']); ?>
                </div>
            </div>
		</div>
		<!--/Maintenance tab-->
		
		<!--Mail-->
		<div class="tab-pane fade" id="mail" role="tabpanel">
            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate("Try using server's native mailer"); ?></label>
                <div class="col-lg-10">
                    <div class="form-check">
                        <?= Element::checkbox('config[use_smtp_driver]', $config->getUseSmtpDriver(), ['class' => 'form-check-input']); ?>
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Domain'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?= Element::text('config[domain]', $config->getDomain(), ['class' => 'form-control']); ?>
                        <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                    </div>
                    <div class="form-text"><?= $this->translate('Default domain can be overriden if neccesary'); ?></div>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Secure layer'); ?> (SSL/TLS)</label>
                <div class="col-lg-10">
                    <?= Element::select('config[smtp_secure_layer]', $config->getSmtpSecureLayers(), $config->getSmtpSecureLayer(), ['class' => 'form-select']); ?>
                    <div class="form-text"><?= $this->translate('If your provided requires secure layer, choice required one here'); ?></div>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Host'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?= Element::text('config[smtp_host]', $config->getSmtpHost(), ['class' => 'form-control']); ?>
                        <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                    </div>
                    <div class="form-text"><?= $this->translate('STMP host might look like as smtp.yourserver.com'); ?></div>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Username'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?= Element::text('config[smtp_username]', $config->getSmtpUsername(), ['class' => 'form-control']); ?>
                        <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                    </div>
                    <div class="form-text"><?= $this->translate("Account's username, which usually represents your login"); ?></div>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Password'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?= Element::text('config[smtp_password]', $config->getSmtpPassword(), ['class' => 'form-control']); ?>
                        <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                    </div>
                    <div class="form-text"><?= $this->translate("Account's password"); ?></div>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Port'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?= Element::number('config[smtp_port]', $config->getSmtpPort(), ['class' => 'form-control']); ?>
                        <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                    </div>
                    <div class="form-text"><?= $this->translate("SMTP server's port. In most cases its 25"); ?></div>
                </div>
            </div>
		</div>
		<!--/Mail-->
	</div>

    <div class="actions mt-3">
        <button data-button="save" data-url="<?= $this->url('Cms:Admin:Tweaks@saveAction'); ?>" class="btn btn-primary"><i class="bi bi-save"></i> <?= $this->translate('Save'); ?></button>
        <button data-button="cancel" data-url="<?= $this->url('Cms:Admin:Dashboard@indexAction'); ?>" class="btn btn-secondary"><i class="bi bi-folder2-open"></i> <?= $this->translate('Cancel'); ?></button>
    </div>
</form>