<?php

use Cms\Service\ThemeService;

?>

<div class="p-4 mb-4 bg-light rounded-3">
    <h2><?= $this->translate('Dashboard'); ?></h2>
    <p class="lead"><?= $this->translate('Welcome to Bono. The best choice for managing your web-site!'); ?></p>
    <p><?= $this->translate('The management of your site gets done via installed modules.'); ?></p>
</div>

<div class="row">
    <div class="col-6">
        <div class="card mb-3">
            <div class="card-body">
                <p><?= $this->translate('Quick links'); ?></p>

                <ul class="dashboard-quick-links">
                    <?php foreach($bookmarks as $bookmark): ?>
                    <li><a href="<?= $this->url($bookmark['controller']); ?>"><i class="<?= $bookmark['icon']; ?>"></i> <?= $this->translate($bookmark['name']); ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>

        <div class="card mb-3">
            <div class="card-body">
                <p><?= $this->translate('System information'); ?></p>

                <table class="table">
                    <?php foreach ($systemInfo as $name => $value): ?>
                    <tr>
                        <td><?= $this->translate($name); ?></td>
                        <td><?= $value; ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>

    <div class="col-6">
        <div class="card mb-3">
            <div class="card-body">
                <p><?= $this->translate('Recent activity'); ?></p>

                <table class="table">
                    <?php foreach ($activity as $item): ?>
                    <tr>
                        <td><?= $this->translate($item->getComment(), $item->getPlaceholder()); ?> <span class="text-muted">(<?= $this->translate($item->getModule()); ?>)</span></td>
                    </tr>
                    <?php endforeach; ?>
                </table>

                <p class="lead">
                    <a class="btn btn-primary btn-lg" href="<?= $this->url('Cms:Admin:History@indexAction'); ?>" role="button"><?= $this->translate('View all'); ?></a>
                </p>
            </div>
        </div>
    </div>
</div>