<?php defined('KRYSTAL') or die; ?>
<aside class="clearfix">
 <h5><i class="fa fa-home fa-2x"></i> <?php $this->show('Control panel'); ?></h5>
 <ul>
  <?php foreach ($utilites as $utility): ?>
  <li>
	<a href="<?php echo $this->url($utility['route']); ?>" data-toggle="tooltip" data-placement="bottom" data-original-title="<?php echo htmlentities($this->translate($utility['description'])); ?>">
    <img src="<?php echo $this->moduleAsset($utility['icon'], 'Cms'); ?>" />
	<?php if ($utility['name'] == 'Notifications' && $notifications > 0): ?>
	<label class="urgent"><?php $this->show($utility['name']); ?> (<?php echo $notifications; ?>)</label>
	<?php else: ?>
	<label><?php $this->show($utility['name']); ?></label>
	<?php endif; ?>
   </a>
 </li>
 <?php endforeach; ?>
 </ul>
</aside>

<aside class="clearfix">
  <h5><i class="fa fa-plug fa-2x"></i> <?php $this->show('Installed modules'); ?> <small>(<?php echo count($modulesConfiguration); ?>)</small></h5>
  <ul>
	<?php foreach ($modulesConfiguration as $module): ?>
	<li>
	 <a href="<?php echo call_user_func_array(array($this, 'url'), (array) $module['route']); ?>" data-toggle="tooltip" data-placement="bottom" data-original-title="<?php echo htmlentities($this->translate($module['description'])); ?>">
     <img src="<?php echo sprintf('/module/%s/Assets/%s.png', $module['name'], strtolower($module['name'])); ?>" /> <label><?php isset($module['caption']) and $this->show($module['caption']); ?></label>
	 </a>
	</li>
	 <?php endforeach; ?>
	</ul>
</aside>