<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

?>

<?php if (!empty($records) && $extendedMode): ?>
<div class="btn-toolbar">
    <div class="btn-group me-2">
        <button data-message="<?= $this->translate('Do you really want to clear the history?'); ?>" data-button="remove" data-url="<?= $this->url('Cms:Admin:History@clearAction'); ?>" class="btn btn-primary"><i class="bi bi-fire"></i> <?= $this->translate('Clear all'); ?></button>
    </div>
</div>
<?php endif; ?>

<div class="card">
    <?php $this->loadPartial('items-per-page', ['caption' => 'History']); ?>

    <div class="table-responsive">
        <?= $this->widget(new GridViewWidget($records, [
            'tableClass' => 'table table-hover table-bordered table-striped',
            'columns' => [
                [
                    'column' => 'id',
                    'label' => '#',
                    'attributes' => [
                        'class' => 'text-muted text-center'
                    ]
                ],

                [
                    'column' => 'timestamp',
                    'label' => 'Date and time',
                    'value' => function($record){
                        return date('d.m.y H:i:s', $record->getTimestamp());
                    }
                ],

                [
                    'column' => 'comment',
                    'attributes' => [
                        'class' => null
                    ],
                    'value' => function($record){
                        return $this->translate($record->getComment(), $record->getPlaceholder());
                    }
                ],

                [
                    'column' => 'module',
                    'translateable' => true
                ],

                [
                    'column' => 'user_id',
                    'label' => 'User',
                    'translateable' => true,
                    'value' => function($record) use ($userManager){
                        $user = $userManager->fetchNameById($record->getUserId());

                        if ($user){
                            return $user;
                        } else {
                            return 'User no longer exists';
                        }
                    }
                ]
            ]
        ])); ?>

        <?php if (empty($records)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="bi bi-x-circle"></i> <?= $this->translate('No records'); ?></h2>
        </div>
        <?php endif; ?>
    </div>

    <?php $this->loadPartial('paginator'); ?>
</div>