<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<?php if (!empty($records) && $extendedMode): ?>
<div class="btn-toolbar">
    <div class="btn-group mr-2">
        <button data-message="<?php $this->show('Do you really want to clear the history?'); ?>" data-button="remove" data-url="<?php echo $this->url('Cms:Admin:History@clearAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-fire"></i> <?php $this->show('Clear all'); ?></button>
    </div>
</div>
<?php endif; ?>

<div class="card">
    <?php $this->loadPartial('items-per-page', array('caption' => 'History')); ?>

    <div class="table-responsive">
        <?= $this->widget(new GridViewWidget($records, array(
            'tableClass' => 'table table-hover table-bordered table-striped',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#',
                    'attributes' => array(
                        'class' => 'text-muted text-center'
                    )
                ),

                array(
                    'column' => 'timestamp',
                    'label' => 'Date and time',
                    'value' => function($record){
                        return date('d.m.y H:i:s', $record->getTimestamp());
                    }
                ),

                array(
                    'column' => 'comment',
                    'attributes' => array(
                        'class' => null
                    ),
                    'value' => function($record){
                        return $this->translate($record->getComment(), $record->getPlaceholder());
                    }
                ),

                array(
                    'column' => 'module',
                    'translateable' => true
                ),

                array(
                    'column' => 'user_id',
                    'label' => 'User',
                    'translateable' => true,
                    'value' => function($record) use ($userManager){
                        $user = $userManager->fetchNameById($record->getUserId());

                        if ($user){
                            return $user;
                        } else {
                            return 'User no longer exists';
                        }
                    }
                )
            )
        ))); ?>

        <?php if (empty($records)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No records'); ?></h2>
        </div>
        <?php endif; ?>
    </div>

    <?php $this->loadPartial('paginator'); ?>
</div>