<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>
<!DOCTYPE html>
<html>
<head>
 <meta charset="utf-8" />
 <meta name="csrf-token" content="<?php echo $csrfToken; ?>" />
 <title><?php $this->show('Enter the system'); ?></title>
 <?php foreach ($this->getPluginBag()->getStylesheets() as $stylesheet): ?>
 <link rel="stylesheet" media="screen" href="<?php echo $stylesheet; ?>"  />
 <?php endforeach; ?>
</head>
<body>

<section class="bg-light vh-100">
    <div class="container h-100">
        <div class="h-100 d-flex flex-column align-items-start justify-content-center">
            <div class="row justify-content-center w-100">
                <div class="col-lg-5">
                    <!-- Box -->
                    <div class="bg-white shadow-lg p-5">
                        <span class="d-flex align-items-center justify-content-center mx-auto text-white rounded-circle bg-primary login-icon">
                            <i class="fas fa-lock"></i>
                        </span>
                        
                        <h3 class="text-center mb-4 mt-3"><?= $this->translate('Administration panel'); ?></h3>
                        
                        <form autocomplete="off" role="form" data-success-url="<?= $this->url('Cms:Admin:Dashboard@indexAction'); ?>" data-submit-url="<?= $this->url('Cms:Admin:Auth@loginAction'); ?>">
                            <div class="form-group">
                                <label><?php $this->show('Login'); ?></label>
                                <?= Element::text('login', null, ['class' => 'form-control form-control-lg']); ?>
                            </div>

                            <div class="form-group">
                                <label><?php $this->show('Password'); ?></label>
                                <?= Element::password('password', null, ['class' => 'form-control form-control-lg']); ?>
                            </div>

                            <div class="form-group">
                               <div class="custom-control custom-checkbox">
                                  <?= Element::checkbox('remember', true, ['class' => 'custom-control-input']); ?>
                                  <label class="custom-control-label"><?= $this->translate('Keep me signed in'); ?></label>
                               </div>
                            </div>

                            <?php if ($captcha === true): ?>
                            <div class="captcha-container">
                                <span class="label label-danger"><?= $this->translate('Please confirm that you are not a bot'); ?></span>

                                <div class="form-group">
                                    <label for="inputCaptcha" class="control-label"></label>
                                        <a href="#" title="<?= $this->translate('Click to refresh'); ?>" data-captcha="button-refresh">
                                        <img data-captcha="image" src="<?= $this->url('Site:Main@captchaAction', null); ?>" />
                                    </a>
                                </div>

                                <div class="form-group">
                                    <label for="inputCaptcha" class="control-label"></label>
                                    <input type="text" class="form-control" name="captcha" placeholder="<?= $this->translate('Type here'); ?>" />
                                </div>
                            </div>
                            <?php endif; ?>

                            <div class="form-group">
                                <button disabled type="submit" class="btn btn-primary btn-lg w-100"><?= $this->translate('Sign In'); ?></button>
                            </div>
                        </form>
                    </div>
                    <!-- End of box -->
                </div>
            </div>
        </div>
    </div>
</section>

<?php $this->loadPartial('ajax'); ?>

<?php foreach ($this->getPluginBag()->getScripts() as $script): ?>
<script src="<?php echo $script; ?>"></script>
<?php endforeach; ?>  

</body>
</html>