<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>
<!DOCTYPE html>
<html>
<head>
 <meta charset="utf-8" />
 <meta name="csrf-token" content="<?php echo $csrfToken; ?>" />
 <title><?php $this->show('Enter the system'); ?></title>
 <?php foreach ($this->getPluginBag()->getStylesheets() as $stylesheet): ?>
 <link rel="stylesheet" media="screen" href="<?php echo $stylesheet; ?>"  />
 <?php endforeach; ?>
</head>
<body>
<section class="login">
    <div class="login-overlay">
        <div class="login-form">
            <span class="caption"><?php $this->show('Administration panel'); ?></span>
            <form autocomplete="off" role="form" data-success-url="<?php echo $this->url('Cms:Admin:Dashboard@indexAction'); ?>" data-submit-url="<?php echo $this->url('Cms:Admin:Auth@loginAction'); ?>">
                <div class="form-group">
                    <label for="user"><?php $this->show('Login'); ?></label>
                    <?= Element::text('login', null, array('id' => 'user')); ?>
                </div>

                <div class="form-group">
                    <label for="pass"><?php $this->show('Password'); ?></label>
                    <?= Element::password('password', null, array('id' => 'pass')); ?>
                </div>

                <div class="form-group">
                   <div class="custom-control custom-checkbox">
                      <?= Element::checkbox('remember', true, array('class' => 'custom-control-input', 'id' => 'remember')); ?>
                      <label class="custom-control-label" for="remember"><?php $this->show('Keep me signed in'); ?></label>
                   </div>
                </div>

                <?php if ($captcha === true): ?>
                <div class="captcha-container">
                    <span class="label label-danger"><?php $this->show('Please confirm that you are not a bot'); ?></span>

                    <div class="form-group">
                        <label for="inputCaptcha" class="control-label"></label>
                        <div class="col-lg-12">
                            <a href="#" title="<?php $this->show('Click to refresh'); ?>" data-captcha="button-refresh"><img data-captcha="image" src="<?php echo $this->url('Site:Main@captchaAction', null); ?>" /></a>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputCaptcha" class="control-label"></label>
                        <div class="col-lg-12">
                            <input type="text" class="form-control" name="captcha" placeholder="<?php $this->show('Type here'); ?>" />
                        </div>
                    </div>
                </div>
                <?php endif; ?>

                <div class="form-group">
                    <button class="btn btn-primary btn-lg"><?php $this->show('Sign In'); ?></button>
                </div>
            </form>
        </div>
	</div>
</section>

<?php $this->loadPartial('ajax'); ?>

<?php foreach ($this->getPluginBag()->getScripts() as $script): ?>
<script src="<?php echo $script; ?>"></script>
<?php endforeach; ?>  

</body>
</html>