<?php defined('KRYSTAL') or die; ?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="#" data-button="module-install" data-url="<?php echo $this->url('Cms:Admin:Themes@tweakAction'); ?>" title="<?php $this->show('Click to Install a module from ZIP archive'); ?>"><i class="glyphicon glyphicon-wrench"></i> <?php $this->show('Install a module');?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Cms:Admin:ModuleManager@deleteManyAction'); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
	  </ul>
      
      <input type="file" name="module" accept=".zip" class="hidden" />
	</div>
</div>

<h2 class="page-header"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Modules'); ?> <span class="text-muted">(<?php echo count($modules); ?>)</span></h2>

<div class="table-responsive">
    <form>
        <table class="table table-hover table-bordered table-striped table-condensed">
            <thead>
                <tr>
                    <th class="text-center">
                        <?php if (!empty($modules)): ?>
                        <input type="checkbox" />
                        <?php endif; ?>
                    </th>
                    <th class="text-center"><?php $this->show('Icon'); ?></th>
                    <th class="text-center"><?php $this->show('Name'); ?></th>
                    <th class="text-center"><?php $this->show('Description'); ?></th>
                </tr>
            </thead>
            
            <?php if (!empty($modules)): ?>
            <tbody>
                <?php foreach ($modules as $module): ?>
                <tr>
                    <td class="text-center">
                        <?php if (!$moduleManager->isCoreModule($module['name'])): ?>
                        <input type="checkbox" name="toDelete[<?php echo $module['name']; ?>]" />
                        <?php endif; ?>
                    </td>
                    <td class="text-center col-lg-2"><a href="<?php echo $this->url($module['route']); ?>"><i class="<?php echo $module['icon']; ?>"></i></a></td>
                    <td class="text-center"><?php $this->show($module['caption']); ?></td>
                    <td class="text-center"><?php $this->show($module['description']); ?></td>
                    <td class="text-center">
                        <?php if (!$moduleManager->isCoreModule($module['name'])): ?>
                        <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this module'); ?>" data-button="delete" href="#" data-url="<?php echo $this->url('Cms:Admin:ModuleManager@deleteAction', $module['name']); ?>"><i class="glyphicon glyphicon-remove"></i></a>
                        <?php endif; ?>
                    </td>
                </tr>
                
                <?php endforeach; ?>
            </tbody>
            <?php endif; ?>
        </table>
        
        <?php if (empty($modules)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No modules'); ?></h2>
        </div>
        <?php endif; ?>
    </form>
</div>