<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;
use Cms\View\Icon;
use Cms\Service\ThemeService;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="#" data-button="module-install" data-url="<?php echo $this->url('Cms:Admin:Themes@tweakAction'); ?>" title="<?php $this->show('Click to Install a module from ZIP archive'); ?>"><i class="glyphicon glyphicon-wrench"></i> <?php $this->show('Install a module');?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Cms:Admin:ModuleManager@deleteManyAction'); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
	  </ul>
      
      <input type="file" name="module" accept=".zip" class="hidden" />
	</div>
</div>

<h2 class="page-header"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Modules'); ?> <span class="text-muted">(<?php echo count($modules); ?>)</span></h2>

<form>
    <div class="table-responsive">
        <?= Grid::render($modules, array(
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'pk' => 'name',
            'batch' => true,
            'batchCallback' => function($module) use ($moduleManager){
                return !$moduleManager->isCoreModule($module['name']);
            },
            'columns' => array(
                array(
                    'column' => 'route',
                    'value' => function($module){
                        $image = Element::image(ThemeService::createIconPath($module['name']), array('class' => 'module-icon'));
                        $url = is_array($module['route']) ? call_user_func_array(array($this, 'url'), $module['route']) : $this->url($module['route']);

                        return Element::link($image, $url);
                    }
                ),

                array(
                    'column' => 'caption',
                    'translateable' => true
                ),

                array(
                    'column' => 'description',
                    'translateable' => true
                )
            ),

            'actions' => array(
                'remove' => function($module) use ($moduleManager){
                    if (!$moduleManager->isCoreModule($module['name'])) {
                        return Icon::remove(
                            $this->url('Cms:Admin:ModuleManager@deleteAction', $module['name']),
                            $this->translate('Remove this module')
                        );
                    } else {
                        return null;
                    }
                }
            )

        ), $this->translator); ?>

        <?php if (empty($modules)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No modules'); ?></h2>
        </div>
        <?php endif; ?>
    </div>
</form>
