<?php

use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

?>

<div class="card">
    <div class="card-header bg-light">
        <?php $this->loadPartial('items-per-page', ['caption' => 'Notifications']); ?>
    </div>

    <div class="card-body border-bottom">
        <div class="btn-toolbar justify-content-between align-items-center">
            <div>
                <?php if (!empty($notifications)): ?>
                <button data-button="remove" data-message="<?= $this->translate('Do you really want to clear all notifications?'); ?>" data-url="<?= $this->url('Cms:Admin:Notifications@clearAction'); ?>" class="btn btn-outline-danger btn-sm">
                    <i class="bi bi-trash-fill"></i> <?= $this->translate('Clear all'); ?>
                </button>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <?= $this->widget(new GridViewWidget($notifications, [
            'tableClass' => 'table table-hover table-striped mb-0',
            'columns' => [
                [
                    'column' => 'id',
                    'label' => '#',
                    'attributes' => [
                        'class' => 'text-muted text-center',
                        'style' => 'width: 50px;'
                    ]
                ],
                [
                    'column' => 'message',
                    'translateable' => true,
                    'attributes' => [
                        'class' => function($notification){
                            return $notification->getViewed() ? 'text-muted' : 'fw-bold';
                        }
                    ]
                ],
                [
                    'column' => 'date',
                    'label' => 'Date',
                    'value' => function($notification) use($dateFormat) {
                        return date($dateFormat, $notification->getTimestamp());
                    },
                    'attributes' => [
                        'class' => function($notification){
                            $class = 'text-center small';
                            return $notification->getViewed() ? $class . ' text-muted' : $class;
                        }
                    ]
                ],
            ],
            'actions' => [
                function($notification){
                    return Icon::remove(
                        $this->url('Cms:Admin:Notifications@deleteAction', $notification->getId()), 
                        $this->translate('Remove this notification')
                    );
                }
            ]
        ])); ?>
    </div>

    <?php if (empty($notifications)): ?>
    <div class="card-body py-5 text-center">
        <h2 class="text-muted"><i class="bi bi-bell-slash"></i> <?= $this->translate('No notifications'); ?></h2>
    </div>
    <?php endif; ?>

    <div class="card-footer bg-white">
        <?php $this->loadPartial('paginator'); ?>
    </div>
</div>