<?php $this->loadBlock('items-per-page', array('caption' => 'Notifications')); ?>

<form>
	<div class="table-responsive">
		<table class="table table-striped table-hover table-bordered">
			<thead>
				<tr>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Message'); ?></th>
					<th class="text-center"><?php $this->show('Date'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>
			
			<?php if (!empty($notifications)): ?>
			<tbody>
				<?php foreach ($notifications as $notification): ?>
				<tr>
					<?php if ($notification->getViewed()): ?>
					<td class="text-center text-muted"><?php echo $notification->getId(); ?></td>
					<td class="text-center text-muted"><?php $this->show($notification->getMessage()); ?></td>
					<td class="text-center text-muted"><?php echo date($dateFormat, $notification->getTimestamp()); ?></td>
					<?php else: ?>
					<td class="text-center text-muted"><?php echo $notification->getId(); ?></td>
					<td class="text-center"><?php $this->show($notification->getMessage()); ?></td>
					<td class="text-center"><?php echo date($dateFormat, $notification->getTimestamp()); ?></td>
					<?php endif; ?>
					<td class="text-center">
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this notification'); ?>" data-button="delete" data-url="<?php echo $this->url('Cms:Admin:Notifications@deleteAction', $notification->getId()); ?>" href="#" ><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
			<?php endif; ?>
		</table>
		
		<?php if (empty($notifications)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No notifications'); ?></h2>
		</div>
		<?php endif; ?>

		<?php if (!empty($notifications)): ?>
		<button data-button="remove" data-message="<?php $this->show('Do you really want to clear all notifications?'); ?>" data-url="<?php echo $this->url('Cms:Admin:Notifications@clearAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-fire"></i> <?php $this->show('Clear all'); ?></button>
		<?php endif; ?>
		
	</div>
</form>

<?php $this->loadBlock('paginator'); ?>
