<?php

use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="card">
    <?php $this->loadPartial('items-per-page', array('caption' => 'Notifications')); ?>

    <?php if (!empty($notifications)): ?>
    <div class="btn-toolbar">
        <div class="btn-group">
            <button data-button="remove" data-message="<?php $this->show('Do you really want to clear all notifications?'); ?>" data-url="<?php echo $this->url('Cms:Admin:Notifications@clearAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-fire"></i> <?php $this->show('Clear all'); ?></button>
        </div>
    </div>
    <?php endif; ?>

    <div class="table-responsive">
        <?= $this->widget(new GridViewWidget($notifications, [
            'tableClass' => 'table table-hover table-bordered table-striped',
            'columns' => [
                [
                    'column' => 'id',
                    'label' => '#'
                ],

                [
                    'column' => 'message',
                    'translateable' => true,
                    'attributes' => [
                        'class' => function($notification){
                            return $notification->getViewed() ? 'text-muted' : null;
                        }
                    ]
                ],

                [
                    'column' => 'date',
                    'value' => function($notification) use($dateFormat) {
                        return date($dateFormat, $notification->getTimestamp());
                    },
                    'attributes' => [
                        'class' => function($notification){
                            return $notification->getViewed() ? 'text-muted text-center' : 'text-center';
                        }
                    ]
                ],
            ],

            'actions' => [
                'remove' => function($notification){
                    return Icon::remove(
                        $this->url('Cms:Admin:Notifications@deleteAction', $notification->getId()), 
                        $this->translate('Remove this notification')
                    );
                }
            ]
        ])); ?>
    </div>

    <?php $this->loadPartial('paginator'); ?>
</div>
