<?php defined('KRYSTAL') or die; ?>
<?php echo '<?xml version="1.0" encoding="UTF-8"?>' . PHP_EOL ?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">

    <?php foreach ($urls as $url): ?>
    <url>
        <loc><?php echo $url; ?></loc>
        <changefreq>weekly</changefreq>
        <priority>1.0</priority>
    </url>
    <?php endforeach; ?>

</urlset>