<div class="alert alert-dismissable alert-info">
    <button type="button" class="close" data-dismiss="alert">x</button>
    <strong><i class="fa fa-info-circle"></i></span> <?php $this->show('In search engines, you can submit the following sitemap URLs'); ?></strong>
</div>

<div class="table-responsive">
    <table class="table table-hover table-bordered table-striped">
        <thead>
            <tr>
                <th class="text-center"><?php $this->show('Language'); ?></th>
                <th class="text-center"><?php $this->show('URL'); ?></th>
            </tr>
        </thead>
        
        <?php if (!empty($links)): ?>
        <tbody>
            <?php foreach($links as $language => $link): ?>
            <tr>
                <td class="text-center"><?php echo $language; ?></td>
                <td class="text-center"><a href="<?php echo $link; ?>" target="_blank"><?php echo $link; ?></a></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        <?php endif; ?>
    </table>
</div>