<?php

use Krystal\Form\Element;

?>

<div class="alert alert-dismissable alert-info">
    <strong><i class="fa fa-info-circle"></i></span> <?php $this->show('You can configure default options for SiteMap of your website'); ?></strong>
</div>

<div class="row">
    <div class="col-lg-9">
        <div class="card">
            <form class="form-horizontal">
              <fieldset>
                <legend><i class="fa fa-sitemap"></i> <?php $this->show('Sitemap configuration'); ?></legend>
                
                <div class="form-group">
                  <label for="select" class="col-lg-12 control-label"><?php $this->show('Priority'); ?></label>
                  <div class="col-lg-12">
                    <?php echo Element::select('sitemap_priority', $priorities, $priority, array('class' => 'form-control')); ?>
                  </div>
                </div>

                <div class="form-group">
                  <label for="select" class="col-lg-12 control-label"><?php $this->show('Change frequency'); ?></label>
                  <div class="col-lg-12">
                    <?php echo Element::select('sitemap_frequency', $this->translateArray($changefreqs), $changefreq, array('class' => 'form-control')); ?>
                  </div>
                </div>
                
                <div class="form-group">
                  <div class="col-lg-12">
                    <button data-button="save" data-url="<?php echo $this->url('Cms:Admin:SitemapLinks@saveAction'); ?>" class="btn btn-primary btn-sm mr-2"><i class="glyphicon glyphicon-ok"></i> <?php $this->show('Save'); ?></button>
                    <button data-button="save" data-url="<?php echo $this->url('Cms:Admin:SitemapLinks@robotsAction'); ?>" class="btn btn-primary btn-sm mr-2"><i class="fas fa-robot"></i> <?php $this->show('Synchronize Robots file'); ?></button>
                  </div>
                </div>
              </fieldset>
            </form>
        </div>
    </div>
</div>
