<?php

use Krystal\Form\Element;

?>

<div class="alert alert-dismissable alert-info">
    <button type="button" class="close" data-dismiss="alert">x</button>
    <strong><i class="fa fa-info-circle"></i></span> <?php $this->show('In search engines, you can submit the following sitemap URLs'); ?></strong>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <h2><i class="fa fa-sitemap"></i> <?php $this->show('Available site maps'); ?> <small class="text-muted">(<?php echo count($links); ?>)</small></h2>

            <div class="table-responsive">
                <table class="table table-hover table-bordered table-striped">
                    <thead>
                        <tr>
                            <th class="text-center"><?php $this->show('Language'); ?></th>
                            <th class="text-center"><?php $this->show('URL'); ?></th>
                        </tr>
                    </thead>
                    
                    <?php if (!empty($links)): ?>
                    <tbody>
                        <?php foreach($links as $language => $link): ?>
                        <tr>
                            <td class="text-center"><?php echo $language; ?></td>
                            <td class="text-center"><a href="<?php echo $link; ?>" target="_blank"><?php echo $link; ?></a></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                    <?php endif; ?>
                </table>
            </div>
        </div>
    </div>
    
    <div class="col-lg-6">
        <div class="card">
            <form class="form-horizontal">
              <fieldset>
                <legend><i class="glyphicon glyphicon-wrench"></i> <?php $this->show('Sitemap configuration'); ?></legend>
                
                <div class="form-group">
                  <label for="select" class="col-lg-12 control-label"><?php $this->show('Priority'); ?></label>
                  <div class="col-lg-12">
                    <?php echo Element::select('sitemap_priority', $priorities, $priority, array('class' => 'form-control')); ?>
                  </div>
                </div>

                <div class="form-group">
                  <label for="select" class="col-lg-12 control-label"><?php $this->show('Change frequency'); ?></label>
                  <div class="col-lg-12">
                    <?php echo Element::select('sitemap_frequency', $this->translateArray($changefreqs), $changefreq, array('class' => 'form-control')); ?>
                  </div>
                </div>
                
                <div class="form-group">
                  <div class="col-lg-12">
                    <button data-button="save" data-url="<?php echo $this->url('Cms:Admin:SitemapLinks@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-ok"></i> <?php $this->show('Save'); ?></button>
                    <button data-button="save" data-url="<?php echo $this->url('Cms:Admin:SitemapLinks@pingAction'); ?>" class="btn btn-warning"><i class="glyphicon glyphicon-globe"></i> <?php $this->show('Inform search engines about update'); ?></button>
                  </div>
                </div>
              </fieldset>
            </form>
        </div>
    </div>
</div>
