<?php defined('KRYSTAL') or die; ?>
<?php echo '<?xml version="1.0" encoding="UTF-8"?>' . PHP_EOL ?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">

    <?php foreach ($urls as $url): ?>
    <url>
        <loc><?= $url['location']; ?></loc>
        <changefreq><?= isset($url['changefreq']) ? $url['changefreq'] : $changefreq; ?></changefreq>
        <priority><?= isset($url['priority']) ? $url['priority'] : $priority; ?></priority>
        <?php if (isset($url['lastmod'])): ?>
        <lastmod><?= $url['lastmod']; ?></lastmod>
        <?php endif; ?>
    </url>
    <?php endforeach; ?>

</urlset>