<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Element;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
        
		 <?php if (!empty($themes)): ?>
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Cms:Admin:Themes@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes');?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Cms:Admin:Themes@deleteManyAction'); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes');?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php endif; ?>
		 
	  </ul>
	</div>
</div>

<h2 class="page-header"><?php $this->show('Themes'); ?></h2>

<form>
    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr>
                    <th class="text-center text-muted">#</th>
                    <th class="text-center"><?php $this->show('Cover'); ?></th>
                    <th class="text-center"><?php $this->show('Current'); ?></th>
                    <th class="text-center"><?php $this->show('Name'); ?></th>
                    <th class="text-center"><?php $this->show('Version'); ?></th>
                    <th class="text-center"><?php $this->show('Description'); ?></th>
                    <th class="text-center"><?php $this->show('Author'); ?></th>
                    <th class="text-center"><?php $this->show('Actions'); ?></th>
                </tr>
            </thead>
            
            <?php if (!empty($themes)): ?>
            <tbody>
                <?php foreach ($themes as $data): ?>
                <tr>
                    <td class="text-center text-muted">
                        <?php echo Element::checkbox(sprintf('toDelete[%s]', $data['theme']), null, array(), false); ?>
                    </td>
                    <td class="text-center">
                        <img class="img-reponsive" src="<?php echo $data['cover']; ?>" />
                    </td>
                    <td class="text-center">
                        <?php echo Element::radio('current', $data['theme'], $current == $data['theme']); ?>
                    </td>
                    <td class="text-center">
                        <?php if (isset($data['name'])): ?>
                        <?php echo $data['name']; ?>
                        <?php else: ?>
                        <em class="text-danger"><?php $this->show('No value'); ?></em>
                        <?php endif; ?>
                    </td>
                    <td class="text-center">
                        <?php if (isset($data['version'])): ?>
                        <?php echo $data['version']; ?>
                        <?php else: ?>
                        <em class="text-danger"><?php $this->show('No value'); ?></em>
                        <?php endif; ?>
                    </td>
                    <td class="text-center">
                        <?php if (isset($data['description'])): ?>
                        <?php $this->show($data['description']); ?>
                        <?php else: ?>
                        <em class="text-danger"><?php $this->show('No value'); ?></em>
                        <?php endif; ?>
                    </td>
                    <td class="text-center">
                        <?php if (isset($data['author'])): ?>
                        <?php echo $data['author']; ?>
                        <?php else: ?>
                        <em class="text-danger"><?php $this->show('No value'); ?></em>
                        <?php endif; ?>
                    </td>
                    <td class="text-center">
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this theme'); ?>" data-button="delete" data-url="<?php echo $this->url('Cms:Admin:Themes@deleteAction', $data['theme']); ?>" href="#" ><i class="glyphicon glyphicon-remove"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
            <?php endif; ?>
            
        </table>

        <?php if (empty($themes)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No themes'); ?></h2>
        </div>
        <?php endif; ?>
        
    </div>
</form>
