<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

?>

<div class="btn-toolbar mb-3">
    <div class="dropdown">
      <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">
        <i class="bi bi-list-ul"></i> <?= $this->translate('Menu'); ?>
      </button>

      <div class="dropdown-menu">
         <?php if (!empty($themes)): ?>
         <a class="dropdown-item" href="#" data-button="save-changes" data-url="<?= $this->url('Cms:Admin:Themes@tweakAction'); ?>"><i class="bi bi-save"></i> <?= $this->translate('Save changes');?></a>
         <a class="dropdown-item" href="#" data-button="remove-selected" data-url="<?= $this->url('Cms:Admin:Themes@deleteManyAction'); ?>"><i class="bi bi-x-circle"></i> <?= $this->translate('Remove selected'); ?></a>
         <?php else: ?>
         <a class="dropdown-item disabled"><i class="bi bi-save"></i> <?= $this->translate('Save changes');?></a>
         <a class="dropdown-item disabled"><i class="bi bi-x-circle"></i> <?= $this->translate('Remove selected'); ?></a>
         <?php endif; ?>
      </div>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h2 class="page-header"><i class="bi bi-list-ul"></i> <?= $this->translate('Themes'); ?> <span class="text-muted">(<?= count($themes); ?>)</span></h2>

        <form>
            <div class="table-responsive">
                <?= $this->widget(new GridViewWidget($themes, [
                    'batch' => true,
                    'pk' => 'theme',
                    'tableClass' => 'table table-hover table-bordered table-striped table-sm',
                    'columns' => [
                        [
                            'column' => 'cover',
                            'value' => function($theme){
                                return Element::image($theme['cover'], ['class' => 'img-fluid']);
                            }
                        ],

                        [
                            'column' => 'current',
                            'value' => function($theme) use ($current){
                                return Element::radio('current', $theme['theme'], $current == $theme['theme']);
                            }
                        ],

                        [
                            'column' => 'name'
                        ],

                        [
                            'column' => 'version'
                        ],

                        [
                            'column' => 'description'
                        ],

                        [
                            'column' => 'author'
                        ]
                    ],

                    'actions' => [
                        function($theme) use ($current){
                            // Don't let to remove current theme
                            if ($theme['theme'] !== $current) {
                                return Icon::remove(
                                    $this->url('Cms:Admin:Themes@deleteAction', $theme['theme']),
                                    $this->translate('Remove this theme')
                                );
                            } else {
                                return null;
                            }
                        }
                    ]
                ])); ?>

                <?php if (empty($themes)): ?>
                <div class="center-block">
                    <h2 class="text-center text-muted"><i class="bi bi-x-circle"></i> <?= $this->translate('No themes'); ?></h2>
                </div>
                <?php endif; ?>
            </div>
        </form>
    </div>
</div>