<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
	
	<title><?php echo $page->getTitle(); ?></title>
	
	<?php foreach ($this->getPluginBag()->getStylesheets() as $stylesheet): ?>
	<link href="<?php echo $this->asset($stylesheet); ?>" rel="stylesheet" />
	<?php endforeach; ?>
	
	<?php foreach($this->getPluginBag()->getScripts() as $script): ?>
	<script src="<?php echo $this->asset($script); ?>"></script>
	<?php endforeach; ?>
	
  </head>

  <body>
	<header>
		<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		  <div class="container">
			<div class="navbar-header">
			  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  </button>
			  <a class="navbar-brand" href="/">Bono Framework</a>
			</div>
			<div class="collapse navbar-collapse">
			  <ul class="nav navbar-nav">
				<li><a href="#about">Home</a></li>
				<li class="active"><a href="#">Manual</a></li>
			  </ul>
			</div><!--/.nav-collapse -->
		  </div>
		</div>
	</header>
	
    <main>
		<div class="row">
			<div class="col-lg-7">
				<nav><?php echo $menu->render('main'); ?></nav>
			</div>
			
			<div class="col-lg-4">
				<article><?php echo $page->getContent(); ?></article>
			</div>
		</div>
    </main>
	
	
	<footer>
		<article>(c) Bono Team</article>
	</footer>

  </body>
</html>
