<?php

use Krystal\Form\HtmlHelper;

?>
<!DOCTYPE html>
<html>
<head>
 <meta charset="UTF-8" />
 <title><?php echo $page->getTitle(); ?></title>
 
 <meta name="description" content="<?php echo $page->getMetaDescription(); ?>" />
 <meta name="keywords" content="<?php echo $page->getKeywords(); ?>" />
 <meta name="robots" content="" />
 <meta name="viewport" content="initial-scale=1.0, width=device-width" />
 
 <?php foreach ($this->getPluginBag()->getStylesheets() as $stylesheet): ?>
 <link rel="stylesheet" href="<?php echo $stylesheet; ?>" media="all" />
 <?php endforeach; ?>
 
 <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
 <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
 <![endif]-->
 
</head>
<body>

<main>
 <header>
  <nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
		  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </button>
		  <a class="navbar-brand" href="/"><i class="glyphicon glyphicon-th-large"></i> <?php echo $block->render('header'); ?></a>
		</div>
	    <div id="navbar" class="navbar-collapse collapse">
		  <form action="<?php echo $search->getUrl(); ?>" class="navbar-form navbar-right">
			<div class="form-group">
			  <input type="text" name="<?php echo $search->getElementName(); ?>" class="form-control" placeholder="<?php $this->show('Looking for something?'); ?>" />
			</div>
			<button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-search"></i> <?php $this->show('Search'); ?></button>
		  </form>
		  <ul class="nav navbar-nav navbar-right">
			<li>
			 <a href="<?php echo $basket->getUrl(); ?>"><i class="glyphicon glyphicon-shopping-cart"></i> <?php $this->show('Basket'); ?> 
			 (<?php $this->show('Total products'); ?> <label data-basket-label="total-products-qty"> <?php echo $basket->getTotalQty(); ?></label>, 
			 <label data-basket-label="total-products-price"><?php echo $basket->getTotalPrice(); ?></label> <?php echo $basket->getCurrency(); ?>)
			 </a>
			</li>
		  </ul>
	    </div>
	</div>
   </nav>
	
	<?php if ($slider->has('main')): ?>
	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
	  <!-- Indicators -->
	  <ol class="carousel-indicators">
       <?php foreach($slider->getAll('main') as $index => $slide): ?>
       <li data-target="#carousel-example-generic" data-slide-to="<?php echo $index; ?>" <?php HtmlHelper::addClassOnDemand($index == 0, 'active'); ?>></li>
       <?php endforeach; ?>
	  </ol>
	  
	  <!-- Wrapper for slides -->
	  <div class="carousel-inner" role="listbox">
		<?php foreach ($slider->getAll('main') as $index => $slide): ?>
		<div class="item <?php HtmlHelper::addOnDemand($index == 0, 'active'); ?>">
		  <img src="<?php echo $slide->getImageBag()->getUrl('1600x356'); ?>" alt="<?php echo $slide->getName(); ?>" />
		  <div class="carousel-caption">
			<h3><?php echo $slide->getName(); ?></h3>
			<p><?php echo $slide->getDescription(); ?></p>
		  </div>
		</div>
		<?php endforeach; ?>
	  </div>
	  
	   <!-- Controls -->
	  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	  </a>
	  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	  </a>
	</div>
	<?php endif; ?>
   
 </header>
 
 <section>
  <nav class="top-menu">
   <?php echo $menu->renderByClass('top', $page->getWebPageId()); ?>
  </nav>
  
  <?php if ($this->getBreadcrumbBag()->has()): ?>
  <ul class="breadcrumb">
  <?php foreach ($this->getBreadcrumbBag()->getBreadcrumbs() as $breadcrumb): ?>
  <?php if ($breadcrumb->isActive()): ?>
  <li class="active"><?php echo $breadcrumb->getName(); ?></li>
  <?php else: ?>
  <li><a href="<?php echo $breadcrumb->getLink(); ?>"><?php echo $breadcrumb->getName(); ?></a></li>
  <?php endif; ?>
  <?php endforeach; ?>
  </ul>
  <?php endif; ?>
  
  <?php if ($flashMessenger->has('success')): ?>
  
  <div class="alert alert-dismissible alert-success">
   <button type="button" class="close" data-dismiss="alert">x</button>
   <i class="glyphicon glyphicon-ok"></i> <?php $this->show($flashMessenger->get('success')); ?>
  </div>
  
  <?php endif; ?>
  
  <?php if ($flashMessenger->has('warning')): ?>
  
  <div class="alert alert-dismissible alert-warning">
   <button type="button" class="close" data-dismiss="alert">x</button>
   <i class="glyphicon glyphicon-ok"></i> <?php $this->show($flashMessenger->get('warning')); ?>
  </div>

  <?php endif; ?>
  
  <?php echo $fragment; ?>
  

 <footer>
  <div class="row">
   <div class="col-lg-3">
    <h3><?php echo $menu->getCategoryNameByClass('nav'); ?></h3>
    <?php echo $menu->renderByClass('nav'); ?>
   </div>
  
   <div class="col-lg-3">
	 <h3><?php echo $menu->getCategoryNameByClass('partners'); ?></h3>
	 <?php echo $menu->renderByClass('partners'); ?>
   </div>
  </div>
	
 <div class="row">
  <div class="pull-right">
	<!--Counter can be place here
	<img src="<?php echo $this->asset('/img/counter.png'); ?>" >
	<img src="<?php echo $this->asset('/img/counter.png'); ?>" >
	-->
  </div>
 </div>
	
 <address>
  <div class="social-block block-center text-center"></div>
  <h2><small><?php echo $block->render('footer'); ?></small></h2>
 </address>
 
 </footer>
</section>


<!--Product added success modal-->
<div class="modal fade" id="added-success" tabindex="-1" role="dialog" aria-labelledby="mdLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="mdLabel"><?php $this->show('Added'); ?></h4>
      </div>
      <div class="modal-body"><?php $this->show('The product has been added to your basket'); ?></div>
      <div class="modal-footer">
        <a class="btn btn-primary" data-dismiss="modal"><i class="glyphicon glyphicon-ok"></i> OK</a>
        <a class="btn btn-primary" href="<?php echo $basket->getUrl(); ?>"><i class="glyphicon glyphicon-shopping-cart"></i> <?php $this->show("To basket's page"); ?></a>
      </div>
    </div>
  </div>
</div>
<!--/Product added success modal-->

<!--Product added success modal-->
<div class="modal fade" id="ajax-modal" tabindex="-1" role="dialog" aria-labelledby="mdLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="mdLabel"><?php $this->show('Please wait'); ?></h4>
      </div>
      <div class="modal-body">
	    <img class="center-block" src="<?php echo $this->asset('/img/ajax.gif'); ?>" />
	  </div>
    </div>
  </div>
</div>
<!--/Product added success modal-->

</main>


<?php foreach ($this->getPluginBag()->getScripts() as $script): ?>
<script src="<?php echo $script; ?>"></script>
<?php endforeach; ?>

</body>
</html>
		