
<div class="container">
	<div class="row">
		<div class="col-lg-6">
            <?php $this->loadPartial('bs-form', array(
                'title' => $page->getTitle(),
                'captcha' => true,
                'fields' => array(
                    array(
                        'label' => 'Name', 
                        'attrs' => array(
                            'type' => 'text', 
                            'name' => 'name', 
                            'placeholder' => 'Type your name'
                        )
                    ),
                    array(
                        'label' => 'Email',
                        'attrs' => array(
                            'type' => 'text', 
                            'name' => 'email', 
                            'placeholder' => 'Type your email if you want us to reply'
                        )
                    ),
                    array(
                        'label' => 'Message',
                        'attrs' => array(
                            'type' => 'textarea',
                            'name' => 'message',
                            'placeholder' => 'Type your message',
                            'rows' => '3'
                        )
                    )
                ),
                'length' => array(
                    'field' => '10',
                    'label' => '2'
                )
                
            )); ?>
		</div>
		
		<div class="col-lg-6">
			<article><?php echo $page->getDescription(); ?></article>
		</div>
		
	</div>
</div>
