
<div class="container">
	
	<div class="pull-right">
		<h4 title="<?php $this->show('Views'); ?>" class="text-muted"><i class="glyphicon glyphicon-eye-open"></i> <?php echo $post->getViewCount(); ?></h4>
	</div>
	
	<div class="page-header">
		<h3><?php echo $post->getTitle(); ?> <small><?php echo $post->getTimeBag()->getPostFormat(); ?></small></h3>
	</div>
	
	<?php if ($post->hasCover()): ?>
	<div class="col-xs-6 col-md-3">
		<a href="<?php echo $post->getUrl(); ?>" class="thumbnail">
			<img src="<?php echo $post->getImageBag()->getUrl('300x300'); ?>" alt="<?php echo $post->getTitle(); ?>" />
		</a>
	</div>
	<?php endif; ?>
	
	<article><?php echo $post->getFull(); ?></article>
</div>
