<?php

use Krystal\Form\Element;

?>

<h1 class="text-muted"><?php echo $category->getTitle(); ?> (<?php echo $paginator->getTotalAmount(); ?>)</h1>

<div class="container">
	
	<div class="row">
		<div class="col-lg-4 pull-left">
			<label><?php $this->show('Sort method'); ?>: </label>
            <?php echo Element::select(null, $sorter->getSortingOptions(), $sorter->getSortOption(), array('data-category-option' => 'sort')); ?>
		</div>
		
		<div class="col-lg-2 pull-right">
			<p class="text-muted"><small><?php $this->show('Displayed'); ?>: <?php echo $paginator->getSummary(); ?></small></p>
			<span class="text-muted"><?php $this->show('Per page'); ?>: </span>
            <?php echo Element::select(null, $ppc->getPerPageCountValues(), $ppc->getPerPageCount(), array('data-category-option' => 'per-page-count')); ?>
		</div>
	</div>

	<?php if (!empty($products)): ?>
	
	<?php $this->loadPartial('product-block'); ?>
	<?php $this->loadPartial('bs-pagination'); ?>

	<br />
	
	<article><?php echo $category->getDescription(); ?></article>
	<?php else: ?>
	
	<h2><?php $this->show('No products in this category'); ?></h2>
	<?php endif; ?>
</div>
