<h1 class="text-muted"><?php echo $category->getTitle(); ?> (<?php echo $paginator->getTotalAmount(); ?>)</h1>

<div class="container">
	
	<div class="row">
		<div class="col-lg-4 pull-left">
			<label><?php $this->show('Sort method'); ?>: </label>
			<select data-category-option="sort">
				<?php foreach ($sortOptions as $sort): ?>
				<option value="<?php echo $sort->getValue(); ?>" <?php $this->getHelper()->selectOnDemand($sort->isCurrent()); ?>><?php $this->show($sort->getName()); ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		
		<div class="col-lg-2 pull-right">
			<p class="text-muted"><small><?php $this->show('Displayed'); ?>: <?php echo $paginator->getSummary(); ?></small></p>
			<span class="text-muted"><?php $this->show('Per page'); ?>: </span>
			<select data-category-option="per-page-count">
				
				<?php foreach ($perPageCounts as $option): ?>
				<option value="<?php echo $option->getValue(); ?>" <?php $this->getHelper()->selectOnDemand($option->isCurrent()); ?>><?php echo $option->getName(); ?></option>
				<?php endforeach; ?>
				
			</select>
		</div>
		
	</div>

	<?php if (!empty($products)): ?>
	
	<?php $this->loadBlock('product-block'); ?>
	<?php $this->loadBlock('paginate'); ?>

	<br />
	
	<article><?php echo $category->getDescription(); ?></article>
	<?php else: ?>
	
	<h2><?php $this->show('No products in this category'); ?></h2>
	<?php endif; ?>
</div>
