<?php if ($basket->isEnabled()): ?>

<?php if (!empty($products)): ?>

<div class="pull-right clearfix">
	<button class="btn btn-primary" data-toggle="modal" data-target="#emptyBasketConfirm"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Empty the basket'); ?></button>
</div>

<div>
	<h2><?php echo $page->getTitle(); ?></h2>
	<article><?php echo $page->getContent(); ?></article>
</div>

<div class="row">
	<div class="col-lg-4 form-horizontal">
		<form data-basket-form="order">
			<fieldset>
				<legend>
					<label><?php $this->show("Order now"); ?>&nbsp;</label>
					<small class="text-muted">
						<label data-basket-label="total-products-price"><?php echo $basket->getTotalPrice(); ?></label>
						<label data-basket-label="currency"><?php echo $basket->getCurrency(); ?></label>
					</small>
				</legend>

				<div class="form-group">
					<label for="inputName" class="col-lg-3 control-label"><?php $this->show('Your name'); ?></label>
					<div class="col-lg-9">
						<input type="text" class="form-control" name="name" id="inputName" placeholder="<?php $this->show('Type your name'); ?>" />
					</div>
				</div>
				
				<div class="form-group">
					<label for="inputPhone" class="col-lg-3 control-label"><?php $this->show('Phone'); ?></label>
					<div class="col-lg-9">
						<input type="text" class="form-control" name="phone" id="inputPhone" placeholder="<?php $this->show('Your contact phone'); ?>" />
					</div>
				</div>
				
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><?php $this->show('Your email'); ?></label>
					<div class="col-lg-9">
						<input type="text" class="form-control" name="email" id="inputEmail" placeholder="<?php $this->show('Type your email'); ?>" />
					</div>
				</div>
				
				<div class="form-group">
					<label for="inputAddress" class="col-lg-3 control-label"><?php $this->show('Address'); ?></label>
					<div class="col-lg-9">
						<textarea class="form-control" rows="3" name="address" id="inputAddress" placeholder="<?php $this->show("Delivery address"); ?>"></textarea>
					</div>
				</div>
				
				<div class="form-group">
					<label for="inputComment" class="col-lg-3 control-label"><?php $this->show('Comment'); ?></label>
					<div class="col-lg-9">
						<textarea class="form-control" rows="3" name="comment" id="inputComment" placeholder="<?php $this->show("If you have additional information for us, type it here"); ?>"></textarea>
					</div>
				</div>
				
				<div class="form-group">
					<label for="select" class="col-lg-3 control-label"><?php $this->show('Delivery type'); ?></label>
					<div class="col-lg-9">
						<select class="form-control" name="delivery" id="select">
							<?php foreach ($deliveryTypes as $deliveryType): ?>
							<option><?php $this->show($deliveryType); ?></option>
							<?php endforeach; ?>
						</select>
					</div>
				</div>
				
				<div class="form-group">
					<label for="inputCaptcha" class="col-lg-3 control-label"></label>
					<div class="col-lg-9">
						<a href="#" title="Click to refresh" data-captcha="button-refresh"><img data-captcha="image" src="/captcha/render/" /></a>
					</div>
				</div>
				
				<div class="form-group">
					<label for="inputCaptcha" class="col-lg-3 control-label"></label>
					<div class="col-lg-9">
						<input type="text" class="form-control" id="inputCaptcha" name="captcha" placeholder="<?php $this->show("Enter what you see on the image above"); ?>" />
					</div>
				</div>
				
				<div class="form-group">
					<div class="col-lg-9 pull-right clearfix">
						<button type="submit" class="btn btn-primary" data-basket-button="order"><i class="glyphicon glyphicon-shopping-cart"></i> <?php $this->show("Order now"); ?></button>
						<button type="reset" class="btn btn-default"><i class="glyphicon glyphicon-remove"></i> <?php $this->show("Cancel"); ?></button>
					</div>
				</div>
				
			</fieldset>
		</form>
	</div>
	
	
	<div class="col-lg-8 table-responsive">
		
		<table class="table table-condensed table-bordered table-striped table-hover">
			<thead>
				<tr>
					<th class="text-center"><?php $this->show('Product'); ?></th>
					<th></th>
					<th class="text-center"><?php $this->show('Price'); ?></th>
					<th class="text-center"><?php $this->show('Amount'); ?></th>
					<th class="text-center"><?php $this->show('Subtotal'); ?></th>
					<th></th>
				</tr>
			</thead>
			
			<tbody>
				
				<?php foreach ($products as $product): ?>

				<tr data-basket-product-id="<?php echo $product->getId(); ?>" data-basket-type="container">
					<td>
						<center>
							<a href="<?php echo $product->getUrl(); ?>"><img class="img-responsive" src="<?php echo $product->getImageUrl('120x120'); ?>" /></a>
						</center>
					</td>

					<td class="text-center">
						<a href="<?php echo $product->getUrl(); ?>"><?php echo $product->getTitle(); ?></a>
					</td>

					<td class="text-center">
						<?php echo $product->getPrice(); ?> <label data-basket-label="currency"><?php echo $basket->getCurrency(); ?></label>
					</td>
					
					<td class="data-basket-qty-container">
						<div class="input-group">
							<input type="number" class="form-control" data-basket-product-id="<?php echo $product->getId(); ?>" data-basket-input="recount" min="1" value="<?php echo $product->getQty(); ?>" maxlength="12" />
							<span class="input-group-btn">
								<button class="btn btn-primary" data-basket-product-id="<?php echo $product->getId(); ?>" data-basket-button="product-recount"><i class="glyphicon glyphicon-refresh"></i></button>
							</span>
						</div>
					</td>

					<td class="text-center">
						<label data-basket-product-id="<?php echo $product->getId(); ?>" data-basket-label="sub-total-price"><?php echo $product->getSubTotalPrice(); ?></label>
						<span data-basket-label="currency"><?php echo $basket->getCurrency(); ?></span>
					</td>
					
					<td class="text-center">
						<a href="#" data-toggle="modal" data-target="#removeProductConfirm" data-basket-button="product-delete-with-confirm" data-basket-product-id="<?php echo $product->getId(); ?>"><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>


<!--Basket clear confirmation dialog-->
<div class="modal fade" id="emptyBasketConfirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><?php $this->show('Are you sure?'); ?></h4>
      </div>
      <div class="modal-body"><?php $this->show('Do you really want to empty your basket?'); ?></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-basket-button="clear-without-confirm" data-dismiss="modal"><i class="glyphicon glyphicon-ok"></i> <?php $this->show('Yes'); ?></button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Cancel'); ?></button>
      </div>
    </div>
  </div>
</div>
<!-- /Basket clear confirmation dialog-->



<!--Basket clear confirmation dialog-->
<div class="modal fade" id="removeProductConfirm" tabindex="-1" role="dialog" aria-labelledby="removeProductConfirmLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="removeProductConfirmLabel"><?php $this->show('Are you sure?'); ?></h4>
      </div>
      <div class="modal-body"><?php $this->show('Do you really want remove this product from your basket?'); ?></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal" data-basket-button="product-delete-confirm-yes"><i class="glyphicon glyphicon-ok"></i> <?php $this->show('Yes'); ?></button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Cancel'); ?></button>
      </div>
    </div>
  </div>
</div>
<!-- /Basket clear confirmation dialog-->

<?php else: ?>

<div class="col-lg-7">
	<h2 class="text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Basket is empty'); ?></h2>
</div>

<div class="clearfix"></div>

<?php endif; ?>

<?php else: ?>

<h2><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Basket is disabled'); ?></h2>

<?php endif; ?>