<h1 class="text-muted"><?php echo $page->getTitle(); ?> (<?php echo $paginator->getTotalAmount(); ?>)</h1>

<div class="container">

	<?php if (!empty($products)): ?>
	
	<?php $this->loadPartial('product-block'); ?>
	<?php $this->loadPartial('bs-pagination'); ?>

	<br />
	
	<article><?php echo $page->getDescription(); ?></article>
	<?php else: ?>
	
	<h2><?php $this->show('No stokes at this moment'); ?></h2>
	<?php endif; ?>

</div>
