<?php

use Krystal\Form\Element;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Cms:Admin:Languages@addAction'); ?>"><i class="glyphicon glyphicon-globe"></i> <?php $this->show('Add a language'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		
		 <?php if (!empty($langs)): ?>
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Cms:Admin:Languages@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <?php endif; ?>
		 
	  </ul>
	</div>
</div>

<h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Languages'); ?> </h4>

<form>
	<div class="table-responsive">
		<table class="table table-hover table-bordered table-striped table-condensed">
			<thead>
				<tr>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Name'); ?></th>
					<th class="text-center"><?php $this->show('Code'); ?></th>
					<th class="text-center"><?php $this->show('Order'); ?></th>
					<th class="text-center"><?php $this->show('Published'); ?></th>
					<th class="text-center"><?php $this->show('Default'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>
			
			<?php if (!empty($langs)): ?>
			<tbody>
				<?php foreach ($langs as $language): ?>
				<tr>
					<td class="text-center text-muted"><?php echo $language->getId(); ?></td>
					<td class="text-center"><i class="<?php printf('famfamfam-flag-%s', $language->getFlag()); ?>"></i> <?php echo $language->getName(); ?></td>
					<td class="text-center"><?php echo $language->getCode(); ?></td>
					<td class="text-center col-md-1">
                        <?php echo Element::number(sprintf('order[%s]', $language->getId()), $language->getOrder(), array('class' => 'form-control center-block', 'min' => '0')); ?>
					</td>
					<td class="text-center">
                        <?php echo Element::checkbox(sprintf('published[%s]', $language->getId()), $language->getPublished()); ?>
					</td>
					<td class="text-center">
                        <?php echo Element::radio('default', $language->getId(), $language->getDefault()); ?>
					</td>
					<td class="text-center">
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this language'); ?>" data-button="edit" href="<?php echo $this->url('Cms:Admin:Languages@editAction', $language->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this language'); ?>" data-button="delete" data-id="<?php echo $language->getId(); ?>" data-category="language" href="#"><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
			<?php endif; ?>
		</table>

		<?php if (empty($langs)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No languages'); ?></h2>
		</div>
		<?php endif; ?>
		
	</div>
</form>
