<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Cms:Admin:Languages@addAction'); ?>"><i class="glyphicon glyphicon-globe"></i> <?php $this->show('Add a language'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		
		 <?php if (!empty($langs)): ?>
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Cms:Admin:Languages@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <?php endif; ?>
		 
	  </ul>
	</div>
</div>

<h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Languages'); ?> <small>(<?php echo count($langs); ?>)</small></h4>

<form>
	<div class="table-responsive">
        <?= Grid::render($langs, array(
            'batch' => true,
            'pk' => 'id',
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'flag',
                    'value' => function($language){
                        return sprintf('<i class="famfamfam-flag-%s"></i>', $language->getFlag());
                    }
                ),

                array(
                    'column' => 'code'
                ),

                array(
                    'column' => 'name'
                ),

                array(
                    'column' => 'order',
                    'value' => function($language){
                        return Element::number(sprintf('order[%s]', $language->getId()), $language->getOrder(), array('class' => 'form-control center-block', 'min' => '0'));
                    }
                ),

                array(
                    'column' => 'published',
                    'value' => function($language){
                        return Element::checkbox(sprintf('published[%s]', $language->getId()), $language->getPublished());
                    }
                ),

                array(
                    'column' => 'default',
                    'value' => function($language){
                        return Element::radio('default', $language->getId(), $language->getDefault());
                    }
                )
            ),

            'actions' => array(
                'edit' => function($language){
                    return Icon::edit(
                        $this->url('Cms:Admin:Languages@editAction', $language->getId()),
                        $this->translate('Edit this language')
                    );
                },

                'remove' => function($language){
                    return Icon::remove(
                        $this->url('Cms:Admin:Languages@deleteAction', $language->getId()),
                        $this->translate('Remove this language')
                    );
                }
            )

        ), $this->translator); ?>        
		<?php if (empty($langs)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No languages'); ?></h2>
		</div>
		<?php endif; ?>
		
	</div>
</form>
