<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bono CMS: You're arrived!</title>
	
	<?php foreach ($this->getPluginBag()->getStylesheets() as $style): ?>
	<link href="<?php echo $style; ?>" rel="stylesheet" />
	<?php endforeach; ?>
	
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body role="document">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><i class="glyphicon glyphicon-th-large"></i> Bono CMS</a>
        </div>

      </div>
    </nav>
	
    <div class="container theme-showcase" role="main">
      <div class="jumbotron">
        <h1>Welcome to Bono CMS!</h1>
		<?php echo $fragment; ?>
		
		<p><a target="_blank" href="http://bono-cms.tk" class="btn btn-primary btn-lg" role="button">Visit web-site &raquo;</a></p>
      </div>
      
	  <div class="row">
        <div class="col-lg-4">
          <h2>Very simple API</h2>
          <p>What you should know before you start working, is that CMS is totally modular. And its modules have services. That's all you need to know to start using API!</p>
        </div>
		
        <div class="col-lg-4">
          <h2>Easy to use and extend</h2>
          <p>It's no longer painful to add or removed some functionality</p>
        </div>
        
		<div class="col-lg-4">
          <h2>Clean code</h2>
          <p>The codebase has been tested many times and follows proven best OOP practises</p>
        </div>
      </div>
    </div>
	
	<?php foreach ($this->getPluginBag()->getScripts() as $script): ?>
	<script src="<?php echo $script; ?>"></script>
    <?php endforeach;?>
   
  </body>
</html>
