
<?php if (!empty($categories)): ?>

<form>
	<div class="well clearfix">
		
		<input type="hidden" name="id" value="<?php echo $announce->getId(); ?>" />
		<input type="hidden" name="web_page_id" value="<?php echo $announce->getWebPageId(); ?>" />
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="title" class="form-control" placeholder="<?php $this->show('Announce title'); ?>" value="<?php echo $announce->getTitle(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
				<div class="input-group date">
					<input type="text" name="name" class="form-control" placeholder="<?php $this->show('Name of this announce'); ?>" value="<?php echo $announce->getName(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil" data-toggle="tooltip"></i></span>
				</div>
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Category'); ?></label>
			<div class="col-lg-10">
				<select name="category_id" class="form-control">
					
					<?php foreach ($categories as $category): ?>
					<option value="<?php echo $category->getId(); ?>" <?php $this->getHelper()->selectOnDemand($category->getId() == $announce->getCategoryId()); ?>><?php echo $category->getName(); ?></option>
					<?php endforeach; ?>
					
				</select>
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Introduction'); ?></label>
			<div class="col-lg-10">				
				<textarea name="intro" class="form-control"><?php echo $announce->getIntro(); ?></textarea>
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Full text'); ?></label>
			<div class="col-lg-10">
				<textarea name="full" class="form-control"><?php echo $announce->getFull(); ?></textarea>
			</div>
		</div>
		
		<div class="options">
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
				<div class="col-lg-10">
					<input type="hidden" name="published" value="0" />
					<input type="checkbox" name="published" value="1" class="form-control" <?php $this->getHelper()->checkOnDemand($announce->getPublished()); ?>/>
				</div>
			</div>
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
				<div class="col-lg-10">
					<input type="hidden" name="seo" value="0" />
					<input type="checkbox" name="seo" value="1" class="form-control" <?php $this->getHelper()->checkOnDemand($announce->getSeo()); ?> />
				</div>
			</div>
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
				<div class="col-lg-10">
					<div class="input-group">
						<input type="number" name="order" class="form-control"  placeholder="<?php $this->show('Order of the announce to be created'); ?>" value="<?php echo $announce->getOrder(); ?>" />
						<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
					</div>
				</div>
			</div>
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
				<div class="col-lg-10">
					<div class="input-group">
						<input type="text" name="slug" class="form-control" placeholder="<?php $this->show('URL slug for this announce. By default is taken from a title'); ?>" value="<?php echo $announce->getSlug(); ?>" />
						<span class="input-group-addon">
							<a href="#" data-button="slug"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh'); ?>"></i></a>
						</span>
					</div>
				</div>
			</div>
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
				<div class="col-lg-10">
					<div class="input-group">
						<input type="text" name="keywords" class="form-control"  placeholder="<?php $this->show('Keywords used for search engines'); ?>" value="<?php echo $announce->getKeywords() ;?>" />
						<span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
					</div>
				</div>
			</div>
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Meta-Description'); ?></label>
				<div class="col-lg-10">
					<textarea name="meta_description" class="form-control" placeholder="<?php $this->show('Meta description for search engines'); ?>"><?php echo $announce->getMetaDescription(); ?></textarea>
				</div>
			</div>
			
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Cover'); ?></label>
				<div class="col-lg-10">
					<?php if ($announce->getCover() !== ''): ?>
					
					<br />
					<br />
					
					<?php endif; ?>
					
					<input type="file" name="file" />
				</div>
			</div>
			
		</div>
	</div>
	
	<?php if ($announce->getId()): ?>
	
	<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Save & Create new'); ?></button>
	
	<?php else: ?>
	
	<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Add & Create new'); ?></button>
	
	<?php endif; ?>
	
	<button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
	<button data-button="cancel" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
	
</form>

<?php else: ?>

<div class="well">

	<div class="center-block">
		<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('In order to add a new announce, you have to create at least on category'); ?></h2>
	</div>

</div>

<?php endif; ?>