<?php

use Krystal\Form\Widget\CheckBoxWidget;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> 
		<span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Announcement:Admin:Announce:Add@indexAction'); ?>"><i class="glyphicon glyphicon-plus"></i> <?php $this->show('Add new announce'); ?></a></li>
		 <li><a href="<?php echo $this->url('Announcement:Admin:Category:Add@indexAction'); ?>"><i class="glyphicon glyphicon-plus"></i> <?php $this->show('Add a category'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 
		 <?php if (!empty($announces)): ?>
		 <li><a data-button="save-changes" href="#"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a data-button="remove-selected" href="#"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<?php $this->loadBlock('items-per-page', array('caption' => 'Announcements')); ?>

<form>
	<div class="table-responsive">
		<table class="table table-hover table-bordered table-striped table-condensed">
			<thead>
				<tr>
					<th class="text-center">
						<input type="checkbox" />
					</th>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Name'); ?></th>
					<th class="text-center"><?php $this->show('Category'); ?></th>
					<th class="text-center"><?php $this->show('Order'); ?></th>
					<th class="text-center"><?php $this->show('Published'); ?></th>
					<th class="text-center"><?php $this->show('SEO'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>
			
			<?php if (!empty($announces)): ?>
			<tbody>
				<?php foreach ($announces as $announce): ?>
				<tr>
					<td class="text-center">
						<input type="checkbox" name="toDelete[<?php echo $announce->getId(); ?>]" />
					</td>
					<td class="text-center text-muted"><?php echo $announce->getId(); ?></td>
					<td class="text-center"><?php echo $announce->getName(); ?></td>
					<td class="text-center"><?php echo $announce->getCategoryName(); ?></td>
					<td class="col-lg-1">
						<input type="number" min="0" class="form-control" name="order[<?php echo $announce->getId(); ?>]" value="<?php echo $announce->getOrder(); ?>" />
					</td>
					<td class="text-center">
						<?php echo CheckBoxWidget::render(array('name' => sprintf('published[%s]', $announce->getId())), $announce->getPublished()); ?>
					</td>
					<td class="text-center">
						<?php echo CheckBoxWidget::render(array('name' => sprintf('seo[%s]', $announce->getId())), $announce->getSeo()); ?>
					</td>
					<td class="text-center">
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('View this announce'); ?>" data-button="view" href="<?php echo $announce->getUrl(); ?>" target="_blank" ><i class="glyphicon glyphicon-search"></i></a>
						<a data-button="edit" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this announce'); ?>" href="<?php echo $this->url('Announcement:Admin:Announce:Edit@indexAction', $announce->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
						<a data-button="delete" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this announce'); ?>" data-id="<?php echo $announce->getId(); ?>" data-category="announce" href="#"><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				
				<?php endforeach; ?>
			</tbody>
			<?php endif; ?>
			
		</table>
		
		<?php if (empty($announces)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No announces'); ?></h2>
		</div>
		<?php endif; ?>
	</div>
</form>

<?php $this->loadBlock('paginator'); ?>

<div class="table-responsive clearfix">
	<h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Categories'); ?> (<?php echo count($categories); ?>)</h4>
	
	<table class="table table-hover table-bordered table-striped table-condensed">
		<thead>
			<tr>
				<th class="text-center"><?php $this->show('#'); ?></th>
				<th class="text-center"><?php $this->show('Name'); ?></th>
				<th class="text-center"><?php $this->show('Class'); ?></th>
				<th class="text-center"><?php $this->show('Actions'); ?></th>
			</tr>
		</thead>
		
		<?php if (!empty($categories)): ?>
		<tbody>
			<?php foreach ($categories as $category): ?>
			<tr>
				<td class="text-center text-muted"><?php echo $category->getId(); ?></td>
				<td class="text-center">
					<a href="<?php echo $this->url('Announcement:Admin:Browser@categoryAction', $category->getId()); ?>">
						<?php if (isset($categoryId) && $categoryId == $category->getId()): ?>
						<strong><?php echo $category->getName(); ?></strong>
						<?php else: ?>
						<?php echo $category->getName(); ?>
						<?php endif; ?>
					</a>
				</td>
				<td class="text-center"><?php echo $category->getClass(); ?></td>
				<td class="text-center">
					<a data-toggle="tooltip" data-placement="left" data-button="edit" data-original-title="<?php $this->show('Edit this category'); ?>" href="<?php echo $this->url('Announcement:Admin:Category:Edit@indexAction', $category->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
					<a data-toggle="tooltip" data-placement="left" data-button="delete" data-original-title="<?php $this->show('Remove this category'); ?>" data-id="<?php echo $category->getId(); ?>" data-category="category" href="#"><i class="glyphicon glyphicon-remove"></i></a>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
		<?php endif; ?>
	</table>
	
	<?php if (empty($categories)): ?>
	<div class="center-block">
	 <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
	</div>
	<?php endif; ?>
	
</div>
