<form>
	<div class="well clearfix">
		
		<input type="hidden" name="id" value="<?php echo $category->getId(); ?>" />
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="name" class="form-control" placeholder="<?php $this->show('Category name'); ?>" value="<?php echo $category->getName(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		<?php if ($extendedMode): ?>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Class'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="class" class="form-control" placeholder="<?php $this->show('Class to simplify rendering'); ?>" value="<?php echo $category->getClass(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		<?php else: ?>
		
		<input type="hidden" name="class" value="<?php echo $category->getClass(); ?>" />
		
		<?php endif; ?>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Maximal depth'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="number" name="max_depth" class="form-control" placeholder="<?php $this->show('Maximal allowed nested level for items'); ?>" value="<?php echo $category->getMaxDepth(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
	</div>
	
	<?php if ($category->getId()): ?>
	<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	
	<?php else: ?>
	
	<button data-button="add" type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<?php endif; ?>
	
	<button data-button="cancel" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
	
</form>
