<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> 
		<span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Team:Admin:Add@indexAction'); ?>"><i class="glyphicon glyphicon-plus"></i> <?php $this->show('Add a member'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 
		 <?php if (!empty($members)): ?>
		 <li><a href="#" data-button="save-changes"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<?php $this->loadBlock('items-per-page', array('caption' => 'Team')); ?>

<form>
	<div class="table-responsive">
		<table class="table table-hover table-bordered table-striped table-condensed">
			<thead>
				<tr>
					<th class="text-center">
						<input type="checkbox" />
					</th>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Photo'); ?></th>
					<th class="text-center"><?php $this->show('Name'); ?></th>
					<th class="text-center"><?php $this->show('Order'); ?></th>
					<th class="text-center"><?php $this->show('Published'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>
			
			<?php if (!empty($members)): ?>
			<tbody>
				
				<?php foreach ($members as $member): ?>
				<tr>
					<td class="text-center">
						<input type="checkbox" name="toDelete[<?php echo $member->getId(); ?>]" />
					</td>
					<td class="text-center text-muted"><?php echo $member->getId(); ?></td>
					<td>
						<img class="img-responsive center-block" src="<?php echo $member->getImageBag()->getUrl('400x200'); ?>" />
					</td>
					<td class="text-center"><?php echo $member->getName(); ?></td>
					<td class="text-center col-md-1">
						<input type="number" class="form-control" min="0" name="order[<?php echo $member->getId(); ?>]" value="<?php echo $member->getOrder(); ?>" />
					</td>
					<td class="text-center">
						<input type="hidden" name="published[<?php echo $member->getId(); ?>]" value="0" />
						<input type="checkbox" name="published[<?php echo $member->getId(); ?>]" value="1" <?php $this->getHelper()->checkOnDemand($member->getPublished()); ?>/>
					</td>
					<td class="text-center">
						<a data-button="edit" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit the member'); ?>" href="<?php echo $this->url('Team:Admin:Edit@indexAction', $member->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
						<a data-button="delete" data-category="main" data-id="<?php echo $member->getId(); ?>" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this member'); ?>" href="#" ><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				<?php endforeach; ?>
				
			</tbody>
			<?php endif; ?>
			
		</table>
		
		<?php if (empty($members)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No members'); ?></h2>
		</div>
		<?php endif; ?>
		
	</div>
	
</form>

<?php $this->loadBlock('paginator'); ?>
