<?php

use Krystal\Form\Widget\CheckBoxWidget;

?>

<form>
	
	<input type="hidden" name="team[id]" value="<?php echo $member->getId(); ?>" />
	<input type="hidden" name="team[photo]" value="<?php echo $member->getPhoto(); ?>" />
	
	<div class="well clearfix">
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="team[name]" class="form-control" placeholder="<?php $this->show("Member's name"); ?>" value="<?php echo $member->getName(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
			<div class="col-lg-10">
				<textarea name="team[description]" rows="7" class="form-control"><?php echo $member->getDescription(); ?></textarea>
			</div>
		</div>
		
		
		<div class="form-group clearfix clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Photo'); ?></label>
			<div class="col-lg-10">
				
				<?php if ($member->getPhoto()): ?>
				<img class="img-responsive" src="<?php echo $member->getImageBag()->getUrl('400x200');?>" />
				
				<?php else: ?>
				<img data-image="preview" />
				
				<?php endif; ?>
				
				<br />
				<br />
				
				<input type="file" name="file" accept="image/x-png, image/gif, image/jpeg" />
			</div>
		</div>
		
		
		<div class="options">
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
				<div class="col-lg-10">
					<?php echo CheckBoxWidget::render(array('name' => 'team[published]', 'class' => 'form-control'), $member->getPublished()); ?>
				</div>
			</div>
			
			<div class="form-group clearfix">
				<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
				<div class="col-lg-10">
					<input type="number" name="team[order]" class="form-control" placeholder="<?php $this->show("Member's sort order"); ?>" value="<?php echo $member->getOrder(); ?>" />
				</div>
			</div>
			
		</div>
		
	</div>
	
	
	<?php if ($member->getId()): ?>
	<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
	
	<?php else: ?>
	
	<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
	
	<?php endif; ?>
	
	<button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
	<button data-button="cancel" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
	
</form>
