<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> 
		<span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Pages:Admin:Add@indexAction'); ?>"><i class="glyphicon glyphicon-plus"></i> <?php $this->show('Add new page'); ?></a></li>
		 
		 <?php if ($extendedMode): ?>
		 <li><a href="<?php echo $this->url('Pages:Admin:Config@indexAction'); ?>"><i class="glyphicon glyphicon-th-large"></i> <?php $this->show('Configuration'); ?></a></li>
		 <?php endif; ?>
		 
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 
		 <?php if (!empty($pages)): ?>
		 <li><a href="#" data-button="save-changes"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-button="remove-selected"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<?php $this->loadBlock('items-per-page', array('caption' => 'Pages')); ?>

<form>
	<div class="table-responsive">
		<table class="table table-striped table-hover table-bordered table-condensed">
			<thead>
				<tr>
					<th class="text-center"><input type="checkbox" /></th>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Title'); ?></th>
					<th class="text-center"><?php $this->show('Default'); ?></th>
					<th class="text-center"><?php $this->show('SEO'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>
			
			<?php if (!empty($pages)): ?>
			<tbody>
				<?php foreach ($pages as $page): ?>
				
				<tr>
					<td class="text-center">
						<?php if (!(!$extendedMode && $page->getProtected())): ?>
						<input type="checkbox" name="toDelete[<?php echo $page->getId(); ?>]" />
						<?php endif; ?>
					</td>
					<td class="text-center text-muted"><?php echo $page->getId(); ?></td>
					<td class="text-center"><?php echo $page->getTitle(); ?></td>
					
					<td class="text-center">
						<input type="radio" name="default" value="<?php echo $page->getId(); ?>" <?php $this->getHelper()->checkOnDemand($page->isDefault()); ?>/>
					</td>
					
					<td class="text-center">
						<input type="hidden" name="seo[<?php echo $page->getId(); ?>]" value="0" />
						<input type="checkbox" name="seo[<?php echo $page->getId(); ?>]" value="1" <?php $this->getHelper()->checkOnDemand($page->getSeo()); ?>/>
					</td>
					<td class="text-center">
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('View this page on site'); ?>" data-button="view" target="_blank" href="<?php echo $page->getUrl(); ?>"><i class="glyphicon glyphicon-search"></i></a>
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this page'); ?>" data-button="edit" href="<?php echo $this->url('Pages:Admin:Edit@indexAction', $page->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
						
						<?php if ($extendedMode || !($page->isDefault() || $page->getProtected())): ?>
						
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this page'); ?>" data-button="delete" data-category="main" data-id="<?php echo $page->getId(); ?>" href="#" ><i class="glyphicon glyphicon-remove"></i></a>
						
						<?php endif; ?>
						
					</td>
				</tr>
				
				<?php endforeach; ?>
			</tbody>
			<?php endif; ?>
			
		</table>
		
		<?php if (empty($pages)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No pages'); ?></h2>
		</div>
		<?php endif; ?>
		
	</div>
</form>

<?php $this->loadBlock('paginator'); ?>
