<form>
	<div class="well clearfix">
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show("Page's template"); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="page_template" class="form-control" value="<?php echo $config->getPageTemplate(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
				<span class="help-block"><?php $this->show("Framework-compliant template's name for all static pages"); ?></span>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show("Home page's template"); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="home_template" class="form-control" value="<?php echo $config->getHomeTemplate(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
				<span class="help-block"><?php $this->show("Framework-compliant template's name for the home page"); ?></span>
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Not found template'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<input type="text" name="nf_template" class="form-control" value="<?php echo $config->getNfTemplate(); ?>" />
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
				<span class="help-block"><?php $this->show("Framework-compliant template's name for 404 pages"); ?></span>
			</div>
		</div>
		
	</div>
	
	<button data-button="save" type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="cancel" type="button" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
	
</form>