<form>
	<ul class="nav nav-tabs" role="tablist">
	 <li role="presentation" class="active"><a href="#page" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Page'); ?></a></li>
	 <li role="presentation"><a href="#menu" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-list"></i> <?php $this->show('Item in menu'); ?></a></li>
	</ul>
	
	
	<div class="tab-content">
		
		<div class="tab-pane fade in active" id="page" role="tabpanel">
			<div class="well clearfix">
				
				<?php $form->show('id'); ?>
				<?php $form->show('web_page_id'); ?>
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
							<?php $form->show('title'); ?>
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
				
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Content'); ?></label>
					<div class="col-lg-10">
						<?php $form->show('content'); ?>
					</div>
				</div>
				
				
				<div class="options">
					
					<?php if (!$extendedMode): ?>
					<div class="hidden">
					<?php endif; ?>
					
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Controller'); ?></label>
						<div class="col-lg-10">
							<?php $form->show('controller'); ?>
						</div>
					</div>
					
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Template override'); ?></label>
						<div class="col-lg-10">
							<div class="input-group">
								<?php $form->show('template'); ?>
								<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
							</div>
						</div>
					</div>
					
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Protect'); ?></label>
						<div class="col-lg-10">
							<?php $form->show('protected'); ?>
						</div>
					</div>
					
					<?php if (!$extendedMode): ?>
					</div>
					<?php endif; ?>
					
					
					<?php if (!isset($editing)): ?>
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Make default'); ?></label>
						<div class="col-lg-10">
							<?php $form->show('makeDefault'); ?>
						</div>
					</div>
					<?php endif; ?>
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
						<div class="col-lg-10">
							<?php $form->show('seo'); ?>
						</div>
					</div>
					
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
						<div class="col-lg-10">
							<div class="input-group">
								<?php $form->show('slug'); ?>
								
								<span class="input-group-addon">
									<a href="#" data-button="slug"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i></a>
								</span>
							</div>
						</div>
					</div>
					
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
						<div class="col-lg-10">
							<div class="input-group">
								<?php $form->show('keywords'); ?>
								<span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
							</div>
						</div>
					</div>
					
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
						<div class="col-lg-10">
							<?php $form->show('meta_description'); ?>
						</div>
					</div>
					
				</div>
			</div>
			
			<?php if ($form->isNewRecord()): ?>
			
			<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
			<button data-button="add-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
			
			<?php else: ?>
			
			<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
			<button data-button="save-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
			
			<?php endif; ?>
			
			<button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
			<button data-button="cancel" type="button" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
			
		</div>
		
		<div class="tab-pane fade" id="menu" role="tabpanel">
			<?php $this->loadBlock('menu-widget'); ?>
		</div>
	</div>
</form>
